
import { Card } from '../../../types';

export const PENTACLES: Card[] = [
    {
        id: 'pentacles-1', name: 'Érmék Ásza', nameEn: 'Ace of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 1,
        element: 'Föld', astrology: 'Föld elem gyökere (Bika/Szűz/Bak)', numerology: '1',
        keywords: ['Lehetőség', 'Bőség', 'Kezdet', 'Manifesztáció', 'Jólét'],
        meaningUpright: 'Új vállalkozás kezdete, siker lehetősége, anyagi és szellemi igazodás.',
        meaningReversed: 'Erős alap hiánya, anyagi veszteség kockázata.',
        generalMeaning: 'Lehetőség a boldogságra és stabilitásra. Kézzelfogható eredmények.',
        loveMeaning: 'Tartós kapcsolat esélye, elmélyülés és megszilárdulás.',
        careerMeaning: 'Kiváló lehetőség előmenetelre, jövedelmező üzletre.',
        advice: 'Ragadd meg a szerencsédet! Alapozd meg a jövőded.',
        dailyMeaning: 'Ma szerencsés napod lehet anyagi ügyekben.',
        yearlyMeaning: 'A lehetőségek éve. Anyagi vagy erkölcsi haszonra teszel szert.',
        questions: ['Életének mely területein szeretne bőséget?', 'Milyen vagyonod van már, amit figyelmen kívül hagysz?'],
        affirmation: "Hittel ültetem el céljaimat.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-1.jpg',
        shortDesc: 'Az Anyagi Mag',
        comparison: {
            title: 'Érmék Ásza vs. Botok Ásza',
            text: 'Míg a Botok Ásza a tiszta kreatív impulzust és a cselekvés kezdetét jelzi, az Érmék Ásza a kézzelfogható, fizikai megnyilvánulást és a hosszú távú biztonság alapkövét képviseli.',
            relatedCardId: 'wands-1'
        }
    },
    {
        id: 'pentacles-2', name: 'Érmék Kettes', nameEn: '2 of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 2,
        element: 'Föld', astrology: 'Jupiter a Bakban', numerology: '2',
        keywords: ['Egyensúly', 'Zsonglőrködés', 'Alkalmazkodás', 'Rugalmasság', 'Változás'],
        meaningUpright: 'Egyensúlyozás, kötelezettségek zsonglőrködése, alkalmazkodás.',
        meaningReversed: 'Kiegyensúlyozatlanság, diszharmónia, túlvállalás.',
        generalMeaning: 'Játékos alkalmazkodás és rugalmasság a változásokhoz.',
        loveMeaning: 'Játékos, könnyed időszak, vagy alkalmazkodá a körülményekhez.',
        careerMeaning: 'Rugalmasságot követel. Több vasat tartasz a tűzben.',
        advice: 'Légy rugalmas! Ne vedd túl komolyan a dolgokat.',
        dailyMeaning: 'Ma sűrű napod lehet. Vedd könnyedén.',
        yearlyMeaning: 'A hullámzás éve. Élvezd a változatosságot.',
        questions: ['Milyen feladatot tudnál elengedni?', 'Milyen ellentéteket tartasz fenn egyszerre?'],
        affirmation: "Egyensúlyt teremtek az életemben.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-2.jpg'
    },
    {
        id: 'pentacles-3', name: 'Érmék Hármas', nameEn: '3 of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 3,
        element: 'Föld', astrology: 'Mars a Bakban', numerology: '3',
        keywords: ['Csapatmunka', 'Együttműködés', 'Tanulás', 'Szakértelem', 'Tervezés'],
        meaningUpright: 'Együttműködés, közösség, tanítás és tanulás, csapatmunka.',
        meaningReversed: 'Nehézségek az együttműködésben, ego összecsapása.',
        generalMeaning: 'A vizsga és a minőségi munka kártyája. Magasabb szintre lépés.',
        loveMeaning: 'Döntő lépés a kapcsolatban. Közös jövő építése.',
        careerMeaning: 'Sikeres vizsga vagy előléptetés. Szakmai elismerés.',
        advice: 'Bizonyítsd a tudásodat! Működj együtt másokkal.',
        dailyMeaning: 'Ma vizsgázhatsz valamiből. Légy alapos.',
        yearlyMeaning: 'A szintlépés éve. Tanulmányaidat siker koronázza.',
        questions: ['Melyik részedet osztod meg másokkal?', 'Szeretsz csapatban dolgozni?'],
        affirmation: "Belépek a tudatos együttműködésbe.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-3.jpg'
    },
    {
        id: 'pentacles-4', name: 'Érmék Négyes', nameEn: '4 of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 4,
        element: 'Föld', astrology: 'Nap a Bakban', numerology: '4',
        keywords: ['Stabilitás', 'Kontroll', 'Biztonság', 'Birtoklás', 'Kuporgatás'],
        meaningUpright: 'Stabilitás, megtakarítás, siker, irányítás fenntartása.',
        meaningReversed: 'Felhalmozás, túl nagy érték a pénznek, mohóság.',
        generalMeaning: 'Túlzott ragaszkodás és görcsös biztonságvágy kártyája.',
        loveMeaning: 'Birtoklási vágy, féltékenység. Megmerevedett kapcsolat.',
        careerMeaning: 'Ragaszkodás a pozícióhoz, félelem az újítástól. Anyagiasság.',
        advice: 'Engedd el! Légy nagylelkűbb másokkal.',
        dailyMeaning: 'Ma hajlamos lehetsz a kicsinyességre. Lazíts.',
        yearlyMeaning: 'A stagnálás éve. Ne félj a fejlődéstől.',
        questions: ['Mi az, amihoz túl erősen ragaszkodsz?', 'Hogyan vélekedsz a nagylelkűségedről?'],
        affirmation: "Bőséges életet élek.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-4.jpg'
    },
    {
        id: 'pentacles-5', name: 'Érmék Ötös', nameEn: '5 of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 5,
        element: 'Föld', astrology: 'Merkúr a Bikában', numerology: '5',
        keywords: ['Szükség', 'Veszteség', 'Elszigeteltség', 'Segítségkérés', 'Szegénység'],
        meaningUpright: 'Anyagi nehézségek, elszigeteltség, segítségkérés.',
        meaningReversed: 'Szűkös gondolkodásmód, áldozat szerep, fény az alagút végén.',
        generalMeaning: 'A nélkülözés és a bizonytalanság kártyája. Keress segítséget.',
        loveMeaning: 'Elhagyatottság érzése egy kapcsolaton belül is. Krízis.',
        careerMeaning: 'Anyagi gondok, munkanélküliségtől való félelem.',
        advice: 'Kérj segítséget! Nyisd ki a szemed a lehetőségekre.',
        dailyMeaning: 'Ma nehézségekbe ütközhetsz. Ne add fel a reményt.',
        yearlyMeaning: 'A szűk esztendő. Megtanulod értékelni azt, amit van.',
        questions: ['Milyen történetet engednél el a gazdagságodról?', 'Kit vagy mit zársz ki?'],
        affirmation: "A lehetőségek ajtói megnyílnak előttem.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-5.jpg'
    },
    {
        id: 'pentacles-6', name: 'Érmék Hatos', nameEn: '6 of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 6,
        element: 'Föld', astrology: 'Hold a Bikában', numerology: '6',
        keywords: ['Nagylelkűség', 'Adakozás', 'Hála', 'Megosztás', 'Jótékonyság'],
        meaningUpright: 'Adás és fogadás bősége, jótékonyság, nagylelkűség.',
        meaningReversed: 'Túlzott adakozás, felhalmozás, önzés.',
        generalMeaning: 'A nagylelkűség és az adok-kapok egyensúlyának kártyája.',
        loveMeaning: 'Kölcsönös támogatás és tolerancia a kapcsolatban.',
        careerMeaning: 'Támogatást kapsz a céljaidhoz. Jutalom várható.',
        advice: 'Légy nagylelkű! Oszd meg a tudásodat másokkal.',
        dailyMeaning: 'Ma segíts valakin vagy fogadj el segítséget.',
        yearlyMeaning: 'A támogatás éve. Megkapod a segítséget a céljaidhoz.',
        questions: ['Hol tudnál többet adni?', 'Hol lehetnél kiegyensúlyozottabb?'],
        affirmation: "Nagylelkűséggel mutatok hálát az életemért.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-6.jpg'
    },
    {
        id: 'pentacles-7', name: 'Érmék Hetes', nameEn: '7 of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 7,
        element: 'Föld', astrology: 'Szaturnusz a Bikában', numerology: '7',
        keywords: ['Türelem', 'Befektetés', 'Várakozás', 'Értékelés', 'Növekedés'],
        meaningUpright: 'Szünet és gondolkodás, újraértékelés, betakarításra várás.',
        meaningReversed: 'Túl korai feladás, türelmetlenség, hitvesztés.',
        generalMeaning: 'A türelem kártyája. Elvetettük a magokat, várni kell.',
        loveMeaning: 'Lassú fejlődés. Ne sürgesd a kapcsolatot.',
        careerMeaning: 'Hosszú távú befektetés, lassú megtérülés. Kitartás kell.',
        advice: 'Légy türelmes! Adj időt a dolgoknak, hogy beérjenek.',
        dailyMeaning: 'Ma ne várj gyors eredményt. Légy kitartó.',
        yearlyMeaning: 'A lassú érés éve. A végén gazdag lesz a szüret.',
        questions: ['Mennyi a hited, amikor nem látod a bizonyítékot?', 'Mit tehetnél, amíg vársz?'],
        affirmation: "Hálát adok azért, amit betakarítok.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-7.jpg'
    },
    {
        id: 'pentacles-8', name: 'Érmék Nyolcas', nameEn: '8 of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 8,
        element: 'Föld', astrology: 'Sun in Virgo', numerology: '8',
        keywords: ['Szorgalom', 'Mesterkedés', 'Részletek', 'Fejlődés', 'Szakértelem'],
        meaningUpright: 'Készség elsajátítása, szakértő mesterség, elszántság.',
        meaningReversed: 'Kiégés, feladás, tapasztalatlanság, perfekcionizmus.',
        generalMeaning: 'A szorgalom és a tanulás kártyája. Jó úton haladsz.',
        loveMeaning: 'Új fejezet. Hajlandó vagy dolgozni a kapcsolaton.',
        careerMeaning: 'Új munkahely vagy átképzés. Szorgalmas tanulás.',
        advice: 'Dolgozz szorgalmasan! Élvezd magát a tevékenységet.',
        dailyMeaning: 'Ma tanulhatsz valami újat. Légy alapos.',
        yearlyMeaning: 'A tanulás éve. Új készségeket sajátítasz el.',
        questions: ['Hogyan köteleződsz el az utad iránt?', 'Mit mesterkedsz most?'],
        affirmation: " Kitartok, és azzá válok, aki lenni vágyom.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-8.jpg'
    },
    {
        id: 'pentacles-9', name: 'Érmék Kilences', nameEn: '9 of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 9,
        element: 'Föld', astrology: 'Venus in Virgo', numerology: '9',
        keywords: ['Függetlenség', 'Jólét', 'Önbizalom', 'Kifinomultság', 'Luxus'],
        meaningUpright: 'Lelki és anyagi elégedettség, belső béke, aratás.',
        meaningReversed: 'Munkamánia, magány az anyagi sikerben.',
        generalMeaning: 'Szerencsés fordulat és anyagi függetlenség kártyája.',
        loveMeaning: 'Kellemes meglepetés, harmónia és elégedettség.',
        careerMeaning: 'Siker, előléptetés, váratlan bónusz. Anyagi biztonság.',
        advice: 'Élvezd a sikert! Légy büszke arra, amit elértél.',
        dailyMeaning: 'Ma valami jó dolog történhet veled.',
        yearlyMeaning: 'A bőség éve. Függetlenséget élvezhetsz.',
        questions: ['Mi okozza a legnagyobb örömöt?', 'Mikor voltál utoljára büszke magadra?'],
        affirmation: "Méltó vagyok a boldogságra és bőségre.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-9.jpg'
    },
    {
        id: 'pentacles-10', name: 'Érmék Tizes', nameEn: '10 of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 10,
        element: 'Föld', astrology: 'Mercury in Virgo', numerology: '10',
        keywords: ['Örökség', 'Család', 'Gazdagság', 'Hosszú távú siker', 'Közösség'],
        meaningUpright: 'Bőség, közösség, örökség építése, pozitív eredmények.',
        meaningReversed: 'Luxus hajszolása, pénzügyi veszteség vagy késés.',
        generalMeaning: 'A gazdagság és a családi stabilitás kártyája. Révbe érés.',
        loveMeaning: 'Családi boldogság, stabil háttér, hosszú távú elköteleződés.',
        careerMeaning: 'Biztos egzisztencia, sikeres vállalkozás, hosszú távú siker.',
        advice: 'Értékeld a stabilitást! Építs maradandó értékeket.',
        dailyMeaning: 'Ma élvezd a biztonságot és a családodat.',
        yearlyMeaning: 'A bőség éve. Anyagilag és érzelmileg is révbe érsz.',
        questions: ['Hogyan hat a gazdagság a bőségedre?', 'Mik a pénzcéljaid?'],
        affirmation: "Sikeres vagyok, és megosztom az örömömet.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-10.jpg'
    },
    {
        id: 'pentacles-page', name: 'Érmék Apródja', nameEn: 'Page of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 11,
        element: 'Föld', astrology: 'Föld elem földi aspektusa', numerology: '11',
        keywords: ['Tanulás', 'Lehetőség', 'Gyakorlatiasság', 'Hűség', 'Új munka'],
        meaningUpright: 'Új tanulmányok, anyagi lehetőségek, hűség, gyakorlatias tervek, ambíció.',
        meaningReversed: 'Lassú haladás, elszalasztott lehetőség, lustaság, irreális célok.',
        generalMeaning: 'Egy új lehetőség az anyagi világban vagy a tanulásban. Fiatalos, tettre kész energia.',
        loveMeaning: 'Hűséges, stabil alapokon nyugvó új kapcsolat vagy megújuló elkötelezettség.',
        careerMeaning: 'Új munkalehetőség, előléptetés tanulás révén, szakmai fejlődés kezdete.',
        advice: 'Légy türelmes és alapos! Tanulj meg minden részletet.',
        dailyMeaning: 'Ma érkezhet egy jó üzleti vagy tanulmányi hír.',
        yearlyMeaning: 'Az alapozás éve. Most sajátíthatod el a jövőbeli sikereidhez szükséges tudást.',
        questions: ['Mit kell ma megtanulnod?', 'Milyen anyagi célod van, amiért hajlandó vagy dolgozni?'],
        affirmation: "Megfontoltan építem a jövőmet és nyitott vagyok a tanulásra.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-page.jpg'
    },
    {
        id: 'pentacles-knight', name: 'Érmék Lovagja', nameEn: 'Knight of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 12,
        element: 'Föld', astrology: 'Szűz / Föld elem levegő aspektusa', numerology: '12',
        keywords: ['Szorgalom', 'Felelősség', 'Kitartás', 'Rutin', 'Megbízhatóság'],
        meaningUpright: 'Kemény munka, módszeresség, türelem, becsület, lassú de biztos haladás.',
        meaningReversed: 'Munkamánia, unalom, rugalmatlanság, elakadás a rutinban.',
        generalMeaning: 'A kitartó munka és a megbízhatóság mintaképe. Ő az, aki célba ér, mert sosem adja fel.',
        loveMeaning: 'Kiszámítható, biztonságos de néha egyhangú kapcsolat. Mély hűség.',
        careerMeaning: 'Alapos munkavégzés, adminisztrációs siker, hosszú távú stabilitás.',
        advice: 'Tarts ki a terveid mellett! A lassú tempó most kifizetődik.',
        dailyMeaning: 'Ma végezd el a feladataidat szorgalmasan. A rutin most a barátod.',
        yearlyMeaning: 'A szorgalom éve. Kitartó munkával maradandót alkothatsz.',
        questions: ['Elég türelmes vagy önmagadhoz?', 'Mi az a rutinfeladat, ami valójában a biztonságodat szolgálja?'],
        affirmation: "Lépésről lépésre haladok a céljaim felé, és élvezem a folyamatot.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-knight.jpg'
    },
    {
        id: 'pentacles-queen', name: 'Érmék Királynője', nameEn: 'Queen of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 13,
        element: 'Föld', astrology: 'Bika / Föld elem vizes aspektusa', numerology: '13',
        keywords: ['Gondoskodás', 'Bőség', 'Gyakorlatiasság', 'Biztonság', 'Nagylelkűség'],
        meaningUpright: 'Szerető gondoskodás, otthonteremtés, anyagi biztonság, józan ész, nagylelkűség.',
        meaningReversed: 'Bizonytalanság, elhanyagolás, féltékenység, túlzott anyagiasság.',
        generalMeaning: 'A földanya archetípusa. Képes a semmiből is bőséget teremteni és másokat táplálni.',
        loveMeaning: 'Meleg, oltalmazó fészek. Érzéki és stabil partnerség.',
        careerMeaning: 'Sikeres menedzselés, pénzügyi tudatosság, jól jövedelmező munkahely.',
        advice: 'Gondoskodj magadról és a környezetedről! Teremts kényelmet.',
        dailyMeaning: 'Ma kényeztesd magad vagy főzz valami finomat a szeretteidnek.',
        yearlyMeaning: 'A gyarapodás éve. Megszilárdíthatod az otthonodat és az anyagi helyzetedet.',
        questions: ['Hogyan tehetnéd ma szebbé az otthonodat?', 'Mire van szüksége a testednek a jóléthez?'],
        affirmation: "Bőségben élek, és örömmel gondoskodom a világról.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-queen.jpg'
    },
    {
        id: 'pentacles-king', name: 'Érmék Királya', nameEn: 'King of Pentacles', arcana: 'Minor', suit: 'Érmék', number: 14,
        element: 'Föld', astrology: 'Bak / Föld elem tüzes aspektusa', numerology: '14',
        keywords: ['Siker', 'Gazdagság', 'Hatalom', 'Szakértelem', 'Fegyelem'],
        meaningUpright: 'Üzleti siker, anyagi mestermunka, biztonság, stabilitás, tekintély.',
        meaningReversed: 'Korrupció, fukarság, kockázatkerülés, érzelemmentes anyagiasság.',
        generalMeaning: 'A megvalósult álmok és a földi hatalom ura. Tudja, hogyan kell bánni a pénzzel és az energiával.',
        loveMeaning: 'Biztos támasz, nagylelkű partner, aki számára fontos a család védelme.',
        careerMeaning: 'Csúcsvezetői pozíció, sikeres vállalkozás, szakmai elismertség.',
        advice: 'Gondolkozz nagyban! Használd a tapasztalatodat a stabilitás érdekében.',
        dailyMeaning: 'Ma fontos anyagi döntést hozhatsz meg sikeresen.',
        yearlyMeaning: 'A beteljesülés éve az anyagban. Minden erőfeszítésed beérik.',
        questions: ['Mi a te birodalmad?', 'Hogyan tudnád bölcsebben kezelni a forrásaidat?'],
        affirmation: "Mestere vagyok a saját világomnak, és stabilitást teremtek másoknak is.",
        imageUrl: 'https://myralog.hu/tarot/pentacles-king.jpg'
    }
];
