import { WesternHoroscope } from '../types';

export const WESTERN_HOROSCOPES: WesternHoroscope[] = [
    {
        id: "libra",
        name: "Mérleg",
        dates: "Szeptember 23 - Október 22",
        symbol: "A Mérleg",
        rulingPlanet: "Vénusz",
        houseRuled: "Hetedik",
        element: "Levegő",
        mode: "Kardinális",
        keyword: "Kapcsolódom",
        description: "A Mérleg a harmónia és a kapcsolatok jegye, amely az egyensúlyra törekszik a polaritások között. A Mérlegek jó ízlésükről, eleganciájukról és bájukról ismertek. Természetes életmódjuk a másokkal való partnerség. Foglalkoztatják őket a társadalmi igazságosság kérdései, és született diplomaták. Küzdhetnek a határozott döntések meghozatalával.",
        strengths: ["Együttműködő", "Diplomatikus", "Bájos", "Igazságos", "Társasági"],
        weaknesses: ["Határozatlan", "Kerüli a konfrontációt", "Haragtartó", "Önsajnálat", "Megggondolatlan"],
        likes: ["Harmónia", "Gyengédség", "Megosztani másokkal", "Szabadban lenni"],
        dislikes: ["Erőszak", "Igazságtalanság", "Hangoskodók", "Konformitás"],
        color: "Kék",
        luckyGem: "Zafír",
        flower: "Rózsa",
        day: "Péntek",
        numbers: "4, 6, 13, 15, 24",
        mostCompatible: "Oroszlán, Ikrek, Nyilas",
        leastCompatible: "Halak, Rák, Bika"
    },
    {
        id: "aries",
        name: "Kos",
        dates: "Március 21 - Április 19",
        symbol: "A Kos",
        rulingPlanet: "Mars",
        houseRuled: "Első",
        element: "Tűz",
        mode: "Kardinális",
        keyword: "Vagyok",
        description: "A Kos a kezdetek és a bátorság jegye.",
        strengths: ["Bátor", "Határozott", "Őszinte"],
        weaknesses: ["Türelmetlen", "Hangulatember", "Lobbanékony"],
        likes: ["Kényelmes ruhák", "Vezetői szerep", "Kihívások"],
        dislikes: ["Tétlenség", "Késés", "Nem őt választják"],
        color: "Vörös",
        luckyGem: "Gyémánt",
        flower: "Loncre",
        day: "Kedd",
        numbers: "1, 8, 17",
        mostCompatible: "Mérleg, Oroszlán",
        leastCompatible: "Bika, Rák"
    },
    {
        id: "taurus",
        name: "Bika",
        dates: "Április 20 - Május 20",
        symbol: "A Bika",
        rulingPlanet: "Vénusz",
        houseRuled: "Második",
        element: "Föld",
        mode: "Szilárd",
        keyword: "Birtoklok",
        description: "A Bika a stabilitás és az érzékiség jegye.",
        strengths: ["Megbízható", "Türelmes", "Gyakorlatias"],
        weaknesses: ["Makacs", "Birtokló", "Kompromisszumképtelen"],
        likes: ["Kertészkedés", "Főzés", "Zene", "Romantika"],
        dislikes: ["Hirtelen változások", "Bonyodalmak", "Bizonytalanság"],
        color: "Zöld",
        luckyGem: "Smaragd",
        flower: "Pipacs",
        day: "Péntek",
        numbers: "2, 6, 9, 12, 24",
        mostCompatible: "Skorpió, Rák",
        leastCompatible: "Vízöntő, Ikrek"
    },
    {
        id: "gemini",
        name: "Ikrek",
        dates: "Május 21 - Június 20",
        symbol: "Az Ikrek",
        rulingPlanet: "Merkúr",
        houseRuled: "Harmadik",
        element: "Levegő",
        mode: "Változó",
        keyword: "Gondolkodom",
        description: "Az Ikrek a kommunikáció és a kíváncsiság jegye.",
        strengths: ["Gyengéd", "Kíváncsi", "Alkalmazkodó"],
        weaknesses: ["Ideges", "Következetlen", "Határozatlan"],
        likes: ["Zene", "Könyvek", "Beszélgetés"],
        dislikes: ["Egyedüllét", "Korlátozás", "Ismétlődés"],
        color: "Sárga",
        luckyGem: "Achát",
        flower: "Levendula",
        day: "Szerda",
        numbers: "5, 7, 14, 23",
        mostCompatible: "Nyilas, Vízöntő",
        leastCompatible: "Halak, Szűz"
    },
    {
        id: "cancer",
        name: "Rák",
        dates: "Június 21 - Július 22",
        symbol: "A Rák",
        rulingPlanet: "Hold",
        houseRuled: "Negyedik",
        element: "Víz",
        mode: "Kardinális",
        keyword: "Érezek",
        description: "A Rák az otthon és az érzelmek jegye.",
        strengths: ["Kitartó", "Nagy képzelőerő", "Hűséges"],
        weaknesses: ["Hangulatember", "Pesszimista", "Gyanakvó"],
        likes: ["Művészet", "Otthoni hobbik", "Vízpart"],
        dislikes: ["Idegenek", "Kritika", "Magánélet felfedése"],
        color: "Fehér",
        luckyGem: "Gyöngy",
        flower: "Liliom",
        day: "Hétfő",
        numbers: "2, 3, 15, 20",
        mostCompatible: "Bak, Skorpió",
        leastCompatible: "Ikrek, Nyilas"
    },
    {
        id: "leo",
        name: "Oroszlán",
        dates: "Július 23 - Augusztus 22",
        symbol: "Az Oroszlán",
        rulingPlanet: "Nap",
        houseRuled: "Ötödik",
        element: "Tűz",
        mode: "Szilárd",
        keyword: "Alkotok",
        description: "Az Oroszlán a kreativitás és a dráma jegye.",
        strengths: ["Kreatív", "Szenvedélyes", "Nagylelkű"],
        weaknesses: ["Arrogáns", "Makacs", "Lusta"],
        likes: ["Színház", "Vakáció", "Drága dolgok"],
        dislikes: ["Mellőzés", "Nehéz valóság", "Nem királyi bánásmód"],
        color: "Arany",
        luckyGem: "Rubin",
        flower: "Napraforgó",
        day: "Vasárnap",
        numbers: "1, 3, 10, 19",
        mostCompatible: "Vízöntő, Ikrek",
        leastCompatible: "Bak, Halak"
    },
    {
        id: "virgo",
        name: "Szűz",
        dates: "Augusztus 23 - Szeptember 22",
        symbol: "A Szűz",
        rulingPlanet: "Merkúr",
        houseRuled: "Hatodik",
        element: "Föld",
        mode: "Változó",
        keyword: "Elemzek",
        description: "A Szűz a szolgálat és a részletek jegye.",
        strengths: ["Hűséges", "Elemző", "Kedves"],
        weaknesses: ["Félénk", "Aggodalmaskodó", "Túlzottan kritikus"],
        likes: ["Állatok", "Egészséges étel", "Természet"],
        dislikes: ["Durvaság", "Kérés segítsége nélkül", "Rendetlenség"],
        color: "Szürke",
        luckyGem: "Zafír",
        flower: "Nefelejcs",
        day: "Szerda",
        numbers: "5, 14, 15, 23, 32",
        mostCompatible: "Halak, Rák",
        leastCompatible: "Nyilas, Oroszlán"
    },
    {
        id: "scorpio",
        name: "Skorpió",
        dates: "Október 23 - November 21",
        symbol: "A Skorpió",
        rulingPlanet: "Plútó",
        houseRuled: "Nyolcadik",
        element: "Víz",
        mode: "Szilárd",
        keyword: "Kívánok",
        description: "A Skorpió a szenvedély és az átalakulás jegye.",
        strengths: ["Erőforrásokban gazdag", "Bátor", "Szenvedélyes"],
        weaknesses: ["Bizalmatlan", "Féltékeny", "Titkolózó"],
        likes: ["Igazság", "Tények", "Igaza lenni"],
        dislikes: ["Hazugság", "Passzivitás", "Titkok felfedése"],
        color: "Skarlátvörös",
        luckyGem: "Topáz",
        flower: "Muskátli",
        day: "Kedd",
        numbers: "8, 11, 18, 22",
        mostCompatible: "Bika, Rák",
        leastCompatible: "Oroszlán, Vízöntő"
    },
    {
        id: "sagittarius",
        name: "Nyilas",
        dates: "November 22 - December 21",
        symbol: "A Nyilas",
        rulingPlanet: "Jupiter",
        houseRuled: "Kilencedik",
        element: "Tűz",
        mode: "Változó",
        keyword: "Látok",
        description: "A Nyilas a filozófia és a kaland jegye.",
        strengths: ["Nagylelkű", "Idealista", "Humoros"],
        weaknesses: ["Türelmetlen", "Ígérgető", "Tapintatlan"],
        likes: ["Szabadság", "Utazás", "Filozófia"],
        dislikes: ["Ragaszkodó emberek", "Korlátozás", "Részletek"],
        color: "Lila",
        luckyGem: "Türkiz",
        flower: "Szegfű",
        day: "Csütörtök",
        numbers: "3, 7, 9, 12, 21",
        mostCompatible: "Ikrek, Kos",
        leastCompatible: "Szűz, Halak"
    },
    {
        id: "capricorn",
        name: "Bak",
        dates: "December 22 - Január 19",
        symbol: "A Bak",
        rulingPlanet: "Szaturnusz",
        houseRuled: "Tizedik",
        element: "Föld",
        mode: "Kardinális",
        keyword: "Hasznosítok",
        description: "A Bak a struktúra és a fegyelem jegye.",
        strengths: ["Felelősségteljes", "Fegyelmezett", "Önuralom"],
        weaknesses: ["Mindentudó", "Megbocsátásra képtelen", "Borúlátó"],
        likes: ["Család", "Hagyomány", "Zene"],
        dislikes: ["Szinte minden egy ponton"],
        color: "Barna",
        luckyGem: "Gránát",
        flower: "Árvácska",
        day: "Szombat",
        numbers: "4, 8, 13, 22",
        mostCompatible: "Rák, Bika",
        leastCompatible: "Kos, Nyilas"
    },
    {
        id: "aquarius",
        name: "Vízöntő",
        dates: "Január 20 - Február 18",
        symbol: "A Vízöntő",
        rulingPlanet: "Uránusz",
        houseRuled: "Tizenegyedik",
        element: "Levegő",
        mode: "Szilárd",
        keyword: "Tudok",
        description: "A Vízöntő az eredetiség és a haladás jegye.",
        strengths: ["Haladó szellemű", "Eredeti", "Független"],
        weaknesses: ["Érzelmek kerülése", "Temperamentumos", "Megalkuvást nem tűrő"],
        likes: ["Szórakozás barátokkal", "Segíteni másokon", "Intellektuális beszélgetés"],
        dislikes: ["Korlátok", "Be nem tartott ígéretek", "Unalom"],
        color: "Ezüst",
        luckyGem: "Ametiszt",
        flower: "Orchidea",
        day: "Szombat",
        numbers: "4, 7, 11, 22, 29",
        mostCompatible: "Oroszlán, Nyilas",
        leastCompatible: "Skorpió, Szűz"
    },
    {
        id: "pisces",
        name: "Halak",
        dates: "Február 19 - Március 20",
        symbol: "A Halak",
        rulingPlanet: "Neptunusz",
        houseRuled: "Tizenkettedik",
        element: "Víz",
        mode: "Változó",
        keyword: "Hiszek",
        description: "A Halak az empátia és a művészet jegye.",
        strengths: ["Együttérző", "Művészi", "Intuitív"],
        weaknesses: ["Félénk", "Szomorú", "Menekülő"],
        likes: ["Egyedüllét", "Alvás", "Zene", "Romantika"],
        dislikes: ["Mindentudók", "Kritika", "Múlt"],
        color: "Halványlila",
        luckyGem: "Akvamarin",
        flower: "Vízililiom",
        day: "Csütörtök",
        numbers: "3, 9, 12, 15, 18, 24",
        mostCompatible: "Szűz, Bika",
        leastCompatible: "Ikrek, Nyilas"
    }
];
