// Firestore szabály-tesztek. Futtatás (Java + firebase-tools + @firebase/rules-unit-testing + firebase szükséges):
//   firebase emulators:exec --only firestore --project demo-t "node tests/firestore.rules.test.mjs"  (firebase.json: firestore.rules + emulator port 8089)
import { initializeTestEnvironment, assertSucceeds, assertFails } from '@firebase/rules-unit-testing';
import { readFileSync } from 'fs';
import { doc, getDoc, setDoc, updateDoc, getDocs, collection, query, where, deleteDoc } from 'firebase/firestore';
const env = await initializeTestEnvironment({ projectId:'demo-t', firestore:{ rules: readFileSync('./firestore.rules','utf8'), host:'127.0.0.1', port:8089 }});
const A = env.authenticatedContext('a',{email:'a@x.com',email_verified:true}).firestore();
const B = env.authenticatedContext('b',{email:'b@x.com',email_verified:true}).firestore();
const ADM = env.authenticatedContext('adm',{email:'themadteam@gmail.com',email_verified:true}).firestore();
const ADMU = env.authenticatedContext('adm2',{email:'themadteam@gmail.com',email_verified:false}).firestore();
const anon = env.unauthenticatedContext().firestore();
let fail=0; const ok=async(n,p)=>{try{await p;console.log('PASS',n)}catch(e){fail++;console.log('FAIL',n,e.message.slice(0,90))}};
const no=async(n,p)=>ok(n,assertFails(p));
await ok('own profile write', assertSucceeds(setDoc(doc(A,'users/a'),{name:'A',isPublicProfile:true,username:'aa'})));
await no('other profile write', setDoc(doc(B,'users/a'),{name:'x'}));
await no('self-admin create', setDoc(doc(B,'users/b'),{name:'B',isAdmin:true}));
await ok('own create', assertSucceeds(setDoc(doc(B,'users/b'),{name:'B'})));
await no('self-promote', updateDoc(doc(B,'users/b'),{isAdmin:true}));
await ok('public profile get', assertSucceeds(getDoc(doc(B,'users/a'))));
await no('private profile get', getDoc(doc(A,'users/b')));
await ok('username query', assertSucceeds(getDocs(query(collection(B,'users'),where('username','==','aa'),where('isPublicProfile','==',true)))));
await no('username query w/o public', getDocs(query(collection(B,'users'),where('username','==','aa'))));
await no('read other readings', getDoc(doc(B,'users/a/readings/r1')));
await ok('post public reading', assertSucceeds(setDoc(doc(A,'public_readings/r1'),{userId:'a',likes:0,comments:[]})));
await no('spoof userId', setDoc(doc(B,'public_readings/r2'),{userId:'a'}));
await ok('other likes/comments', assertSucceeds(updateDoc(doc(B,'public_readings/r1'),{likes:1,comments:[{id:'c'}]})));
await no('other edits content', updateDoc(doc(B,'public_readings/r1'),{question:'hax'}));
await no('other deletes', deleteDoc(doc(B,'public_readings/r1')));
await ok('admin deletes', assertSucceeds(deleteDoc(doc(ADM,'public_readings/r1'))));
await no('unverified admin', deleteDoc(doc(ADMU,'users/a')));
await ok('anon read reading', assertSucceeds(getDoc(doc(anon,'public_readings/r1'))));
await no('anon write', setDoc(doc(anon,'public_readings/r9'),{userId:'x'}));
await ok('rate own', assertSucceeds(setDoc(doc(B,'public_decks/d1/ratings/b'),{userId:'b',rating:5})));
await no('rate as other', setDoc(doc(B,'public_decks/d1/ratings/a'),{userId:'a',rating:5}));
await no('rate 99', setDoc(doc(B,'public_decks/d1/ratings/b'),{userId:'b',rating:99}));
await ok('settings read anon', assertSucceeds(getDoc(doc(anon,'settings/global'))));
await no('settings write user', setDoc(doc(A,'settings/global'),{enableShop:false}));
await ok('settings write admin', assertSucceeds(setDoc(doc(ADM,'settings/global'),{enableShop:false})));
await ok('create session', assertSucceeds(setDoc(doc(A,'sessions/S1'),{hostId:'a',status:'waiting',drawnCards:[]})));
await ok('guest joins', assertSucceeds(setDoc(doc(B,'sessions/S1'),{hostId:'a',status:'active',drawnCards:[],guestName:'B'},{merge:true})));
await no('guest sets cards', updateDoc(doc(B,'sessions/S1'),{drawnCards:[1]}));
await ok('host cards', assertSucceeds(updateDoc(doc(A,'sessions/S1'),{drawnCards:[1]})));
await ok('notify other', assertSucceeds(setDoc(doc(A,'notifications/n1'),{userId:'b',type:'system',isRead:false})));
await no('read others notif', getDoc(doc(A,'notifications/n1')));
await ok('mark read', assertSucceeds(updateDoc(doc(B,'notifications/n1'),{isRead:true})));
await no('market write user', setDoc(doc(A,'market_items/m'),{x:1}));
await ok('event join', (async()=>{await setDoc(doc(A,'community_events/e'),{hostId:'a',participants:[]});await assertSucceeds(updateDoc(doc(B,'community_events/e'),{participants:['b'],participantDetails:[]}))})());
console.log(fail?`${fail} FAILED`:'ALL OK'); await env.cleanup(); process.exit(fail?1:0);
