
import { Card } from '../types';

export const CUPS: Card[] = [
    {
        id: 'cups-1', name: 'Kelyhek Ásza', nameEn: 'Ace of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 1,
        element: 'Víz', astrology: 'Víz elem gyökere (Rák/Skorpió/Halak)', numerology: '1',
        keywords: ['Szerelem', 'Új érzések', 'Kreativitás', 'Intuíció', 'Érzelmek'],
        meaningUpright: 'Új kapcsolatok, romantikus kapcsolatok, a szeretet magvai, öröm, kreativitás.',
        meaningReversed: 'Önszeretet táplálása, érzelmi elfojtás elkerülése.',
        generalMeaning: 'A Kelyhek Ásza a boldogság, a hála és a szeretet megélésének legnagyobb esélye.',
        loveMeaning: 'A "Nagy Szerelem" esélye. Mély szeretet és érzelmi biztonság.',
        careerMeaning: 'Hivatás megtalálása, megbecsülés a munkában.',
        advice: 'Nyílj meg! Hagyd, hogy az érzelmek szabadon áramoljanak.',
        dailyMeaning: 'Ma teljesülhet egy kívánságod. Nyisd ki a szívedet.',
        yearlyMeaning: 'A beteljesülés éve. Érzelmileg gazdag időszak vár rád.',
        questions: ['Milyen szerepet játszik ma a szerelem az életedben?', 'Milyen új érzések mozgatnak meg?'],
        affirmation: "Szívem nyitott és tele van szeretettel.",
        imageUrl: 'https://myralog.hu/tarot/cups-1.jpg',
        shortDesc: 'Az Érzelmi Áttörés',
        comparison: {
            title: 'Kelyhek Ásza vs. Kelyhek Kettes',
            text: 'Míg az Ász a tiszta érzelmi potenciált és az önmagunk felé áradó szeretetet jelképezi, a Kettes már két ember közötti harmonikus kapcsolódásról és egységről szól. Az Ász a forrás, a Kettes az áramlás.',
            relatedCardId: 'cups-2'
        }
    },
    {
        id: 'cups-2', name: 'Kelyhek Kettes', nameEn: '2 of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 2,
        element: 'Víz', astrology: 'Vénusz a Rákban', numerology: '2',
        keywords: ['Egység', 'Partnerség', 'Szerelem', 'Kapcsolat', 'Vonzalom'],
        meaningUpright: 'Romantikus partnerek, lélektársak, barátság, együttműködés, egyesülés.',
        meaningReversed: 'Érzelmi blokkok, diszharmónia, elválás.',
        generalMeaning: 'A szeretetteljes találkozás kártyája. Randevút vagy mély barátságot jelent.',
        loveMeaning: 'Szerelem első látásra vagy a kapcsolat elmélyülése. Kibékülés.',
        careerMeaning: 'Jó együttműködés, kellemes munkahelyi légkör.',
        advice: 'Közeledj másokhoz szeretettel! Tedd meg az első lépést.',
        dailyMeaning: 'Ma találkozhatsz valakivel, aki fontos lesz számodra.',
        yearlyMeaning: 'A szívügyek éve. Fontos találkozás vagy felvirágzás várható.',
        questions: ['Nyitott vagy új lélekkapcsolatok kialakítására?', 'Bízol magadban, hogy bevonzod a bőséget?'],
        affirmation: "Jól érzem magam a partnerségben, és élvezem a kapcsolat szent varázsát.",
        imageUrl: 'https://myralog.hu/tarot/cups-2.jpg'
    },
    {
        id: 'cups-3', name: 'Kelyhek Hármas', nameEn: '3 of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 3,
        element: 'Víz', astrology: 'Merkúr a Rákban', numerology: '3',
        keywords: ['Ünneplés', 'Barátság', 'Kreativitás', 'Közösség', 'Öröm'],
        meaningUpright: 'Barátságok, bőség, együttműködés, öröm, ünneplés.',
        meaningReversed: 'Félreértések, régi sebek gyógyításának igénye, kirekesztettség.',
        generalMeaning: 'A hála, az öröm és a gondtalanság kártyája. Van ok az ünneplésre.',
        loveMeaning: 'Boldog, felszabadult időszak. Nászutat vagy közös ünneplést jelent.',
        careerMeaning: 'Sikeres vizsgát vagy munkahelyi ünneplést jelez.',
        advice: 'Ünnepelj! Oszd meg az örömödet másokkal.',
        dailyMeaning: 'Ma okod lehet az örömre. Találkozz barátokkal.',
        yearlyMeaning: 'Az öröm és a hála éve. Boldog események várnak rád.',
        questions: ['Melyik személy jut eszedbe rokon szellemként?', 'Mennyi időt szánsz a barátaidra?'],
        affirmation: "Belekapcsolódom ebbe a szent testvériségbe.",
        imageUrl: 'https://myralog.hu/tarot/cups-3.jpg'
    },
    {
        id: 'cups-4', name: 'Kelyhek Négyes', nameEn: '4 of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 4,
        element: 'Víz', astrology: 'Hold a Rákban', numerology: '4',
        keywords: ['Apátia', 'Elmélkedés', 'Elszakadás', 'Befordulás', 'Unalom'],
        meaningUpright: 'Meditáció ideje, frusztráció, duzzogás, unalom, elszalasztott lehetőségek.',
        meaningReversed: 'Pesszimizmus elengedése, hála gyakorlása.',
        generalMeaning: 'A csömör és a rosszkedv kártyája. Nem vesszük észre az új esélyeket.',
        loveMeaning: 'Sértődöttség és érdektelenség. Csak a hibákat látjuk a partnerünkben.',
        careerMeaning: 'Motiválatlanság és kiégés. Elszalasztunk egy jó ajánlatot.',
        advice: 'Nyisd ki a szívedet! Ne duzzogj, hanem vedd észre a feléd nyújtott kezet.',
        dailyMeaning: 'Ma hajlamos lehetsz a rosszkedvre. Ne utasítsd el a kedvességet.',
        yearlyMeaning: 'A belső elégedetlenség éve. Ne maradj le a nagy lehetőségekről.',
        questions: ['Úy érzed, zöldebb a fű a másik oldalon?', 'Hogyan látná a helyzetedet egy optimista?'],
        affirmation: "Látom az életem teljességét és gazdagságát.",
        imageUrl: 'https://myralog.hu/tarot/cups-4.jpg'
    },
    {
        id: 'cups-5', name: 'Kelyhek Ötös', nameEn: '5 of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 5,
        element: 'Víz', astrology: 'Mars a Skorpióban', numerology: '5',
        keywords: ['Veszteség', 'Gyász', 'Csalódás', 'Sajnálat', 'Szomorúság'],
        meaningUpright: 'Gyász, csalódás, árulás, önsajnálat, megtört szív.',
        meaningReversed: 'Múltbeli traumák elengedése, gyógyulás keresése.',
        generalMeaning: 'A fájdalom és a veszteség kártyája. De nem veszett el minden.',
        loveMeaning: 'Szakítást vagy illúzió elvesztését jelzi. Meg kell élni a fájdalmat.',
        careerMeaning: 'Bukást vagy egy üzleti terv kudarcát jelzi. Veszteséges vállalkozás.',
        advice: 'Éld át a gyászt, de ne maradj benne! Vedd észre, ami megmaradt.',
        dailyMeaning: 'Ma csalódás érhet. Ne tagadd le a fájdalmat.',
        yearlyMeaning: 'A válság éve. Veszteségek érhetnek, de ez a megújulás útja.',
        questions: ['Mi történne, ha a szívedre hallgatnál?', 'Találsz időt a veszteségek feldolgozására?'],
        affirmation: "Gyengéd szívem segít nekem navigálni a jövőm felé.",
        imageUrl: 'https://myralog.hu/tarot/cups-5.jpg'
    },
    {
        id: 'cups-6', name: 'Kelyhek Hatos', nameEn: '6 of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 6,
        element: 'Víz', astrology: 'Nap a Skorpióban', numerology: '6',
        keywords: ['Nosztalgia', 'Emlékek', 'Gyermekkor', 'Ártatlanság', 'Újraegyesülés'],
        meaningUpright: 'Nosztalgia, múltbeli kapcsolatok, harmónia, belső gyermek.',
        meaningReversed: 'Bűntudat elengedése, megbocsátás magadnak.',
        generalMeaning: 'A múltba való visszatekintés és a nosztalgia kártyája.',
        loveMeaning: 'Régi szerelem felbukkanása vagy gyermeki, tiszta szerelem vágya.',
        careerMeaning: 'Visszatérés egy régi munkahelyre vagy egy álom megvalósítása.',
        advice: 'Meríts erőt a szép emlékekből! Ápold a kapcsolataidat.',
        dailyMeaning: 'Ma felbukkanhat valaki a múltadból.',
        yearlyMeaning: 'A visszatekintés éve. Feldolgozhatod a múltadat.',
        questions: ['Milyen emlékek merülnek fel benned?', 'Tudsz visszanézni, és látni, meddig jutottál?'],
        affirmation: "Megbékéltem a múltammal, ez hozott ide.",
        imageUrl: 'https://myralog.hu/tarot/cups-6.jpg'
    },
    {
        id: 'cups-7', name: 'Kelyhek Hetes', nameEn: '7 of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 7,
        element: 'Víz', astrology: 'Vénusz a Skorpióban', numerology: '7',
        keywords: ['Illúzió', 'Választás', 'Képzelet', 'Lehetőségek', 'Álmok'],
        meaningUpright: 'Választások, illúziók, kísértés, döntés igénye a teljes kép nélkül.',
        meaningReversed: 'Határozatlanság blokkja, túlterheltség a választásoktól.',
        generalMeaning: 'Az illúziók és az álmodozás kártyája. Veszélyes lehet a délibáb.',
        loveMeaning: 'Rózsaszín köd. Rajongás egy elérhetetlen ideálért.',
        careerMeaning: 'Irreális tervek, álmok kergetése tettek helyett.',
        advice: 'Ébredj fel! Válassz egyet a lehetőségek közül, és valósítsd meg.',
        dailyMeaning: 'Ma ne hozz fontos döntést. Élvezd a játékot.',
        yearlyMeaning: 'Az álmok éve. Vigyázz, nehogy becsapd magad.',
        questions: ['Mik az előnyök és hátrányok?', 'Tesz-e lépéseket annak érdekében amit akarsz?'],
        affirmation: "A képzeletem egy eszköz a jövőm megalkotásához.",
        imageUrl: 'https://myralog.hu/tarot/cups-7.jpg'
    },
    {
        id: 'cups-8', name: 'Kelyhek Nyolcas', nameEn: '8 of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 8,
        element: 'Víz', astrology: 'Szaturnusz a Halakban', numerology: '8',
        keywords: ['Elengedés', 'Keresés', 'Csalódás', 'Visszavonulás', 'Továbblépés'],
        meaningUpright: 'Elhagyni a régi valóságot, elengedés, csalódás, távozás.',
        meaningReversed: 'Visszanézés, megbánás, félelem a haladástól.',
        generalMeaning: 'A nehéz szívvel való távozás kártyája. Menekülés az igazság felé.',
        loveMeaning: 'Szakítást jelent, mert a kapcsolat már nem ad semmit.',
        careerMeaning: 'Felmondás, pályamódosítás. A belső hang hívását követed.',
        advice: 'Indulj el! Kövesd a belső iránytűdet.',
        dailyMeaning: 'Ma elhatározhatod, hogy lezársz valamit.',
        yearlyMeaning: 'Az útkeresés éve. Elhagysz valamit a magasabb célért.',
        questions: ['Mikor helyezed előrébb az igényeidet másokénál?', 'Ragaszkodsz olyasmihez, aminek lejárt az ideje?'],
        affirmation: "Elsétálok a negativitástól és magamat választom.",
        imageUrl: 'https://myralog.hu/tarot/cups-8.jpg'
    },
    {
        id: 'cups-9', name: 'Kelyhek Kilences', nameEn: '9 of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 9,
        element: 'Víz', astrology: 'Jupiter a Halakban', numerology: '9',
        keywords: ['Beteljesülés', 'Öröm', 'Elégedettség', 'Kívánság', 'Hála'],
        meaningUpright: 'Ajándékok az Univerzumtól, álmok megnyilvánulása, bőség.',
        meaningReversed: 'Késleltetett kielégülés, önelégültség.',
        generalMeaning: 'Az életöröm és az élvezetek kártyája. "Kívánság kártya".',
        loveMeaning: 'Érzéki élvezetek, gondtalan együttlét, harmónia.',
        careerMeaning: 'Siker és elismerés. Élvezzük a munkánk gyümölcsét.',
        advice: 'Élvezd az életet! Engedj meg magadnak egy kis luxust.',
        dailyMeaning: 'Ma kényeztesd magad. Örülj az életnek.',
        yearlyMeaning: 'Az élvezetek éve. Teljesülhetnek a titkos kívánságaid.',
        questions: ['Mit kérnél egy varázslámpától?', 'Milyen a kapcsolatod a hálával?'],
        affirmation: "Megnyitom hálás szívemet az ajándékok előtt.",
        imageUrl: 'https://myralog.hu/tarot/cups-9.jpg'
    },
    {
        id: 'cups-10', name: 'Kelyhek Tizes', nameEn: '10 of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 10,
        element: 'Víz', astrology: 'Mars a Halakban', numerology: '10',
        keywords: ['Boldogság', 'Család', 'Harmónia', 'Hazatérés', 'Beteljesülés'],
        meaningUpright: 'Közösség, szerelem, harmónia, család, isteni kapcsolat.',
        meaningReversed: 'Félreértés, diszharmónia, elhalasztott érkezés.',
        generalMeaning: 'A családi boldogság és a tartós érzelmi elégedettség kártyája.',
        loveMeaning: 'Hosszú távú boldogság, családalapítás, béke.',
        careerMeaning: 'Jó kollegiális viszony, biztonságos munkahely.',
        advice: 'Értékeld a közösséget! Teremts békét magad körül.',
        dailyMeaning: 'Ma tölts időt a szeretteiddel.',
        yearlyMeaning: 'A boldog révbe érés éve. Harmóniába kerülsz önmagaddal.',
        questions: ['Hogyan néz ki a happy ended?', 'Mit tehetsz a gördülékenyebb kapcsolatokért?'],
        affirmation: "Az egység állapotában élek, szeretetet viszek a kapcsolataimba.",
        imageUrl: 'https://myralog.hu/tarot/cups-10.jpg'
    },
    {
        id: 'cups-page', name: 'Kelyhek Apródja', nameEn: 'Page of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 11,
        element: 'Víz', astrology: 'Víz elem földi aspektusa', numerology: '11',
        keywords: ['Kreativitás', 'Hírek', 'Intuíció', 'Lehetőség', 'Szerendipitás'],
        meaningUpright: 'Álmodozó, szerendipitás, váratlan inspiráció, örömteli szív.',
        meaningReversed: 'Érzékenység, gyerekes érzelmek, írói blokk.',
        generalMeaning: 'Békülési gesztus vagy kedves impulzus. Új érzelmi esély.',
        loveMeaning: 'Szerelmi vallomás vagy egy romantikus gesztus.',
        careerMeaning: 'Dicséret, elismerés, barátságos ajánlat.',
        advice: 'Fogadd el a közeledést! Légy nyitott.',
        dailyMeaning: 'Ma kedves üzenetet vagy bókot kaphatsz.',
        yearlyMeaning: 'A békülés éve. Új barátságok szövődhetnek.',
        questions: ['Felismered a mágia felkavarását?', 'Milyen jel segítene hinni a csodákban?'],
        affirmation: "Izgatottan várom, mi nyílik ki legközelebb.",
        imageUrl: 'https://myralog.hu/tarot/cups-page.jpg'
    },
    {
        id: 'cups-knight', name: 'Kelyhek Lovagja', nameEn: 'Knight of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 12,
        element: 'Víz', astrology: 'Víz elem levegő aspektusa', numerology: '12',
        keywords: ['Romantika', 'Sárm', 'Képzelet', 'Szépség', 'Szenvedély'],
        meaningUpright: 'Klasszikus romantikus, művészi hajlam, váratlan meghívás.',
        meaningReversed: 'Féltékeny partner, duzzogás, elzárkózás.',
        generalMeaning: 'A jó hangulat és a romantika követe. Harmonikus időszak.',
        loveMeaning: 'Romantika, udvarlás, álmok. Érzékeny társ.',
        careerMeaning: 'Kellemes légkör, diplomácia, konfliktus elsimítása.',
        advice: 'Hallgass a szívedre! Légy megértő másokkal.',
        dailyMeaning: 'Ma álmodozó hangulatban lehetsz.',
        yearlyMeaning: 'A romantika és a művészetek éve.',
        questions: ['Készen állsz arra, hogy lesöpörjenek a lábaidról?', 'Bízol-e a szerelemben?'],
        affirmation: "Kapcsolatban vagyok az érzelmeimmel.",
        imageUrl: 'https://myralog.hu/tarot/cups-knight.jpg'
    },
    {
        id: 'cups-queen', name: 'Kelyhek Királynője', nameEn: 'Queen of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 13,
        element: 'Víz', astrology: 'Víz elem vizes aspektusa', numerology: '13',
        keywords: ['Együttérzés', 'Nyugalom', 'Kényelem', 'Intuíció', 'Empátia'],
        meaningUpright: 'Intuitív személy, érzelmi intelligencia, gyógyítás, szívvel vezetés.',
        meaningReversed: 'Érzelmi zsarolás, elfojtás, irracionalitás.',
        generalMeaning: 'Az empátia és a segítőkészség női oldala.',
        loveMeaning: 'Mély érzelmek, odaadás. Érzelmi biztonságot nyújtó társ.',
        careerMeaning: 'Segítő szakmák, művészetek, intuitív munka.',
        advice: 'Bízz a megérzéseidben! Légy együttérző.',
        dailyMeaning: 'Ma hallgass a belső hangodra.',
        yearlyMeaning: 'Az intuíció éve. Mély lelki fejlődés vár rád.',
        questions: ['Mennyire hangolt az érzelmi intelligenciád?', 'Mit mondana a szívcsakrád?'],
        affirmation: "Az intuitív szívem kifejezi szeretetemet.",
        imageUrl: 'https://myralog.hu/tarot/cups-queen.jpg'
    },
    {
        id: 'cups-king', name: 'Kelyhek Királya', nameEn: 'King of Cups', arcana: 'Minor', suit: 'Kelyhek', number: 14,
        element: 'Víz', astrology: 'Víz elem tüzes aspektusa', numerology: '14',
        keywords: ['Érzelmi egyensúly', 'Nagylelkűség', 'Diplomácia', 'Kontroll', 'Bölcsesség'],
        meaningUpright: 'Érzelmi egyensúly, tudattalan uralása, bölcs vezető.',
        meaningReversed: 'Érzelmi éretlenség, kontrollálási vágy.',
        generalMeaning: 'Az érzelmi mélység és a megértés férfi oldala.',
        loveMeaning: 'Érett érzelmek, gondoskodás, támasz.',
        careerMeaning: 'Empatikus vezető, terapeuta vagy művész.',
        advice: 'Kezeld az érzelmeidet tudatosan! Légy mások támasza.',
        dailyMeaning: 'Ma légy türelmes és megértő.',
        yearlyMeaning: 'Az érzelmi érettség éve. Megtanulod kezelni az érzelmeidet.',
        questions: ['Milyen üzeneteket kaptál a Szellemtől?', 'Képes vagy-e saját magad királya lenni?'],
        affirmation: "A szívem mély bölcsességet és szeretetet hordoz.",
        imageUrl: 'https://myralog.hu/tarot/cups-king.jpg'
    }
];
