
import { Card } from '../types';

export const MAJOR_ARCANA: Card[] = [
    {
        id: 'major-0', name: 'A Bolond', nameEn: 'The Fool', arcana: 'Major', number: 0,
        element: 'Levegő', astrology: 'Uránusz', numerology: '0',
        keywords: ['Új kezdet', 'Lelkesedés', 'Kaland', 'Lehetőség', 'Spontaneitás'],
        meaningUpright: 'Váratlan új kezdetek, spirituális ugrás az ismeretlenbe. A kártyán a szakadék szélén álló alak nem a veszélyt, hanem a hitet jelképezi. A fehér rózsa a kezében az ártatlanság és a tiszta szándék szimbóluma, míg a kis kutya az ösztönös éberséget és a védelmező természetet képviseli.',
        meaningReversed: 'Naivitás, feltételezve, hogy már megvan a válasz, kiütéses döntések, felelőtlenség, elszalasztott lehetőségek a félelem miatt.',
        generalMeaning: 'A Bolond a $0$-ás számú kártya, ami a tiszta potenciált jelzi, mielőtt bármilyen forma létrejönne. Ő a Tarot-utazás hőse, aki elfogulatlan nyitottsággal lép be egy új életterületre. Nem a tudatlanságot képviseli, hanem azt a bölcsességet, amely tudja, hogy mikor kell elengedni a múlt terheit (a kis batyu) és rábízni magunkat az Univerzum áramlására.',
        loveMeaning: 'Vidám, bonyodalmaktól mentes, életigenlő kapcsolatot jelez. Utalhat egy új szerelem kezdetére, vagy egy meglévő kapcsolat újjáéledésére a játékosság és a spontaneitás által. De óva int a felelőtlenségtől is.',
        careerMeaning: 'Új területre lépünk, ahol még nincs tapasztalatunk, de tele vagyunk kíváncsisággal. A "kezdő szellemét" jelképezi: nyitottságot a tanulásra és a hibázás lehetőségének elfogadását.',
        advice: 'Légy nyitott és előítéletektől mentes! Merj kockáztatni és hallgass a szívedre, még ha az ész mást is diktál. Ugorj fejest az életbe!',
        dailyMeaning: 'Légy ma spontán! Engedd el a görcsös irányítást és hagyd, hogy az élet meglepjen. Ma bármi lehetséges.',
        yearlyMeaning: 'Ez az év az új kezdetek éve. Olyan lehetőségek nyílnak meg előtted, amelyekre nem számítottál. Merj belevágni az ismeretlenbe, ez az átalakulásod alapköve!',
        history: 'A Bolond a Tarot legősibb figurája. Eredetileg a "Mat" (őrült) nevet viselte, és sokáig nem volt száma, vagy a pakli végén állt. Ő az egyetlen kártya, amely a modern játékkártyákba is átkerült mint a Joker. Történelmileg az udvari bolondot idézi, aki az egyetlen volt, aki az igazat mondhatta a királynak anélkül, hogy fejét vennék.',
        symbolism: 'A szakadék széle a szakrális kockázatvállalás. A fehér rózsa a spirituális tisztaság. A nap az életerő és az isteni tudatosság. A batyu a múlt tapasztalatait tartalmazza, melyeket a Bolond még nem analizált, de ösztönösen hordoz.',
        questions: ['Ha tudnád, hogy az Univerzum repülés közben elkap, hova ugranál?'],
        affirmation: "Felébresztem a lelkem ösvényét, és készen állok a kalandra.",
        imageUrl: 'https://myralog.hu/tarot/major-0.jpg'
    },
    {
        id: 'major-1', name: 'A Mágus', nameEn: 'The Magician', arcana: 'Major', number: 1,
        element: 'Levegő', astrology: 'Merkúr', numerology: '1',
        keywords: ['Készségek', 'Erő', 'Manifesztáció', 'Fókusz', 'Teremtés'],
        meaningUpright: 'Az akarat ereje és a tudatos teremtés. A Mágus a csatorna az ég és a föld között: egyik keze az ég felé (inspiráció), a másik a föld felé mutat (megvalósítás). Ez az "Amint fent, úgy lent" alkímiai alapelve. Minden eszköze megvan ahhoz, hogy a gondolatot fizikai valósággá formálja.',
        meaningReversed: 'Kihasználatlan potenciál, lappangó tehetségek, manipuláció, az erő öncélú használata vagy a fókusz elvesztése.',
        generalMeaning: 'A Mágus az aktív cselekvést és a tudatosságot képviseli. Ő az, aki felismeri, hogy az Univerzum energiái formálhatóak az emberi akarat által. Míg a Bolond a tiszta lehetőség, a Mágus a konkrét megvalósítás. Azt mutatja, hogy rendelkezünk a szükséges eszközökkel és képességekkel a sikerhez.',
        loveMeaning: 'Erős vonzerőt és kezdeményezőkészséget jelez. Azt mutatja, hogy képesek vagyunk megtenni az első lépést, vagy új lendületet adni a kapcsolatnak. A varázslat és a csábítás mestere.',
        careerMeaning: 'Sikeres vizsgákat, tárgyalásokat vagy projekteket jelez. Képesek vagyunk meggyőzni másokat és hatékonyan használni a tudásunkat. Kezdeményezőkészséget vár el.',
        advice: 'Vedd kezedbe az irányítást! Használd a tehetségedet és az eszedet a helyzet megoldására. Koncentráld az energiáidat egyetlen célra.',
        dailyMeaning: 'Ma minden sikerülhet, ha aktívan teszel érte. Használd ki a benned rejlő teremtő erőt! Ma te vagy a sorsod kovácsa.',
        yearlyMeaning: 'Ebben az évben a kezedbe veheted a sorsodat. Aktív, teremtő év vár rád, ahol a tudásod és akaratod révén nagy sikereket érhetsz el a fizikai világban is.',
        history: 'A Mágus eredetileg egy vásári mutatványost (Le Bateleur) ábrázolt, aki ügyességével és szavaival kápráztatta el a tömeget. Később, az okkult tarot-hagyományban Hermész Triszmegisztosz alakjával, a bölcsesség és a mágia istenével azonosították.',
        symbolism: 'A négy elem (kehely, érme, kard, bot) az asztalon a világ feletti uralmat jelzi. A végtelen jel (lemniszkáta) a feje felett a szellem határtalanságát mutatja. A fehér köpeny a tisztaságot, a vörös palást a világban való cselekvést jelképezi.',
        questions: ['Milyen eszközök állnak rendelkezésére, amelyeket nem használ ki maradéktalanul?'],
        affirmation: "Kinyilvánítom az általam kívánt életet az energia és a szándék révén.",
        imageUrl: 'https://myralog.hu/tarot/major-1.jpg'
    },
    {
        id: 'major-2', name: 'A Főpapnő', nameEn: 'The High Priestess', arcana: 'Major', number: 2,
        element: 'Víz', astrology: 'Hold', numerology: '2',
        keywords: ['Intuíció', 'Álmok', 'Csend', 'Titkok', 'Misztikum'],
        meaningUpright: 'Belső bölcsesség és a tudatalatti kapuőre. A Főpapnő a rejtett tudás őrzője, aki a látható és láthatatlan világ határán ül. Nem a logikára, hanem a megérzésekre, az álmokra és a szinkronicitásokra alapozza döntéseit. A csend erejét képviseli.',
        meaningReversed: 'Titkok, pletykák, a belső hang figyelmen kívül hagyása, felületesség, rejtett ellenségek vagy elfojtott érzelmek.',
        generalMeaning: 'A Főpapnő a tudattalan erőinket és a befogadást képviseli. Azt üzeni, hogy a válaszok nem a külvilágban, hanem belül, a lelkünk mélyén találhatók. Ő a meditáció és a passzivitás kártyája: néha a nem-cselekvés a leghatékonyabb út a megértéshez.',
        loveMeaning: 'Mély lelki összetartozást, empátiát és megértést jelez. Utalhat egy titokzatos vonzalomra vagy plátói szerelemre is. Azt tanácsolja, hogy hallgassunk a megérzéseinkre a társunkkal kapcsolatban.',
        careerMeaning: 'Olyan feladatokat jelez, ahol pszichológiai érzékre, empátiára vagy intuitív döntésekre van szükség. Művészi vagy segítő foglalkozásokban sikert ígér.',
        advice: 'Ne cselekedj elhamarkodottan! Várj, figyelj befelé, és hagyd, hogy a dolgok maguktól kiforrjanak. Hallgass az intuíciódra és az álmaidra.',
        dailyMeaning: 'Ma hagyatkozz az ösztöneidre. Figyelj a véletlenekre, a megérzéseidre és az álmaid üzenetére. Ma a csendben rejlik a válasz.',
        yearlyMeaning: 'Ez az év a belső utazás éve. Fontos spirituális felismerésekre juthatsz önmagaddal kapcsolatban, ha mersz a felszín alá nézni és elcsendesedni.',
        history: 'Gyakran Johanna papnő legendájához kötik. A középkori kártyákon La Papesse (A Papnő) néven szerepelt. Ő a Tarot titkos tudásának letéteményese, Izisz istennő vagy Perszephoné archetípusa.',
        symbolism: 'A két oszlop (B mint Boáz - sötétség, J mint Jákin - világosság) a dualitást jelzi. A gránátalmás függöny a női termékenységet és a tudat alatt megbúvó rejtett világot, a Tóra tekercs pedig a szent törvényt és a rejtett tudást szimbolizálja.',
        questions: ['Hogyan lépsz kapcsolatba intuitív szíveddel?'],
        affirmation: "A hit az intuitív szívemben van.",
        imageUrl: 'https://myralog.hu/tarot/major-2.jpg'
    },
    {
        id: 'major-3', name: 'Az Uralkodónő', nameEn: 'The Empress', arcana: 'Major', number: 3,
        element: 'Föld', astrology: 'Vénusz', numerology: '3',
        keywords: ['Termékenység', 'Bőség', 'Gondoskodás', 'Kreativitás', 'Anyaság'],
        meaningUpright: 'A természet életereje és a fizikai világ bősége. Az Uralkodónő a növekedést, a táplálást és az anyagi biztonságot szimbolizálja. Ő az Ősanya, aki életet ad minden kreatív ötletnek és projektnek. Jelenléte kényelmet, luxust és érzelmi gazdagságot ígér.',
        meaningReversed: 'Kreatív blokkok, függőség, elhanyagolás, terméketlenség (átvitt értelemben is), érzelmi zsarolás vagy fojtogató szeretet.',
        generalMeaning: 'Az Uralkodónő a természet kifogyhatatlan erejét és az életörömöt jelképezi. Bármi, amibe most belekezdünk, gyümölcsöző lesz. Ő a teremtés és a születés kártyája: nemcsak gyermekek, hanem művek, vállalkozások és új életszakaszok világra jöttét is jelzi.',
        loveMeaning: 'Érzéki élvezeteket, szenvedélyt és védettséget jelent. Családalapításra, terhességre vagy a kapcsolat elmélyülésére utalhat. Az anyai gondoskodás és az érett szeretet kártyája.',
        careerMeaning: 'Kreativitást, új ötletek születését és növekedést jelez. Jó időszak művészeti projektekhez vagy vállalkozás indításához. A bőség most elérhető közelségben van.',
        advice: 'Légy kreatív és élvezd az életet! Tápláld azt, ami növekedni akar. Bízz a megérzéseidben és a természet erejében. Gondoskodj magadról is.',
        dailyMeaning: 'Menj ki a természetbe, alkoss valamit, vagy kényeztesd magad és a szeretteidet. Ma a bőség és az élet szépsége vesz körül.',
        yearlyMeaning: 'Termékeny év vár rád. Amit most elvetsz, az bőségesen fog teremni. Ez az év a kreativitásod és az érzelmi stabilitásod kivirágzásának ideje.',
        history: 'A Nagy Anya archetípusa, Démétér, Ízisz vagy Vénusz megfelelője. Ő a földi mennyország úrnője, aki a káoszból harmóniát és életet teremt.',
        symbolism: 'A gránátalma a termékenységet, a búzatábla az aratást és a bőséget, a Vénusz-pajzs a szeretetet jelképezi. A 12 csillagos korona a zodiákus jegyeit és az idő feletti uralmat szimbolizálja.',
        questions: ['Készen állok megszülni __________.'],
        affirmation: "Megszülöm bőségesen gazdag jövőmet.",
        imageUrl: 'https://myralog.hu/tarot/major-3.jpg'
    },
    {
        id: 'major-4', name: 'Az Uralkodó', nameEn: 'The Emperor', arcana: 'Major', number: 4,
        element: 'Tűz', astrology: 'Kos', numerology: '4',
        keywords: ['Vezetés', 'Struktúra', 'Hatalom', 'Rend', 'Stratégia'],
        meaningUpright: 'A rend, a fegyelem és az atyai tekintély megtestesítője. Az Uralkodó a stabilitást és a biztonságot képviseli a fizikai világban. Képes a káoszból rendszert alkotni, határozott döntéseket hozni és felelősséget vállalni egy egész közösségért. Ő a stratégia és a logikus érvelés mestere.',
        meaningReversed: 'Zsarnokság, merevség, kontrollmánia, gyengeség elfedése agresszióval, a struktúra hiánya vagy az autoritás elvesztése.',
        generalMeaning: 'Az Uralkodó a társadalom és a civilizáció rendjének őre. Azt mutatja, hogy képesek vagyunk uralni a körülményeinket, ha fegyelmezettek és módszeresek vagyunk. Ő a realitások talaján állást és a hosszú távú építkezést szimbolizálja.',
        loveMeaning: 'Stabilitást és biztonságot jelent a kapcsolatban. Jelezheti, hogy a kapcsolat hivatalossá válik. Ugyanakkor figyelmeztethet a túlzott dominanciára vagy az érzelmek elfojtására a logika javára.',
        careerMeaning: 'Sikert, vezetői pozíciót, vagy egy projekt strukturált megvalósítását jelzi. Fegyelemre és következetességre van szükség. A szabályok és a rend most a szövetségeseid.',
        advice: 'Teremts rendet! Húzd meg a határaidat és légy következetes. Cselekedj megfontoltan, felelősségteljesen és állj ki a véleményed mellett.',
        dailyMeaning: 'Ma légy határozott és rendezd a soraidat. Végezz el egy fegyelmet igénylő feladatot. Ma az ész vezéreljen az érzelmek felett.',
        yearlyMeaning: 'Az építkezés és a stabilizáció éve. Most alapozhatod meg a jövődet. Fontos a kitartás, a stratégiai tervezés és a realitásérzék fejlesztése.',
        history: 'Az Apafigura, a Pátriárka és a törvényalkotó uralkodó. Történelmileg olyan alakokkal azonosítják, mint Nagy Károly vagy a bibliai Ábrahám. Ő a világi hatalom csúcsa.',
        symbolism: 'A kocka alakú trón a szilárdságot, a kos fejek az erőt és a Kos asztrológiai jegyét, az ankh-kereszt az élet feletti uralmat, a páncél pedig a folyamatos készenlétet jelképezi.',
        questions: ['Mit építesz, és hogyan fog kinézni, ha elkészültél?'],
        affirmation: "Magabiztossággal és tekintéllyel vezetem az életemet.",
        imageUrl: 'https://myralog.hu/tarot/major-4.jpg'
    },
    {
        id: 'major-5', name: 'A Főpap', nameEn: 'The Hierophant', arcana: 'Major', number: 5,
        element: 'Föld', astrology: 'Bika', numerology: '5',
        keywords: ['Hagyomány', 'Hit', 'Tanítás', 'Spirituális vezető', 'Bölcsesség'],
        meaningUpright: 'A közösségi bölcsesség és a strukturált tanulás kártyája. A Főpap a hidat képezi az isteni és a földi között, segítve az egyént, hogy megtalálja a helyét egy nagyobb rendszerben (vallás, iskola, társadalom). A bizalom, a hit és az erkölcsi integritás megtestesítője.',
        meaningReversed: 'Dogmatizmus, merevség, lázadás a normák ellen, képmutatás, tévutak vagy rossz tanácsok követése.',
        generalMeaning: 'A Főpap a mélyebb értelem keresését és a hagyományok tiszteletét képviseli. Azt jelzi, hogy bizonyos válaszokat csak a múlt bölcsességén és a bevált rendszereken keresztül érhetünk el. Utalhat mentorálásra, oktatásra vagy beavatási rítusokra is.',
        loveMeaning: 'A bizalom és az egymás iránti elköteleződés növekedését jelzi. Gyakran utal házasságkötésre vagy a kapcsolat hivatalossá tételére. A közös értékrend és az etika fontosságát hangsúlyozza.',
        careerMeaning: 'Megtaláljuk hivatásunk értelmét. Utalhat tanári pályára, vagy arra, hogy hűek maradunk elveinkhez az üzleti életben is. Fontos a szakértelem és a folyamatos tanulás.',
        advice: 'Keresd a dolgok mélyebb értelmét! Tarts ki az elveid mellett, és cselekedj a lelkiismereted szerint. Hallgass egy bölcsebb mentor tanácsára.',
        dailyMeaning: 'Ma találkozhatsz valakivel, aki fontos tanácsot ad, vagy te lehetsz mások spirituális támasza. Kérdezd meg magadtól: mi a helyes és mi az igaz?',
        yearlyMeaning: 'Ez az év a bizalom és az értelemkeresés jegyében telik. Megtalálhatod a helyedet a világban és egy közösség értékes tagjává válhatsz.',
        history: 'A beavatás mestere (Hierofáns), aki a görög misztériumvallásokban a szent titkokat magyarázta. A keresztény tarotban a Pápa (Il Papa) néven szerepel.',
        symbolism: 'A háromszoros pápai kereszt és tiara a szellemi, érzelmi és fizikai hatalmat, a lábai előtt lévő két kulcs a mennyek országának (tudásnak) a nyitóeszközeit jelzi.',
        questions: ['Milyen hiedelem áll az álmaid útjában?'],
        affirmation: "Én vagyok a saját gurum, de tisztelem a hagyomány bölcsességét.",
        imageUrl: 'https://myralog.hu/tarot/major-5.jpg'
    },
    {
        id: 'major-6', name: 'A Szeretők', nameEn: 'The Lovers', arcana: 'Major', number: 6,
        element: 'Levegő', astrology: 'Ikrek', numerology: '6',
        keywords: ['Szerelem', 'Választás', 'Harmónia', 'Kapcsolat', 'Egység'],
        meaningUpright: 'Mély érzelmi kapcsolódás és erkölcsi választás. A kártya nemcsak a romantikáról szól, hanem arról a válaszútról, ahol a szívünk és a lelkiismeretünk alapján kell döntetnünk. Az ellentétek (férfi és nő, ész és szív) harmonikus egységét és az elköteleződést jelképezi.',
        meaningReversed: 'Döntésképtelenség, diszharmónia, elválás, hűtlenség, belső konfliktus, elhamarkodott választás következményei.',
        generalMeaning: 'A Szeretők kártyája a nagy szerelmet és a szükségszerű választást öleli fel. Azt jelzi, hogy elérkeztünk egy olyan ponthoz, ahol teljes szívvel el kell köteleződnünk valami mellett. Ez az integráció kártyája: képessé válunk az egységre önmagunkkal és másokkal.',
        loveMeaning: 'A nagy szerelem kártyája. Mély érzelmi kapcsolatot, boldogságot és a "másik felünk" megtalálását jelzi. Döntést is jelenthet a partner mellett (pl. összeköltözés, esküvő).',
        careerMeaning: 'Szenvedéllyel végzett munkát jelent, vagy olyan feladatot, ami mellett teljes szívvel elköteleződünk. Utalhat sikeres üzleti partnerségekre és etikus döntéshozatalra.',
        advice: 'Dönts szívből! Ne csak az eszedre hallgass, hanem arra is, ami lelkesít. Keress harmóniát és egyesítsd az erőidet másokkal.',
        dailyMeaning: 'Ma döntéshelyzetbe kerülhetsz. Válaszd azt, amihez a szíved húz, és ami hosszú távon békét hoz a lelkednek.',
        yearlyMeaning: 'A szív döntéseinek éve. Lehet, hogy megtalálod a párod, vagy elköteleződsz egy olyan hivatás vagy ügy mellett, ami meghatározza a jövődet.',
        history: 'Eredetileg a "Válaszút" kártyája volt, ahol egy ifjúnak két nő (az erény és a bűn) között kellett választania. A Rider-Waite pakliban vált a paradicsomi egység és a szerelem szimbólumává.',
        symbolism: 'Rafael arkangyal az áldást és gyógyulást, a Tudás Fája a kígyóval a kísértést és tapasztalást, az Élet Fája a tiszta potenciált, a nap az isteni fényt jelképezi.',
        questions: ['Képes vagy ebben az időben teljesen beleállni egy partnerségbe?'],
        affirmation: "A szívem nyitott a mélyen értelmes kapcsolatra.",
        imageUrl: 'https://myralog.hu/tarot/major-6.jpg'
    },
    {
        id: 'major-7', name: 'A Diadalszekér', nameEn: 'The Chariot', arcana: 'Major', number: 7,
        element: 'Víz', astrology: 'Rák', numerology: '7',
        keywords: ['Győzelem', 'Akaraterő', 'Irányítás', 'Haladás', 'Elszántság'],
        meaningUpright: 'A fókuszált akaraterő diadala az ellentétes erők felett. A harcos nem gyeplővel, hanem puszta mentális fegyelemmel irányítja a szekerét. Ez a kártya a sikert, az akadályok legyőzését és a magabiztos előrehaladást ígéri, ha hűek maradunk a célunkhoz.',
        meaningReversed: 'Irányítás elvesztése, agresszió, kudarc az elszántság hiánya miatt, rossz irányba haladás vagy az ego romboló dominanciája.',
        generalMeaning: 'A Diadalszekér a lendületet és az új utakra lépést jelképezi. Azt mutatja, hogy bátran vállaljuk a kockázatot, és képesek vagyunk összeegyeztetni a belsőnkben feszülő ellentéteket a győzelem érdekében. Ez a "hős útja" szakasz, ahol a külvilágban aratunk sikert.',
        loveMeaning: 'Új kapcsolat kezdetét vagy a meglévő kapcsolatban egy "friss szél" érkezését jelzi. Jelezheti, hogy két különböző hátterű ember képes közös irányba haladni.',
        careerMeaning: 'Nagy előrelépést, önállósodást vagy előléptetést jelent. Sikert ígér, ha határozott vagy és nem hagyod, hogy a nehézségek eltántorítsanak.',
        advice: 'Indulj el! Ne habozz, vedd kezedbe a gyeplőt és határozottan haladj a célod felé. A siker kulcsa az önfegyelem és a kitartás.',
        dailyMeaning: 'Ma lendületben vagy. Használd ki ezt az energiát a feladataid gyors elintézésére. Ma semmi sem állíthat meg.',
        yearlyMeaning: 'Az áttörés éve. Ha eddig egy helyben toporogtál, most végre felgyorsulnak az események. Ez az év a látványos sikerek és a győzelem ideje lesz.',
        history: 'A diadalmenetben vonuló hadvezér képe, aki úrrá lett az ellenségein. Spirituálisan az emberi lélek szekere, melyet az értelem hajt a káoszon keresztül.',
        symbolism: 'A fekete és fehér szfinxek az érzelmeket és ösztönöket, a csillagos mennyezet az isteni védelmet, a vállán lévő holdak (Urim és Thummim) az isteni ítéletet jelzik.',
        questions: ['Merre tartasz? Ön átvette a kormányt?'],
        affirmation: "Én választom ki, hogy kivé válok, és meggyőződéssel futok felé.",
        imageUrl: 'https://myralog.hu/tarot/major-7.jpg'
    },
    {
        id: 'major-8', name: 'Az Erő', nameEn: 'Strength', arcana: 'Major', number: 8,
        element: 'Tűz', astrology: 'Oroszlán', numerology: '8',
        keywords: ['Bátorság', 'Együttérzés', 'Belső erő', 'Türelem', 'Szelídség'],
        meaningUpright: 'A nyers ösztönök szelídítése szeretettel és belső tartással. A nőalak nem erőszakkal, hanem gyengéd határozottsággal hajtja uralma alá az oroszlánt. Ez a kártya azt tanítja, hogy a valódi hatalom nem az agresszióban, hanem az önuralomban és a szellem erejében rejlik.',
        meaningReversed: 'Gyengeség, önbizalomhiány, nyers ösztönök romboló uralma, félelem a saját erőnktől vagy türelmetlenség.',
        generalMeaning: 'Az Erő nem a fizikai izomzatot, hanem a belső integritást és a szenvedélyes életkedvet jelenti. Azt üzeni, hogy nem elfojtani kell az "állati" énünket, hanem integrálni és magasabb célok szolgálatába állítani. Ez a kitartó, csendes bátorság kártyája.',
        loveMeaning: 'Szenvedélyes, tüzes kapcsolatot jelez. Azt mutatja, hogy az ösztönök és a szeretet egyensúlyban vannak. Bátorságot ad ahhoz, hogy vállaljuk legmélyebb érzéseinket is.',
        careerMeaning: 'Teljes bevetést, munkakedvet és kreatív energiákat jelent. Képes vagy a nehéz konfliktusokat is diplomáciával és belső erővel megoldani.',
        advice: 'Légy bátor és szenvedélyes! Ne rejtsd el az erődet, de használd bölcsen, türelemmel és gyengéden. A szeretet mindent legyőz.',
        dailyMeaning: 'Ma tele vagy energiával. Nézz szembe azzal, amitől eddig tartottál. Megvan benned az erő a győzelemhez.',
        yearlyMeaning: 'Szenvedélyes és energikus év. Olyan belső akadályokat győzöl le ebben az évben, amelyekről korábban azt hitted, lehetetlen.',
        history: 'Hagyományosan "Fortitudo" (Lelki erő) néven a négy sarkalatos erény egyike. A Tarot de Marseille-ben a 11-es számot viselte, a Rider-Waite-ban került a 8-as helyre.',
        symbolism: 'Az oroszlán a nyers ösztönt, a nő a magasabb tudatosságot, a végtelen jel (lemniszkáta) a spirituális energiát, a virágfüzér a természet és az ember kapcsolatát jelképezi.',
        questions: ['Hogyan találhatsz bátorságot a gyengédségben?'],
        affirmation: "Szándékosan ragyogtatom együttérzésem és erőm.",
        imageUrl: 'https://myralog.hu/tarot/major-8.jpg'
    },
    {
        id: 'major-9', name: 'A Remete', nameEn: 'The Hermit', arcana: 'Major', number: 9,
        element: 'Föld', astrology: 'Szűz', numerology: '9',
        keywords: ['Önvizsgálat', 'Magány', 'Bölcsesség', 'Útmutatás', 'Reflexió'],
        meaningUpright: 'Belső igazság keresése a csendben és az elvonulásban. A Remete a belső fényt követi, nem a külvilág elvárásait. Ez az önismereti út, a meditáció és a megfontoltság ideje. A lámpása nemcsak az ő útját világítja meg, hanem példát mutat másoknak is a sötétségben.',
        meaningReversed: 'Elszigetelődés, magányosság, elutasítás, a tanácsok figyelmen kívül hagyása, gőg vagy félelem az egyedülléttől.',
        generalMeaning: 'A Remete a tudatos befelé fordulás kártyája. Azt jelzi, hogy vissza kell vonulnunk a zajból, hogy meghalljuk a lelkünk hangját. Nem a szomorú magányt, hanem az alkotó egyedüllétet és a szerzett bölcsességet képviseli.',
        loveMeaning: 'Érettebb szakaszba lépést jelez, ahol a felek tisztelik egymás privát szféráját. Jelezheti az önkéntes egyedüllét időszakát is, ami a valódi elköteleződés feltétele.',
        careerMeaning: 'Itt az ideje átgondolni a céljaidat. Komolyságot, szakmai elmélyülést és alaposságot jelez. Egyedül végzett kutatás vagy alkotás hozhat sikert.',
        advice: 'Vonulj vissza és tisztázd magadban a céljaidat! Ne kapkodj, légy türelmes önmagadhoz. A valódi válaszok a csendben születnek meg.',
        dailyMeaning: 'Ma tölts egy kis időt csendben. Kerüld a felesleges fecsegést és figyelj befelé. Ma önmagad legjobb tanácsadója lehetsz.',
        yearlyMeaning: 'A komolyság és a belső érés éve. Ebben az évben megtalálod a saját belső igazságodat, ami iránytűként szolgál majd az életed hátralévő részében.',
        history: 'Idővel (Chronos) is azonosították. Diogenészre, a hordóban lakó bölcsre emlékeztet, aki lámpással kereste az "embert" és az igazságot.',
        symbolism: 'A lámpásban lévő hatágú csillag a tudatosságot, a bot a tapasztalatot és támaszt, a kietlen hegycsúcs a spirituális elszigeteltséget és magaslatot jelképezi.',
        questions: ['Mit szólna a belső bölcsed, ha megkérdeznéd tőle, mit kell tenned?'],
        affirmation: "Békében vagyok a csenddel, és figyelek a belső hangomra.",
        imageUrl: 'https://myralog.hu/tarot/major-9.jpg'
    },
    {
        id: 'major-10', name: 'Szerencsekerék', nameEn: 'Wheel of Fortune', arcana: 'Major', number: 10,
        element: 'Tűz', astrology: 'Jupiter', numerology: '10',
        keywords: ['Sors', 'Változás', 'Ciklusok', 'Karma', 'Szerencse'],
        meaningUpright: 'Sorsszerű fordulatok és az élet állandó mozgása. A kerék forog, emlékeztetve minket, hogy "egyszer fent, egyszer lent". Ez a kártya váratlan szerencsét, új lehetőségeket és a sors kerekének kedvező állását jelzi. Azt tanítja, hogy a változás az egyetlen állandó.',
        meaningReversed: 'Balszerencse, ellenállás a változásnak, negatív karmikus ciklusok ismétlődése, külső körülmények áldozatává válás érzése.',
        generalMeaning: 'A Szerencsekerék arra emlékeztet, hogy az élet ciklikus. Azt üzeni, hogy fogadjuk el a sorsunkat, és értsük meg, hogy a változás közepette is létezik egy kozmikus rend. Gyakran jelöl sorsfordító találkozásokat vagy eseményeket.',
        loveMeaning: 'Sorsszerű találkozást vagy a kapcsolatban beálló hirtelen, pozitív változást jelez. A dolgok maguktól megoldódhatnak, ha bízol a folyamatban.',
        careerMeaning: 'Váratlan fordulat a karrierben, ami általában felemelkedést ígér. A szerencse most melléd áll, ragadd meg a kínálkozó alkalmat!',
        advice: 'Fogadd el a változást! Ismerd fel a sorsszerűséget a helyzetben, és légy rugalmas. Most te vagy a kerék tetején, használd ki a lehetőséget!',
        dailyMeaning: 'Ma váratlan dolgok történhetnek. Légy nyitott és használd ki a felbukkanó esélyeket. Ma a sors a kezedre játszik.',
        yearlyMeaning: 'A sorsfordító változások éve. Az életed új, dinamikus irányt vesz. Ez az év a szerencse és a karma egyensúlyba kerülésének ideje.',
        history: 'A középkori "Rota Fortunae" koncepciója: a sors istennője forgatja a kereket, felemelve a koldust és letaszítva a királyt. A tarotban ez a kozmikus törvényszerűséget jelzi.',
        symbolism: 'A négy sarokban lévő szárnyas lények (Tetramorph) az állandóságot, a keréken a T-A-R-O betűk a törvényt, a Szfinx az egyensúlyt, Anubisz a felemelkedést jelképezi.',
        questions: ['Hiszel abban, hogy a sorsod elkerülhetetlen, vagy te alakítod azt?'],
        affirmation: "Elfogadom az élet körforgását és bízom a sorsomban.",
        imageUrl: 'https://myralog.hu/tarot/major-10.jpg'
    },
 {
        id: 'major-11', name: 'Az Igazságosság', nameEn: 'Justice', arcana: 'Major', number: 11,
        element: 'Levegő', astrology: 'Mérleg', numerology: '11',
        keywords: ['Igazság', 'Egyensúly', 'Karma', 'Felelősség', 'Integritás'],
        meaningUpright: 'A tettek és következmények kíméletlen, de igazságos egyensúlya. Ez a kártya az objektivitást és a tényeken alapuló tisztánlátást jelképezi. Azt üzeni, hogy az igazság végül fényre kerül, és mindenki azt aratja le, amit elvetett. Jogi ügyekben kedvező kimenetelt jósol, ha az igazság a mi oldalunkon áll.',
        meaningReversed: 'Igazságtalanság, részrehajlás, felelősséghárítás, önbecsapás, jogi bonyodalmak vagy tisztességtelen ítélet.',
        generalMeaning: 'Az Igazságosság a kozmikus egyensúlyt és a karmikus törvényt képviseli. Nem érzelmi alapon dönt, hanem a tények mérlegelésével. Arra emlékeztet, hogy minden választásunk lenyomatot hagy a világban. A belső integritás kártyája: aszerint élsz-e, amit igaznak vallasz? Itt nincs helye maszkoknak, csak a tiszta valóságnak.',
        loveMeaning: 'Az egyenjogúság és a fair play fontosságát hangsúlyozza. Fontos a tisztázó beszélgetés és az abszolút őszinteség. Hivatalos ügyek (pl. házasságkötés vagy szerződéses elköteleződés) intézését is jelentheti.',
        careerMeaning: 'Világos helyzetértékelést és reális célokat követel. Szerződéskötésre, fontos döntésekre és szakmai elismerésre utal, ha a munkád minőségi és etikus volt. Mindenki megkapja a méltó jutalmát.',
        advice: 'Légy objektív és fair! Mérlegeld a pro és kontra érveket, mielőtt döntesz. Vállald a teljes felelősséget a tetteidért, és maradj hű az elveidhez.',
        dailyMeaning: 'Ma légy megfontolt és igazságos. Egy kényes ügyben döntést kell hoznod vagy szembesülnöd kell egy korábbi tetted következményével. Keress egyensúlyt!',
        yearlyMeaning: 'A felelősségvállalás és a tisztázás éve. Ebben az évben a sorsod kiegyenlítődik: a befektetett energia és a tisztességes szándék meghozza a gyümölcsét.',
        history: 'A négy sarkalatos erény egyike. A tarot történetében sokáig a 8-as helyen állt, a Rider-Waite rendszerben cserélt helyet az Erővel, hogy jobban illeszkedjen az asztrológiai analógiákhoz.',
        symbolism: 'A mérleg a mérlegelést és a dualitást, a kard az ítéletet és a határozott döntést jelképezi. A lila függöny a háttérben a szellemi tekintélyt és a titkos igazságokat szimbolizálja.',
        questions: ['Hol vagy kiegyensúlyozatlan az életedben?', 'Képes vagy-e elfogadni tetteid következményeit?'],
        affirmation: "Vállalom a felelősséget tetteimért és az igazságot keresem.",
        imageUrl: 'https://myralog.hu/tarot/major-11.jpg'
    },
    {
        id: 'major-12', name: 'Az Akasztott Ember', nameEn: 'The Hanged Man', arcana: 'Major', number: 12,
        element: 'Víz', astrology: 'Neptunusz', numerology: '12',
        keywords: ['Átadás', 'Új perspektíva', 'Várakozás', 'Elengedés', 'Megvilágosodás'],
        meaningUpright: 'Tudatos megállás és a világ más szemmel való szemlélése. Az Akasztott Ember nem büntetés alatt áll, hanem önként választotta ezt a helyzetet, hogy magasabb rendű bölcsességet szerezzen. Ez a türelem, az egó elengedésének és a spirituális megvilágosodásnak a kártyája.',
        meaningReversed: 'Stagnálás, mártíromság, hiábavaló áldozat, ellenállás a szükségszerű megállásnak, félelem a dolgok elengedésétől.',
        generalMeaning: 'Ez a kártya a kényszerű vagy választott várakozás ideje. Arra tanít, hogy néha a nem-cselekvés a legaktívabb tett. Amikor a világ fejjel lefelé fordul körülöttünk, új összefüggéseket látunk meg. Ez a "felfüggesztett állapot" lehetőséget ad arra, hogy megszabaduljunk a régi, korlátozó hitrendszereinktől.',
        loveMeaning: 'Elakadást vagy várakozási időt jelez. Most nem tudunk vagy nem kell előre lépnünk. Arra int, hogy nézzünk rá a kapcsolatunkra egy teljesen új szemszögből, mielőtt döntenénk.',
        careerMeaning: 'A dolgok nem haladnak, vagy késnek a projektek. A kényszerpihenő azonban hasznos lehet új stratégiák kidolgozására. Ne erőltesd azt, ami most nem megy; figyeld a jeleket.',
        advice: 'Változtass nézőpontot! Ha nem tudsz változtatni a helyzeten, változtasd meg a hozzáállásodat. Engedd el az irányítási vágyadat, és bízz az időben.',
        dailyMeaning: 'Ma valószínűleg semmi sem úgy alakul, ahogy tervezted. Ne bosszankodj, inkább használd ezt a "holt időt" elmélkedésre és a dolgok átértékelésére.',
        yearlyMeaning: 'A belső átalakulás és a türelem éve. Lehet, hogy kívülről úgy tűnik, megakadtál, de belül mély spirituális fejlődés zajlik, ami tavasszal hoz majd fordulatot.',
        history: 'Odin skandináv isten áldozatára utal, aki kilenc napig függött a világfán, hogy megszerezze a rúnák titkát. A keresztény misztikában a vértanúság és a magasabb rendű önátadás jelképe.',
        symbolism: 'A fejjel lefelé lógó alak a fordított világképet, a glória a feje körül a megvilágosodást, a keresztbe tett lábak pedig a fizikai világ feletti uralmat jelképezik.',
        questions: ['Mi az, amihez túl erősen ragaszkodsz?', 'Mit látnál meg, ha fejjel lefelé néznéd a problémádat?'],
        affirmation: "Elengedem az irányítást és bízom a folyamatban.",
        imageUrl: 'https://myralog.hu/tarot/major-12.jpg'
    },
    {
        id: 'major-13', name: 'A Halál', nameEn: 'Death', arcana: 'Major', number: 13,
        element: 'Víz', astrology: 'Skorpió', numerology: '13',
        keywords: ['Befejezés', 'Átalakulás', 'Elengedés', 'Új kezdet', 'Újjászületés'],
        meaningUpright: 'Egy fontos életszakasz lezárulása, hogy helyet adjon valami újnak. Ez a kártya a radikális átalakulást és a múlt elengedését szimbolizálja. Nem a fizikai halálról szól, hanem a régi maszkok és illúziók lehullásáról. A változás elkerülhetetlen, de szükséges a fejlődéshez.',
        meaningReversed: 'Ragaszkodás a múlthoz, félelem a változástól, elhúzódó vég, stagnálás egy halott helyzetben vagy az újjászületés elutasítása.',
        generalMeaning: 'A Halál a legmélyebb transzformáció kártyája. Arra tanít, hogy semmi sem maradandó, és az elengedés az élet természetes része. Ahhoz, hogy újjászülessünk (mint a főnix vagy a hernyóból a lepke), meg kell engednünk, hogy a régi énünk meghaljon. Ez a kártya a felszabadító lezárás ígérete.',
        loveMeaning: 'Egy életszakasz végét jelentheti. Vagy a kapcsolat végét, vagy egy régi dinamika (pl. féltékenység, függőség) lezárását, hogy egy mélyebb, őszintébb szintre léphessetek.',
        careerMeaning: 'Búcsút a régi munkahelytől vagy pozíciótól. Radikális váltást jelez, ami félelmetesnek tűnhet, de valójában megszabadít a korlátoktól és új hivatást hozhat.',
        advice: 'Engedd el! Ne próbáld életben tartani azt, ami már nem szolgál téged. Fogadd el a búcsút méltósággal, és bízz abban, hogy az üresség után új élet sarjad.',
        dailyMeaning: 'Ma valami végérvényesen lezárulhat. Ne félj tőle, ez a lépés szükséges ahhoz, hogy holnap tiszta lappal indulhass.',
        yearlyMeaning: 'A nagy újjászületés éve. Ebben az évben teljesen leveted a régi bőrödet. Fájdalmas lehet az elszakadás, de év végére egy új, igazabb önmagadra találsz.',
        history: 'A középkori "Mors" alakja, aki nem válogat szegény és gazdag között. A Tarotban ő az "Arcanum névtelen kártyája", jelezve, hogy a változásnak nincs emberi neve, csak ereje.',
        symbolism: 'A kaszás lovas a változás kíméletlenségét, a felkelő nap a horizonton a feltámadást és az örök reményt, a fehér ló pedig a szándék tisztaságát jelképezi.',
        questions: ['Mi az, aminek meg kell halnia az életedben, hogy te valóban élhess?', 'Készen állsz az újjászületésre?'],
        affirmation: "Elengedem a régit, és bizalommal nyitok az új felé.",
        imageUrl: 'https://myralog.hu/tarot/major-13.jpg'
    },
    {
        id: 'major-14', name: 'A Mértékletesség', nameEn: 'Temperance', arcana: 'Major', number: 14,
        element: 'Tűz', astrology: 'Nyilas', numerology: '14',
        keywords: ['Egyensúly', 'Mértékletesség', 'Türelem', 'Harmónia', 'Alkímia'],
        meaningUpright: 'Az ellentétek harmonikus egyesítése és a belső béke megtalálása. A Mértékletesség a spirituális alkímia kártyája: hogyan keverjük össze a vizet és a tüzet (érzelmet és cselekvést) úgy, hogy ne oltsák ki egymást, hanem új minőséget alkossanak. A gyógyulás és a türelmes fejlődés ideje.',
        meaningReversed: 'Egyensúlyhiány, szélsőségek, türelmetlenség, diszharmónia, a mérték elvesztése vagy érzelmi zűrzavar.',
        generalMeaning: 'Ez a kártya az arany középutat képviseli. Arra tanít, hogy a harmónia nem a statikus állapot, hanem egy folyamatos finomhangolás. Az életben minden összetevőnek megvan a helye, ha a megfelelő arányban használjuk őket. A gyógyulás és a belső integráció legfőbb lapja.',
        loveMeaning: 'Harmonikus, békés kapcsolatot jelez. A felek között mély a lelki rokonság és az összhang. Képesek vagytok türelemmel és megértéssel csiszolódni egymáshoz.',
        careerMeaning: 'Kellemes, stresszmentes munkakörnyezetet jelent. A feladatokat nyugodtan és kiegyensúlyozottan végzed. Jó időszak a csapatmunkára és az együttműködésre.',
        advice: 'Légy türelmes és mértéktartó! Keresd az egyensúlyt a munka és a magánélet, a vágyak és a lehetőségek között. Most a lassú, megfontolt haladás hoz sikert.',
        dailyMeaning: 'Ma a nyugalom napja van. Ne engedd, hogy bármi kizökkentsen az egyensúlyodból. Kezelj minden konfliktust békésen és diplomáciával.',
        yearlyMeaning: 'A gyógyulás és a stabilizálódás éve. Ebben az évben minden a helyére kerül az életedben, és megtalálod a belső békédet, amit oly régóta kerestél.',
        history: 'A sarkalatos erények egyike. Az alkímiai "Temperatio" folyamata, ahol az anyagot tisztítják és nemesítik a megfelelő hőmérsékleten.',
        symbolism: 'Az angyal vizet önt egyik kehelyből a másikba (spirituális áramlás), egyik lába a vízen (tudattalan), a másik a földön (valóság) nyugszik, az íriszek a háttérben a reményt jelzik.',
        questions: ['Életed mely területén van szükség több egyensúlyra?', 'Hogyan tudnád harmonizálni az ellentétes vágyaidat?'],
        affirmation: "Harmóniát teremtek testemben, lelkemben és szellememben.",
        imageUrl: 'https://myralog.hu/tarot/major-14.jpg'
    },
    {
        id: 'major-15', name: 'Az Ördög', nameEn: 'The Devil', arcana: 'Major', number: 15,
        element: 'Föld', astrology: 'Bak', numerology: '15',
        keywords: ['Függőség', 'Anyagiasság', 'Kötődés', 'Árnyék', 'Felszabadulás'],
        meaningUpright: 'Szembesülés a belső démonainkkal és a függőségeinkkel. Az Ördög rávilágít azokra a területekre, ahol elveszítettük a szabadságunkat a félelem, a kéj vagy az anyagi ragaszkodás miatt. Ugyanakkor óriási életerőt és kreatív energiát is hordoz, amit ha tudatosítunk, a javunkra fordíthatunk.',
        meaningReversed: 'Megszabadulás a láncoktól, a függőség felismerése és lezárása, spirituális ébredés a sötétség után, az árnyék integrálása.',
        generalMeaning: 'Az Ördög az illúzió kártyája: azt hiteti el velünk, hogy foglyok vagyunk, pedig a láncok lazák. Arra hív, hogy vizsgáljuk meg a sötét oldalunkat – azokat a vágyakat, amiket elfojtunk. Ez a kártya a szexualitás, a hatalom és az anyag birodalma; nem gonosz, csak akkor veszélyes, ha ural minket.',
        loveMeaning: 'Szenvedélyes, de gyakran mérgező kapcsolatot jelez. Utalhat birtoklási vágyra vagy szexuális függőségre. Arra int, hogy vigyázz az egészségtelen kötődésekkel.',
        careerMeaning: 'Anyagiasság és a siker hajszolása bármi áron. Lehet, hogy rabszolgának érzed magad a munkádban, vagy korrupt viszonyokba keveredtél. Itt az ideje visszaszerezni az önállóságodat.',
        advice: 'Nézz szembe az árnyékoddal! Ismerd fel, mi az, ami valóban rabságban tart, és értsd meg: te magad vagy a kulcs a saját szabadulásodhoz.',
        dailyMeaning: 'Ma kísértésbe eshetsz, vagy rátörhet egy régi kényszerképzeted. Ne büntesd magad, csak figyeld meg az érzést, és ne hagyd, hogy irányítson.',
        yearlyMeaning: 'Az árnyékmunka éve. Szembesülnöd kell a legmélyebb félelmeiddel és vágyaiddal, hogy év végére szabadon és integráltan élhess tovább.',
        history: 'Pán isten vagy Baphomet alakja. A keresztény ikonográfiában a bűn jelképe, de a tarotban az anyagi világ sűrűségét és a szellem rabságát jelenti.',
        symbolism: 'A laza láncok a nyakakon jelzik, hogy a fogság mentális és önkéntes. A fordított pentagram a homlokon az anyag uralmát jelenti a szellem felett.',
        questions: ['Mi az, ami valóban rabságban tart?', 'Milyen elfojtott vágyad vár felszabadításra?'],
        affirmation: "Felismerem árnyékomat és a fény felé fordulok.",
        imageUrl: 'https://myralog.hu/tarot/major-15.jpg'
    },
    {
        id: 'major-16', name: 'A Torony', nameEn: 'The Tower', arcana: 'Major', number: 16,
        element: 'Tűz', astrology: 'Mars', numerology: '16',
        keywords: ['Hirtelen változás', 'Káosz', 'Felismerés', 'Összeomlás', 'Ébredés'],
        meaningUpright: 'A hamis biztonság és az illúziók hirtelen összeomlása. A Torony a villámcsapásszerű felismerés, ami lerombolja azt, ami nem stabil alapokra épült. Bár sokkoló és félelmetes lehet, valójában felszabadít egy olyan börtönből, aminek a rácsait észre sem vettük. A káosz után tiszta égbolt marad.',
        meaningReversed: 'Félelem a változástól, elkerült katasztrófa (ami így csak elodázódik), lassú, kínzó összeomlás vagy belső válság kifejezés nélkül.',
        generalMeaning: 'A Torony a radikális igazság kártyája. Lerombolja az egó építményeit, hogy helyet adjon a lélek valóságának. Ez a kártya a "Szürke Köd" eloszlása egy hatalmas vihar árán. Fájdalmas, de elkerülhetetlen szakasz a spirituális fejlődésben: a falaknak le kell dőlniük, hogy láthasd a csillagokat.',
        loveMeaning: 'Hirtelen szakítást vagy egy drámai felismerést jelez, ami alapjaiban rengeti meg a kapcsolatot. Egy titok kiderülése, ami után már semmi sem lesz ugyanolyan.',
        careerMeaning: 'Váratlan felmondást vagy egy projekt összeomlását jelentheti. Radikális irányváltásra kényszerít, ami végül elvezet az igazi hivatásodhoz.',
        advice: 'Ne próbáld foltozgatni a repedéseket! Hagyd, hogy összeomoljon, ami nem igaz és nem tartós. Állj bele a viharba, és várd meg a megvilágosodás pillanatát.',
        dailyMeaning: 'Ma valami váratlan dolog történhet, ami kizökkent a nyugalmadból. Ne állj ellen a változásnak, bármilyen ijesztő is; ez a fejlődésed kulcsa.',
        yearlyMeaning: 'A felszabadulás és az ébredés éve. Ami ingatag és hamis volt az életedben, az most eltűnik, hogy év végére sziklaszilárd alapokra építhess.',
        history: 'Bábel tornya vagy Isten Háza (La Maison Dieu). Az isteni beavatkozás szimbóluma, amely megállítja az emberi gőgöt és visszaterel az igazsághoz.',
        symbolism: 'A villám az isteni tudatosság, a zuhanó alakok az egó és a régi minták elvesztése, a korona a torony tetején a hamis szellemi hatalom bukása.',
        questions: ['Milyen hamis biztonságba kapaszkodsz?', 'Mi maradna belőled, ha minden külső bástyád ledőlne?'],
        affirmation: "Bátran fogadom a változást, amely felszabadít.",
        imageUrl: 'https://myralog.hu/tarot/major-16.jpg'
    },
    {
        id: 'major-17', name: 'A Csillag', nameEn: 'The Star', arcana: 'Major', number: 17,
        element: 'Levegő', astrology: 'Vízöntő', numerology: '17',
        keywords: ['Remény', 'Hit', 'Inspiráció', 'Gyógyulás', 'Cél'],
        meaningUpright: 'A vihar utáni béke, a remény és a spirituális gyógyulás kártyája. A Csillag azt üzeni, hogy túl vagy a nehezén, és most az Univerzum áldása kísér. Ez a tiszta inspiráció és a jövőbe vetett megingathatatlan hit ideje. Nyugalmat, belső fényt és a céljaidhoz való visszatalálást ígéri.',
        meaningReversed: 'Reménytelenség, kiábrándultság, hitvesztés, kreatív blokk vagy elszigeteltség az isteni vezettetéstől.',
        generalMeaning: 'A Csillag a lélek regenerálódását jelképezi. A Torony rombolása után ő hozza el a vígaszt és a tiszta látásmódot. Nemcsak reményt ad, hanem valódi gyógyulást is – érzelmileg és szellemileg egyaránt. Ez a kártya a kozmikus bizalom: jó helyen vagy, és az utad fényesebb, mint valaha.',
        loveMeaning: 'Ígéretes új találkozást vagy a meglévő kapcsolat gyógyulását jelzi. A szerelem itt tiszta, inspiráló és mentes a játszmáktól. Spirituális szintű kapcsolódás.',
        careerMeaning: 'Inspiráló időszak, ahol a kreativitásod szárnyalhat. Hosszú távú projektekhez kapsz támogatást, és végre látod a munkád igazi értelmét.',
        advice: 'Bízz a jövőben! Kövesd a belső fényedet, és ne félj megmutatni a világnak a legtisztább, legsebezhetőbb énedet. A gyógyulás folyamatban van.',
        dailyMeaning: 'Ma tele leszel optimizmussal. Valamilyen jel érkezhet, ami megerősít abban, hogy a helyes úton jársz. Mosolyogj, a csillagok neked ragyognak.',
        yearlyMeaning: 'A remény és a spirituális kivirágzás éve. Ebben az évben a sebek behegednek, és egy olyan jövőt alapozol meg, ami tele van fénnyel és értelemmel.',
        history: 'Pandora szelencéjének utolsó kincse: a Remény. A misztikában a Stella Maris (Tenger Csillaga), az útkeresők égi iránytűje.',
        symbolism: 'A meztelen nő a maszkok nélküli igazságot, a hét kis csillag a csakrákat vagy bolygókat, a víz öntése az érzelmek (tudattalan) és a föld (valóság) táplálását jelképezi.',
        questions: ['Mi a legmerészebb álmod a jövőre nézve?', 'Miben találod meg a reményt a sötét időkben?'],
        affirmation: "Bízom az Univerzumban és követem a belső fényemet.",
        imageUrl: 'https://myralog.hu/tarot/major-17.jpg'
    },
    {
        id: 'major-18', name: 'A Hold', nameEn: 'The Moon', arcana: 'Major', number: 18,
        element: 'Víz', astrology: 'Halak', numerology: '18',
        keywords: ['Illúzió', 'Félelem', 'Tudatalatti', 'Intuíció', 'Misztikum'],
        meaningUpright: 'A bizonytalanság, a sötétben való tapogatózás és a tudatalatti félelmek birodalma. A Hold rávilágít azokra a dolgokra, amiket nappali fénynél nem akarunk látni. Bár félelmetes lehet, ez a kártya a mély intuíció és a kreatív fantázia forrása is. Arra int, hogy ne higgy el mindent, amit látsz, és hallgass a megérzéseidre.',
        meaningReversed: 'Félelmek feloldása, titkok lelepleződése, a zavarodottság vége, tisztánlátás a köd után vagy az érzelmi zűrzavar lecsendesedése.',
        generalMeaning: 'A Hold a lélek sötét éjszakáját és a tudattalan mélységeit képviseli. Ez a "Szürke Köd" birodalma, ahol a formák elmosódnak. Arra tanít, hogy nézzünk szembe a belső árnyainkkal és az ösztöneinkkel. Ez a kártya a várakozás és az óvatosság ideje: nem minden az, aminek látszik.',
        loveMeaning: 'Bizonytalanságot, féltékenységet vagy titkolózást jelezhet. Lehet, hogy illúziókba ringatod magad, vagy félsz megmutatni a valódi arcodat a partnernek.',
        careerMeaning: 'Kavarodás, pletykák vagy bizonytalan jövőkép. Most ne hozz fontos üzleti döntéseket, mert nem látsz tisztán minden részletet. Várj, amíg felszáll a köd.',
        advice: 'Ne félj a sötéttől, de légy óvatos! Hallgass a megérzéseidre és az álmaidra, de ne hagyd, hogy a szorongásaid megbénítsanak. Figyeld a jeleket a felszín alatt.',
        dailyMeaning: 'Ma nyugtalanabb lehetsz a szokásosnál. Ne erőltess semmilyen konkrét választ; inkább merülj el a kreatív álmodozásban vagy meditálj.',
        yearlyMeaning: 'A belső árnyakkal való szembenézés és az intuíció fejlesztésének éve. Ebben az évben megtanulsz bízni a belső iránytűdben a legnagyobb sötétségben is.',
        history: 'Hekaté, az alvilág és a keresztutak istennője. A Hold az ókor óta a változékonyság, a női ciklusok és a rejtett erők szimbóluma.',
        symbolism: 'A rák a tudattalanból felbukkanó félelmek, a kutya és farkas a megszelídített és vad természet harca, az ösvény a hegyek felé a lélek ismeretlenbe vezető útja.',
        questions: ['Milyen félelem tart vissza az igazságtól?', 'Mit üzennének az álmaid, ha végre meghallgatnád őket?'],
        affirmation: "Bátran szembenézek a félelmeimmel és bízom a megérzéseimben.",
        imageUrl: 'https://myralog.hu/tarot/major-18.jpg'
    },
    {
        id: 'major-19', name: 'A Nap', nameEn: 'The Sun', arcana: 'Major', number: 19,
        element: 'Tűz', astrology: 'Nap', numerology: '19',
        keywords: ['Öröm', 'Siker', 'Vitalitás', 'Pozitivitás', 'Boldogság'],
        meaningUpright: 'A Tarot legpozitívabb kártyája: a teljes siker, a ragyogó öröm és a tisztánlátás szimbóluma. A Nap elűz minden árnyékot és ködöt, felfedve a tiszta valóságot és a sikert minden életterületen. Vitalitást, önbizalmat és gyermeki lelkesedést hoz. Azt üzeni: eljött a te időd a ragyogásra!',
        meaningReversed: 'Időleges ború, késleltetett siker, túlzott egó vagy önelégültség, ami elhomályosítja a valódi értékeket.',
        generalMeaning: 'A Nap a tudatosság diadala a sötétség felett. Azt jelenti, hogy minden a lehető legjobban alakul az életedben. Ez a kártya a teljes önazonosság és az életigenlés lapja. Nincs több maszk, nincs több rejtőzködés – csak a tiszta, ragyogó igazság és az elért célok feletti öröm.',
        loveMeaning: 'Felhőtlen boldogságot, kibékülést és szívből jövő melegséget jelent. A kapcsolatod virágzik, tele van nagylelkűséggel és bizalommal. Családi örömök ígérete.',
        careerMeaning: 'Sikert, elismerést és látványos eredményeket jelez. Most mindenki látja és értékeli a tehetségedet. Kiváló időszak új projektek indítására és a reflektorfénybe lépésre.',
        advice: 'Légy optimista és sugározz! Oszd meg a boldogságodat és a tudásodat másokkal. Cselekedj nyíltan, őszintén és magabiztosan – most minden ajtó nyitva áll előtted.',
        dailyMeaning: 'Ma csodálatos napod lesz! Használd ki ezt az energiát, alkoss, nevess és töltsd meg fénnyel a környezetedet is. Ma te vagy a világ közepe.',
        yearlyMeaning: 'A siker és a kiteljesedés éve. Ebben az évben minden terved beérik, és olyan boldogságot tapasztalsz meg, ami tartós és megalapozott lesz.',
        history: 'Héliosz vagy Apollón, a fény és az igazság istenei. A Nap a szellemi megvilágosodás és az élet forrásának egyetemes jelképe minden kultúrában.',
        symbolism: 'A Nap a megvilágosodást, a fehér lovon ülő gyermek a tiszta, újjászületett lelket, a vörös zászló a győzelmet, a fal pedig a múlt kereteit jelképezi, amik felett már túlnőttünk.',
        questions: ['Mi okoz neked tiszta, gyermeki örömöt?', 'Milyen tehetségedet szeretnéd végre megmutatni a világnak?'],
        affirmation: "Élvezem az életet és sugárzom a boldogságot.",
        imageUrl: 'https://myralog.hu/tarot/major-19.jpg'
    },
    {
        id: 'major-20', name: 'A Feltámadás', nameEn: 'Judgement', arcana: 'Major', number: 20,
        element: 'Tűz', astrology: 'Plútó', numerology: '20',
        keywords: ['Újjászületés', 'Hívás', 'Megbocsátás', 'Ébredés', 'Felismerés'],
        meaningUpright: 'A belső hívó szó követése és a teljes újjászületés. Ez a kártya azt a pillanatot jelzi, amikor a múlt terheit letéve, megtisztulva és önmagunknak megbocsátva új életet kezdünk. Ez nem ítélet, hanem megváltás: a felismerés, hogy kik vagyunk valójában, és mi a dolgunk a világban.',
        meaningReversed: 'A hívás elutasítása, félelem a változástól, ragaszkodás a múlt hibáihoz, bűntudat vagy elszalasztott lehetőség a fejlődésre.',
        generalMeaning: 'A Feltámadás a spirituális ébredés kártyája. Azt jelenti, hogy egy nehéz ciklus lezárult, és minden tapasztalatod – a fájdalom is – a javadat szolgálta. Most magasabb szintre lépsz. Ez a kártya a teljes transzformáció, az "igazi név" megtalálása és a lélek szabadsága.',
        loveMeaning: 'A kapcsolat "feltámadását" vagy egy sorsszerű újrakezdést jelenthet. Tisztáztátok a múltat, megbocsátottatok egymásnak, és most egy sokkal magasabb szinten kapcsolódtok.',
        careerMeaning: 'Megtalálod az igazi hivatásodat – azt a munkát, amire születtél. Jelentős váltást jelez, ami végre értelmet ad a mindennapjaidnak. Sikeres vizsga vagy elismert teljesítmény.',
        advice: 'Hallgass a belső hívásra! Emelkedj felül a múltbeli sérelmeiden, bocsáss meg magadnak, és indulj el az utadon. Most megvan az erőd az újrakezdéshez.',
        dailyMeaning: 'Ma egy fontos felismerésre juthatsz. Valamilyen régi ügyed végleg lezárulhat, felszabadítva téged. Figyelj a belső hangodra, ami cselekvésre ösztönöz.',
        yearlyMeaning: 'Az újjászületés és a hivatás megtalálásának éve. Ebben az évben teljesen új életet kezdesz, olyat, ami végre összhangban van a valódi éneddel.',
        history: 'A bibliai végítélet képe, ami a tarotban nem büntetést, hanem a lélek anyagi börtönéből való kiszabadulását és a szellemi ébredést szimbolizálja.',
        symbolism: 'Gábriel angyal harsonája az ébresztő, a nyitott sírok a múlt korlátai közül való kilépést, a meztelen alakok a tisztaságot és az újrakezdést jelzik.',
        questions: ['Mire hív most az élet?', 'Kinek kell megbocsátanod, hogy végre szabadon élhess?'],
        affirmation: "Megbocsátok magamnak és másoknak, és szabadon élek.",
        imageUrl: 'https://myralog.hu/tarot/major-20.jpg'
    },
    {
        id: 'major-21', name: 'A Világ', nameEn: 'The World', arcana: 'Major', number: 21,
        element: 'Föld', astrology: 'Szaturnusz', numerology: '21',
        keywords: ['Beteljesülés', 'Egység', 'Utazás', 'Siker', 'Teljesség'],
        meaningUpright: 'A hős útjának sikeres befejezése és a célba érés. A Világ a teljes harmóniát, a beteljesülést és a helyünk megtalálását jelképezi. Azt üzeni, hogy minden a helyére került, kerek az egész, és te egységben vagy önmagaddal és az Univerzummal. A győzelem és a boldogság csúcspontja.',
        meaningReversed: 'Befejezetlenség, egy utolsó akadály a cél előtt, hiányérzet a siker kapujában, elhúzódó lezárás vagy stagnálás a teljesség előtt.',
        generalMeaning: 'Ez a Nagy Árkánum utolsó kártyája: a kozmikus tánc és az abszolút teljesség szimbóluma. Azt jelenti, hogy minden tapasztalatod összeállt egy nagy képpé. Megérkeztél. Nemcsak külső sikert jelent, hanem azt a belső állapotot, amikor tudod, hogy ott vagy, ahol lenned kell.',
        loveMeaning: 'A "megérkezés" érzése a kapcsolatban. Megtaláltad a társadat, akivel teljes az életed. Hosszú távú boldogság, esküvő vagy közös otthonteremtés a világ bármely pontján.',
        careerMeaning: 'Elérted a szakmai csúcsot. Sikeresen befejeztél egy nagy ciklust, és most élvezheted a gyümölcseit. Nemzetközi lehetőségek, utazás és teljes szakmai elismerés vár.',
        advice: 'Ünnepeld a teljességet! Foglald el méltó helyedet a világban, és ne félj tágítani a horizontodat. Te és a Világ egyek vagytok – élvezd ezt az egységet.',
        dailyMeaning: 'Ma minden kerek és egész. Érezd magad otthon a bőrödben és a környezetedben. Ma valami fontos dolog a helyére kattan a fejedben és a szívedben.',
        yearlyMeaning: 'A beteljesülés és a világutazás éve. Ebben az évben aratod le életed eddigi legnagyobb sikereit, és megtapasztalod az igazi belső szabadságot.',
        history: 'A kozmikus tánc szimbóluma (Anima Mundi - Világlélek). A négy evangélista (vagy a négy rögzített jegy) keretezi, jelezve a tér és idő feletti uralmat.',
        symbolism: 'A táncoló hermafrodita alak az ellentétek tökéletes egyesítését, a babérkoszorú a győzelmet, a négy sarokalak a négy elemet és a világ teljességét jelképezi.',
        questions: ['Mi az, ami valóban teljessé teszi az életedet?', 'Hogyan tudnád megünnepelni azt, aki mára lettél?'],
        affirmation: "Egy vagyok a világgal, és a világ egy velem.",
        imageUrl: 'https://myralog.hu/tarot/major-21.jpg'
    },
];
