
import { Card } from '../types';

export const MAJOR_ARCANA: Card[] = [
    {
        id: 'major-0', name: 'A Bolond', nameEn: 'The Fool', arcana: 'Major', number: 0,
        element: 'Levegő', astrology: 'Uránusz', numerology: '0',
        keywords: ['Új kezdet', 'Lelkesedés', 'Kaland', 'Lehetőség', 'Spontaneitás'],
        meaningUpright: 'Új kezdetek, lelkesedés, kalandok, friss lehetőségek, a lehetőség arra, hogy életre keltsd álmaidat.',
        meaningReversed: 'Naivitás, feltételezve, hogy már megvan a válasz, kiütéses döntések.',
        generalMeaning: 'A Bolond a bennünk élő gyermeket szimbolizálja. Spontán újrakezdést és elfogulatlan nyitottságot jelent. A Nagy Arkánum 0. kártyája, aki minden kezdet és minden lehetőség hordozója.',
        loveMeaning: 'Vidám, bonyodalmaktól mentes, életigenlő kapcsolatot jelez. Utalhat egy új szerelem kezdetére, ami kockázatosnak tűnhet, de tele van izgalommal.',
        careerMeaning: 'Új területre lépünk, ahol még nincs tapasztalatunk, de tele vagyunk kíváncsisággal. Friss ötletek, vállalkozókedv.',
        advice: 'Légy nyitott és előítéletektől mentes! Merj kockáztatni. Ugorj bele az ismeretlenbe, és bízz abban, hogy az Univerzum elkap.',
        dailyMeaning: 'Légy ma spontán! Engedd el a görcsös irányítást, és hagyd, hogy az élet meglepjen.',
        yearlyMeaning: 'Ez az év az új kezdetek éve. Merj belevágni az ismeretlenbe! Most minden lehetséges.',
        questions: ['Ha tudnád, hogy az Univerzum repülés közben elkap, hova ugranál?', 'Hol van szükséged több spontaneitásra az életedben?'],
        affirmation: "Felébresztem a lelkem ösvényét, és készen állok a kalandra.",
        imageUrl: 'https://myralog.hu/tarot/major-0.jpg',
        shortDesc: 'A Tiszta Kezdet',
        history: 'A Bolond a Tarot pakli legtitokzatosabb figurája. A középkori udvari bolondokhoz hasonlít, akiknek kiváltsága volt az igazság kimondása a király előtt büntetés nélkül. Ő a hős, aki elindul az úton (a Bolond Utazása), és végighalad a Nagy Arkánum stációin, hogy a végén a Világ kártyájában beteljesedjen.',
        symbolism: 'A szakadék szélén álló ifjú a kockázatvállalást jelképezi. A fehér kutya az ösztönös védelmezőt és a hűséget szimbolizálja, aki figyelmeztet a veszélyre. A batyu a vállán tartalmazza mindazt a tudást (a négy elemet), amire szüksége lesz, bár még nem tud róla. A fehér rózsa a tisztaságot és az ártatlanságot jelenti.',
        comparison: {
            title: 'Bolond vs. Mágus',
            text: 'Míg a Bolond a terv nélküli, tiszta potenciál és a hit útján jár, a Mágus már tudatosan használja az eszközeit a manifesztációhoz. A Bolondnál az ösztön vezérel, a Mágusnál az akarat.',
            relatedCardId: 'major-1'
        }
    },
    {
        id: 'major-1', name: 'A Mágus', nameEn: 'The Magician', arcana: 'Major', number: 1,
        element: 'Levegő', astrology: 'Merkúr', numerology: '1',
        keywords: ['Készségek', 'Erő', 'Manifesztáció', 'Fókusz', 'Teremtés'],
        meaningUpright: 'Készségek, természetes adottságok, erő, vágyaid kifejezésének képessége. A Mágus összeköti az eget a földdel.',
        meaningReversed: 'Kihasználatlan potenciál, lappangó tehetségek, manipuláció, trükközés, önbizalomhiány.',
        generalMeaning: 'A Mágus az aktív cselekvést, a tudatosságot és az élet irányításának képességét jelenti. Rendelkezésére áll minden eszköz a céljai eléréséhez.',
        loveMeaning: 'Erős vonzerőt és kezdeményezőkészséget jelez. A kapcsolatban aktív, teremtő energia van jelen.',
        careerMeaning: 'Sikeres vizsgákat, tárgyalásokat vagy projekteket jelez. Képes vagy megvalósítani az ötleteidet.',
        advice: 'Vedd kezedbe az irányítást! Használd a tehetségedet. Fókuszáld az energiáidat egy célra.',
        dailyMeaning: 'Ma minden sikerülhet, ha aktívan teszel érte. A varázslat a kezedben van.',
        yearlyMeaning: 'Ebben az évben a kezedbe veheted a sorsodat. Aktív, teremtő év vár rád, ahol a gondolataid valósággá válnak.',
        questions: ['Milyen eszközök állnak rendelkezésére, amelyeket nem használ ki maradéktalanul?', 'Mit szeretnél megteremteni most?'],
        affirmation: "Kinyilvánítom az általam kívánt életet az energia és a szándék révén. Én vagyok a teremtő.",
        imageUrl: 'https://myralog.hu/tarot/major-1.jpg',
        history: 'A Mágus eredetileg a vásári mutatványost vagy bűvészt ábrázolta a korai Tarot paklikban. Később, az okkultista hagyományokban vált a beavatott mesterré, aki uralja az elemeket. Ő az "As Above, So Below" (Amint fent, úgy lent) elv megtestesítője.',
        symbolism: 'Egyik kezével az ég felé mutat (isteni inspiráció), a másikkal a föld felé (megvalósítás). Előtte az asztalon a négy elem szimbólumai: Kehely (víz/érzelem), Kard (levegő/gondolat), Bot (tűz/akarat) és Érme (föld/anyag). A feje feletti fektetett nyolcas (lemniszkáta) a végtelenséget és az örök körforgást jelzi.',
        shortDesc: 'A Teremtő Erő'
    },
    {
        id: 'major-2', name: 'A Főpapnő', nameEn: 'The High Priestess', arcana: 'Major', number: 2,
        element: 'Víz', astrology: 'Hold', numerology: '2',
        keywords: ['Intuíció', 'Álmok', 'Csend', 'Titkok', 'Misztikum'],
        meaningUpright: 'Intuíció, álmok, tudatalatti üzenetek, passzivitás, várakozás, belső tudás.',
        meaningReversed: 'Titkok, pletykák, a belső hang figyelmen kívül hagyása, felszínesség.',
        generalMeaning: 'A Főpapnő a tudattalan erőinket, az intuíciót és a megérzéseket képviseli. Ő az őrzője a titkos tudásnak, ami a fátyol mögött rejlik.',
        loveMeaning: 'Mély lelki összetartozást, empátiát és megértést jelez. Néha titkos viszonyra vagy elérhetetlen szerelemre is utalhat.',
        careerMeaning: 'Olyan feladatokat jelez, ahol pszichológiai érzékre vagy intuícióra van szükség. Hallgass a megérzéseidre üzleti döntéseknél.',
        advice: 'Ne cselekedj elhamarkodottan! Várj, figyelj befelé. Bízz az álmaidban és a jelekben.',
        dailyMeaning: 'Ma hagyatkozz az ösztöneidre. Figyelj az álmokra. A csendben találod meg a választ.',
        yearlyMeaning: 'Ez az év a belső utazás éve. Fontos felismerésekre juthatsz, ha befelé figyelsz.',
        questions: ['Hogyan lépsz kapcsolatba intuitív szíveddel?', 'Mi az a titok, amit fel kell tárnod magadban?'],
        affirmation: "A hit az intuitív szívemben van. Bízom a belső hangomban.",
        imageUrl: 'https://myralog.hu/tarot/major-2.jpg',
        history: 'A középkorban "Nőpápa" néven is ismerték, utalva a legendás Johanna nőpápára. Ő a spirituális anya, a bölcsesség istennőjének földi helytartója. Míg a Mágus a kiáradó, maszkulin energia, a Főpapnő a befogadó, feminin minőség.',
        symbolism: 'A két oszlop (Jachin és Boaz) a dualitást (fény/sötét, aktív/passzív) jelképezi, ő pedig a középutat. A mögötte lévő gránátalmás kárpit a termékenységet és a tudatalatti (víz) elrejtését szimbolizálja. A kezében tartott tekercs (TORA) a rejtett törvényt és tudást jelenti. A Hold a lábánál az intuíció és a ciklikusság szimbóluma.',
        shortDesc: 'A Belső Tudás Őrzője'
    },
    {
        id: 'major-3', name: 'Az Uralkodónő', nameEn: 'The Empress', arcana: 'Major', number: 3,
        element: 'Föld', astrology: 'Vénusz', numerology: '3',
        keywords: ['Termékenység', 'Bőség', 'Gondoskodás', 'Kreativitás', 'Anyaság'],
        meaningUpright: 'Termékenység, kreativitás, bőség, anyaság, érzékiség, új dolgok születése, a természet ereje.',
        meaningReversed: 'Kreatív blokkok, függőség, elhanyagolás, túlzott gondoskodás (fojtogató anya).',
        generalMeaning: 'Az Uralkodónő a természet kifogyhatatlan erejét és a növekedést jelképezi. Ő a Nagy Anya, aki táplál és védelmez mindent, ami él.',
        loveMeaning: 'Érzéki élvezeteket, szenvedélyt és védettséget jelent. Családalapításra, terhességre vagy a kapcsolat virágzására utalhat.',
        careerMeaning: 'Kreativitást, új ötletek születését és növekedést jelez. Bőséges időszak a vállalkozásban.',
        advice: 'Légy kreatív és élvezd az életet! Tápláld azt, ami növekedni akar. Kapcsolódj a természettel.',
        dailyMeaning: 'Menj ki a természetbe, alkoss valamit. Ma a bőség vesz körül, vedd észre a szépet.',
        yearlyMeaning: 'Termékeny év vár rád. Amit most elvetsz, az bőségesen fog teremni. Ideális év családalapításra vagy alkotásra.',
        questions: ['Készen állok megszülni __________.', 'Hogyan tudnám jobban gondozni magamat és környezetemet?'],
        affirmation: "Megszülöm bőségesen gazdag jövőmet. Életet és szépséget teremtek.",
        imageUrl: 'https://myralog.hu/tarot/major-3.jpg',
        history: 'Az Uralkodónő az ősi Természetanya és a Földistennő (pl. Démétér, Gaia) archetípusa. A Vénusz bolygóhoz kapcsolódik, amely a szerelmet, szépséget és művészetet uralja.',
        symbolism: 'A trónján ülő várandós nő a termékenységet jelképezi. A pajzsán vagy a közelében lévő Vénusz-jel a nőiességet és a szeretetet mutatja. A gabonamező az aratást és a bőséget, az erdő és a folyó az élet áramlását jelenti. Koronája a tizenkét csillaggal az év tizenkét hónapját vagy az állatövi jegyeket szimbolizálja.',
        shortDesc: 'A Termékeny Anya'
    },
    {
        id: 'major-4', name: 'Az Uralkodó', nameEn: 'The Emperor', arcana: 'Major', number: 4,
        element: 'Tűz', astrology: 'Kos', numerology: '4',
        keywords: ['Vezetés', 'Struktúra', 'Hatalom', 'Rend', 'Stratégia'],
        meaningUpright: 'Struktúra, stabilitás, tekintély, apaság, logikus döntések, védelem, felelősség.',
        meaningReversed: 'Zsarnokság, merevség, kontrollmánia, gyengeség, a hatalommal való visszaélés.',
        generalMeaning: 'Az Uralkodó a rendet, a struktúrát és a biztonságot képviseli. Ő a civilizáció építője, aki törvényeket hoz a káosz ellen.',
        loveMeaning: 'Stabilitást és biztonságot jelent a kapcsolatban. Egy erős, gondoskodó, de talán kicsit domináns partnert jelezhet.',
        careerMeaning: 'Sikert, vezetői pozíciót, strukturált megvalósítást jelent. Ideje megszervezni a munkát és szabályokat alkotni.',
        advice: 'Teremts rendet! Húzd meg a határaidat és légy következetes. Érvényesítsd az akaratodat logikusan.',
        dailyMeaning: 'Ma légy határozott és rendezd a soraidat. Hozz döntéseket fejjel, ne szívvel.',
        yearlyMeaning: 'Az építkezés és a stabilizáció éve. Most alapozhatod meg a jövődet. Kemény munka és fegyelem vezet eredményre.',
        questions: ['Mit építesz, és hogyan fog kinézni, ha elkészültél?', 'Hol van szükség több fegyelemre az életedben?'],
        affirmation: "Magabiztossággal és tekintéllyel vezetem az életemet.",
        imageUrl: 'https://myralog.hu/tarot/major-4.jpg',
        history: 'Az Uralkodó az "Apa" archetípus, a világi hatalom és a társadalmi rend megtestesítője. Míg az Uralkodónő a természet vad burjánzása, az Uralkodó a városfalak és a törvények biztonsága.',
        symbolism: 'A kőtrón a stabilitást és a keménységet jelzi. A kos fejek a Kos csillagjegyet (Mars uralma alatt) és a törtető erőt szimbolizálják. A jogar (ankh kereszt) az élet feletti uralmat, az országalma a világ feletti hatalmat jelenti. A háttérben lévő kopár hegyek a szigort és a kihívásokat mutatják.',
        shortDesc: 'A Rend Őre'
    },
    {
        id: 'major-5', name: 'A Főpap', nameEn: 'The Hierophant', arcana: 'Major', number: 5,
        element: 'Föld', astrology: 'Bika', numerology: '5',
        keywords: ['Hagyomány', 'Hit', 'Tanítás', 'Spirituális vezető', 'Bölcsesség'],
        meaningUpright: 'Spirituális útmutatás, hagyományok, házasság, tanulás, hit, közösségi normák.',
        meaningReversed: 'Dogmatizmus, lázadás a normák ellen, képmutatás, rossz tanács, szűklátókörűség.',
        generalMeaning: 'A Főpap a bizalom, a hit és a mélyebb értelem keresésének kártyája. Ő a híd az isteni és az emberi világ között (Pontifex).',
        loveMeaning: 'A bizalom és az egymás iránti elköteleződés növekedését jelzi. Házasságkötést vagy tradicionális értékeken alapuló kapcsolatot mutathat.',
        careerMeaning: 'Megtaláljuk hivatásunk értelmét. Tanári pálya, mentorálás vagy egy nagy szervezetbe való beilleszkedés.',
        advice: 'Keresd a dolgok mélyebb értelmét! Tarts ki az elveid mellett. Tanulj a bölcsebbektől.',
        dailyMeaning: 'Ma találkozhatsz valakivel, aki fontos tanácsot ad. Kövesd a bevált módszereket.',
        yearlyMeaning: 'Ez az év a bizalom és az értelemkeresés jegyében telik. Csatlakozhatsz egy közösséghez vagy tanfolyamhoz.',
        questions: ['Milyen hiedelem áll az álmaid útjában?', 'Kinek a tanácsára hallgatsz?'],
        affirmation: "Én vagyok a saját gurum, de tisztelem a hagyomány bölcsességét.",
        imageUrl: 'https://myralog.hu/tarot/major-5.jpg',
        history: 'A "Pápa" kártyájaként is ismert, a spirituális hatalmat képviseli az Uralkodó világi hatalmával szemben. Ő a titkos tudás nyilvános tanítója (szemben a Főpapnő rejtett tudásával).',
        symbolism: 'A hármas tiara a három sík (fizikai, asztrális, isteni) feletti uralmat jelzi. A két tanítvány a tudás átadását szimbolizálja. A kulcsok a mennyország kulcsai (Szent Péter kulcsai), amelyek megnyitják a rejtélyeket. A kéztartása áldást oszt.',
        shortDesc: 'A Spirituális Tanító'
    },
    {
        id: 'major-6', name: 'A Szeretők', nameEn: 'The Lovers', arcana: 'Major', number: 6,
        element: 'Levegő', astrology: 'Ikrek', numerology: '6',
        keywords: ['Szerelem', 'Választás', 'Harmónia', 'Kapcsolat', 'Egység'],
        meaningUpright: 'Szerelem, harmónia, fontos döntés, egyesülés, vonzalom, morális választás.',
        meaningReversed: 'Döntésképtelenség, diszharmónia, elválás, hűtlenség, rossz választás.',
        generalMeaning: 'A Szeretők kártyája a nagy szerelmet és a szükségszerű döntést öleli fel. Nemcsak a romantikáról szól, hanem az értékek közötti választásról is.',
        loveMeaning: 'A nagy szerelem kártyája. Mély érzelmi kapcsolatot és boldogságot jelez. Döntés egy kapcsolat mellett.',
        careerMeaning: 'Szenvedéllyel végzett munkát vagy teljes elköteleződést jelent. Üzleti partnerséget is jelezhet.',
        advice: 'Dönts szívből! Egyesítsd az erőidet másokkal. Válaszd azt, ami egész-sé tesz.',
        dailyMeaning: 'Ma döntéshelyzetbe kerülhetsz. Válaszd azt, amihez a szíved húz.',
        yearlyMeaning: 'A szív döntéseinek éve. Elköteleződés egy fontos ügy vagy személy mellett.',
        questions: ['Képes vagy ebben az időben teljesen beleállni egy partnerségbe?', 'Milyen válaszút előtt állsz?'],
        affirmation: "A szívem nyitott a mélyen értelmes kapcsolatra.",
        imageUrl: 'https://myralog.hu/tarot/major-6.jpg',
        history: 'A régebbi ábrázolásokon egy férfit láthatunk két nő (az Erény és a Kísértés) között, ami a választás kényszerét hangsúlyozta. A Waite-Smith pakli az Édenkertet ábrázolja Ádámmal és Évával.',
        symbolism: 'Az angyal (Rafael) a gyógyítást és az áldást hozza. A férfi a nőre néz, a nő az angyalra – ez a tudat (férfi) és a tudatalatti (nő) közötti kapcsolatot mutatja a felettes én (angyal) felé. A kígyó és az almafa a kísértést és a tudást, a lángoló fa a szenvedélyt jelképezi.',
        shortDesc: 'A Döntés és Egység'
    },
    {
        id: 'major-7', name: 'A Diadalszekér', nameEn: 'The Chariot', arcana: 'Major', number: 7,
        element: 'Víz', astrology: 'Rák', numerology: '7',
        keywords: ['Győzelem', 'Akaraterő', 'Irányítás', 'Haladás', 'Elszántság'],
        meaningUpright: 'Győzelem, előrehaladás, önfegyelem, utazás, siker az akarat révén, ellentétek uralása.',
        meaningReversed: 'Irányítás elvesztése, agresszió, akadályok, túl nagy ego, balesetveszély.',
        generalMeaning: 'A Diadalszekér a lendületet és az új utakra lépést jelképezi. A hős elhagyja a biztonságos otthont, hogy meghódítsa a világot.',
        loveMeaning: 'Új kapcsolat kezdetét vagy friss lendületet jelez. Néha a karrier és a magánélet közötti egyensúlyozásra utal.',
        careerMeaning: 'Nagy előrelépést, önállósodást vagy előléptetést jelent. Céltudatosságot igényel.',
        advice: 'Indulj el! Vedd kezedbe a gyeplőt és haladj a célod felé. Ne hagyd, hogy az érzelmek eltérítsenek.',
        dailyMeaning: 'Ma lendületben vagy. Használd ki ezt az energiát, de maradj fókuszált.',
        yearlyMeaning: 'Az áttörés éve. Ha eddig toporogtál, most végre elindulnak a dolgok.',
        questions: ['Merre tartasz? Ön átvette a kormányt?', 'Mi hajt előre?'],
        affirmation: "Én választom ki, hogy kivé válok, és meggyőződéssel futok felé.",
        imageUrl: 'https://myralog.hu/tarot/major-7.jpg',
        history: 'A Diadalszekér a római hadvezérek győzelmi menetét idézi. Platón kocsihajtó hasonlatára is utal, ahol az értelemnek kell irányítania az ösztönöket.',
        symbolism: 'A szfinxek (fekete és fehér) az ellentétes erőket jelképezik, amelyeket a kocsihajtónak puszta akarattal kell egy irányba terelnie (nincs gyeplő!). A csillagos baldachin az égi védelmet mutatja. A páncél a védekezést és a keménységet jelzi a külvilággal szemben.',
        shortDesc: 'A Győzedelmes Akarat'
    },
    {
        id: 'major-8', name: 'Az Erő', nameEn: 'Strength', arcana: 'Major', number: 8,
        element: 'Tűz', astrology: 'Oroszlán', numerology: '8',
        keywords: ['Bátorság', 'Együttérzés', 'Belső erő', 'Türelem', 'Szelídség'],
        meaningUpright: 'Belső erő, bátorság, szenvedély megszelídítése, türelem, együttérzés, morális tartás.',
        meaningReversed: 'Gyengeség, önbizalomhiány, nyers ösztönök uralma, agresszió vagy gyávaság.',
        generalMeaning: 'Az Erő nem a fizikai izomerőt, hanem a belső tartást, a szenvedélyt és a bátorságot jelenti. A vad ösztönök szeretetteljes elfogadása és irányítása.',
        loveMeaning: 'Szenvedélyes, tüzes kapcsolatot jelez, ahol a felek egyenrangúak. Türelmet és elfogadást igényel.',
        careerMeaning: 'Teljes bevetést, munkakedvet és kreatív energiákat jelent. Kitartással éred el a sikert.',
        advice: 'Légy bátor és szenvedélyes! Használd az erődet bölcsen. Győzz meg másokat szelídséggel, ne erővel.',
        dailyMeaning: 'Ma tele vagy energiával. Nézz szembe a félelmeiddel szeretettel.',
        yearlyMeaning: 'Szenvedélyes és energikus év. Megoldod a nehéz feladatokat, ha hiszel magadban.',
        questions: ['Hogyan találhatsz bátorságot a gyengédségben?', 'Mit kell megszelídítened magadban?'],
        affirmation: "Szándékosan ragyogtatom együttérzésem és erőm.",
        imageUrl: 'https://myralog.hu/tarot/major-8.jpg',
        history: 'Korábban "Fortitude" (Lelki erő) néven a négy sarkalatos erény egyike volt. Eredetileg gyakran Herkulest ábrázolta az oroszlánnal, később alakult át a szelíd nőalakká.',
        symbolism: 'A nőalak az oroszlán száját fogja, de nem erőszakkal, hanem bizalommal. Az oroszlán az alantas ösztönöket és a szenvedélyt jelképezi. A nő feje feletti fektetett nyolcas (mint a Mágusnál) a végtelen szellemi erőt mutatja. A fehér ruha a tisztaságot jelzi.',
        shortDesc: 'A Szelíd Erő'
    },
    {
        id: 'major-9', name: 'A Remete', nameEn: 'The Hermit', arcana: 'Major', number: 9,
        element: 'Föld', astrology: 'Szűz', numerology: '9',
        keywords: ['Önvizsgálat', 'Magány', 'Bölcsesség', 'Útmutatás', 'Reflexió'],
        meaningUpright: 'Belső útkeresés, elvonulás, bölcsesség, magány, önismeret, a válaszok megtalálása önmagunkban.',
        meaningReversed: 'Elszigetelődés, magányosság, a tanácsok figyelmen kívül hagyása, félelem a szembenézéstől.',
        generalMeaning: 'A Remete a befelé fordulás és a saját igazságunk megtalálásának kártyája. Nem a magánytól való félelmet, hanem a magány erejét mutatja.',
        loveMeaning: 'Érettebb szakaszba lépést vagy szükséges egyedüllétet jelez. Ideje átgondolni, mit vársz egy kapcsolattól.',
        careerMeaning: 'Itt az ideje átgondolni, mit is akarsz valójában. Nem a cselekvés, hanem a tervezés ideje.',
        advice: 'Vonulj vissza és tisztázd a céljaidat! A válasz benned van, világíts rá.',
        dailyMeaning: 'Ma tölts egy kis időt csendben. Figyelj befelé, meditálj.',
        yearlyMeaning: 'Az önismeret éve. Fontos döntéseket hozhatsz meg, ha hallgatsz a belső hangodra.',
        questions: ['Mit szólna a belső bölcsed, ha megkérdeznéd tőle, mit kell tenned?', 'Mi elől menekülsz a zajba?'],
        affirmation: "Békében vagyok a csenddel, és figyelek a belső hangomra.",
        imageUrl: 'https://myralog.hu/tarot/major-9.jpg',
        history: 'A Remete alakja Diogenészre, a lámpással embert kereső filozófusra, vagy az idő (Szaturnusz) allegóriájára utal.',
        symbolism: 'A lámpásban a hatágú csillag (Salamon pecsétje) a bölcsesség fénye, amely utat mutat a sötétben. A bot a támasz és a földhöz való kapcsolódás. A havas csúcs a magányt és a tiszta gondolatokat, a spirituális magaslatot jelzi.',
        shortDesc: 'A Bölcs Útkereső'
    },
    {
        id: 'major-10', name: 'Szerencsekerék', nameEn: 'Wheel of Fortune', arcana: 'Major', number: 10,
        element: 'Tűz', astrology: 'Jupiter', numerology: '10',
        keywords: ['Sors', 'Változás', 'Ciklusok', 'Karma', 'Szerencse'],
        meaningUpright: 'Sorsszerű változás, szerencse, új ciklus kezdete, fordulópont, karma, véletlenek.',
        meaningReversed: 'Balszerencse, ellenállás a változásnak, negatív ciklusok, tehetetlenség.',
        generalMeaning: 'A Szerencsekerék az élet állandó változására emlékeztet. Egyszer fent, egyszer lent. A sors keze belenyúl az életedbe.',
        loveMeaning: 'Sorsszerű találkozást vagy változást jelez. A kapcsolat új fázisba lép.',
        careerMeaning: 'Váratlan fordulat a karrierben, általában pozitív. Szerencsés lehetőség, amit meg kell ragadni.',
        advice: 'Fogadd el a változást! Alkalmazkodj a sorshoz. Tudd, hogy ez is el fog múlni.',
        dailyMeaning: 'Ma váratlan dolgok történhetnek. Légy rugalmas és sodródj az árral.',
        yearlyMeaning: 'A sorsfordító változások éve. Új irányt vehet az életed, légy nyitott.',
        questions: ['Hiszel abban, hogy a sorsod elkerülhetetlen, vagy te alakítod azt?', 'Hogyan kezeled a változást?'],
        affirmation: "Elfogadom az élet körforgását és bízom a sorsomban.",
        imageUrl: 'https://myralog.hu/tarot/major-10.jpg',
        history: 'A középkori Fortuna istennő kerekét ábrázolja, amelyen királyok emelkednek fel és hullanak a porba. Ez a "Memento Mori" (emlékezz a halálra/mulandóságra) egyik vizuális megjelenése.',
        symbolism: 'A kerék sarkainál a négy evangélista (angyal, sas, oroszlán, bika) látható, akik egyben a négy fix állatövi jegyet és a négy elemet is jelképezik, de itt tanulnak (könyvet tartanak). A szfinx a kerék tetején a rejtély és az egyensúly. A keréken a TORA/TAROT/ROTA (kerék) betűi és az Isten neve (JHVH) olvashatók.',
        shortDesc: 'A Sors Kereke'
    },
    {
        id: 'major-11', name: 'Az Igazságosság', nameEn: 'Justice', arcana: 'Major', number: 11,
        element: 'Levegő', astrology: 'Mérleg', numerology: '11',
        keywords: ['Igazság', 'Egyensúly', 'Karma', 'Felelősség', 'Integritás'],
        meaningUpright: 'Igazságosság, objektivitás, döntés, ok-okozat, jogi ügyek, tisztesség.',
        meaningReversed: 'Igazságtalanság, részrehajlás, felelősséghárítás, jogi problémák.',
        generalMeaning: 'Az Igazságosság az objektivitást és a felelősségvállalást jelenti. Azt kapod, amit adtál (karma). Hideg, tiszta racionalitás.',
        loveMeaning: 'Az egyenjogúság és az őszinteség fontosságát hangsúlyozza. Házasságkötést vagy válást is jelezhet (jogi értelemben).',
        careerMeaning: 'Világos helyzetértékelést és reális célokat követel. Szerződések aláírása, elszámoltatás.',
        advice: 'Légy objektív és fair! Vállald a felelősséget. Mérlegelj minden szempontot döntés előtt.',
        dailyMeaning: 'Ma légy megfontolt és igazságos. Valami eldőlhet.',
        yearlyMeaning: 'A felelősségvállalás éve. Most aratod le, amit vetettél. Jogi ügyek rendeződése.',
        questions: ['Hol vagy kiegyensúlyozatlan az életedben?', 'Vállalod a tetteid következményeit?'],
        affirmation: "Vállalom a felelősséget tetteimért és az igazságot keresem.",
        imageUrl: 'https://myralog.hu/tarot/major-11.jpg',
        history: 'Az egyik sarkalatos erény. A görög Themisz és Diké istennőkkel rokonítható. Hagyományosan a 8-as számú volt, de Waite felcserélte az Erővel (11), hogy asztrológiailag jobban illeszkedjen (Mérleg=11, Oroszlán=8).',
        symbolism: 'A mérleg a kiegyensúlyozást és az ítélkezést, a kard a döntés élességét és a hamisság levágását jelenti. A lila lepel mögötte a bölcsességre utal. A szögletes oszlopok a rendet és a törvényt szimbolizálják.',
        shortDesc: 'Az Objektív Igazság'
    },
    {
        id: 'major-12', name: 'Az Akasztott Ember', nameEn: 'The Hanged Man', arcana: 'Major', number: 12,
        element: 'Víz', astrology: 'Neptunusz', numerology: '12',
        keywords: ['Átadás', 'Új perspektíva', 'Várakozás', 'Elengedés', 'Megvilágosodás'],
        meaningUpright: 'Megállás, új nézőpont, áldozat, elengedés, türelem, spirituális átlényegülés.',
        meaningReversed: 'Stagnálás, mártíromság, hiábavaló áldozat, önzés, ellenállás.',
        generalMeaning: 'Az Akasztott Ember kényszerű megállást és nézőpontváltást jelez. A világ a feje tetejére áll, hogy végre tisztán láss.',
        loveMeaning: 'Elakadást jelez a kapcsolatban. Most nem tudsz előre lépni, el kell fogadnod a helyzetet. Áldozathozatal a szerelemért.',
        careerMeaning: 'A dolgok nem haladnak. A kényszerpihenő hasznos lehet a stratégiaváltáshoz.',
        advice: 'Változtass nézőpontot! Légy türelmes. Ne küzdj az ár ellen, hanem add át magad.',
        dailyMeaning: 'Ma semmi sem úgy alakul, ahogy tervezted. Fogadd el és nézd más szemszögből.',
        yearlyMeaning: 'A fordulópont éve. Mély belső átalakulás várható, ha képes vagy elengedni a régi mintákat.',
        questions: ['Mi az, amihez túl erősen ragaszkodsz?', 'Mit nyerhetsz, ha feladod az irányítást?'],
        affirmation: "Elengedem az irányítást és bízom a folyamatban.",
        imageUrl: 'https://myralog.hu/tarot/major-12.jpg',
        history: 'Eredetileg "Az áruló" néven is ismerték, akit a lábánál fogva akasztottak fel büntetésből (pittura infamante). A modern Tarotban azonban inkább Odin áldozatához hasonlítják, aki a tudásért függött a világfán.',
        symbolism: 'A fejénél lévő dicsfény mutatja, hogy ez nem büntetés, hanem megvilágosodás. A keresztbe tett lábai a 4-es számot formázzák (anyag), míg a feje és a karjai a háromszöget (szellem), ami az anyag feletti szellem győzelmét, vagy annak megfordítását jelzi.',
        shortDesc: 'A Nézőpontváltás'
    },
    {
        id: 'major-13', name: 'A Halál', nameEn: 'Death', arcana: 'Major', number: 13,
        element: 'Víz', astrology: 'Skorpió', numerology: '13',
        keywords: ['Befejezés', 'Átalakulás', 'Elengedés', 'Új kezdet', 'Újjászületés'],
        meaningUpright: 'Vége valaminek, átalakulás, elengedés, elkerülhetetlen változás, transzformáció.',
        meaningReversed: 'Ragaszkodás a múlthoz, félelem a változástól, elhúzódó gyász.',
        generalMeaning: 'A Halál a radikális változást és az elengedést szimbolizálja. Ritkán jelent fizikai halált; inkább egy korszak lezárását és egy új kezdetét.',
        loveMeaning: 'Egy életszakasz vagy kapcsolat végét jelentheti, de egy kapcsolat teljes megújulását is.',
        careerMeaning: 'Búcsút a régi munkahelytől vagy karriertől. Engedd el a régit, hogy jöhessen az új.',
        advice: 'Engedd el! Ne ragaszkodj ahhoz, ami már idejétmúlt. Tisztítsd meg az életedet.',
        dailyMeaning: 'Ma valami véget érhet. Zárd le a múltat békével.',
        yearlyMeaning: 'A nagy átalakulás éve. Fontos dolgokat fogsz lezárni, teljesen új emberré válhatsz.',
        questions: ['Mi az, aminek meg kell halnia az életedben, hogy te élhess?', 'Mitől félsz megszabadulni?'],
        affirmation: "Elengedem a régit, és bizalommal nyitok az új felé.",
        imageUrl: 'https://myralog.hu/tarot/major-13.jpg',
        history: 'A Haláltánc (Danse Macabre) középkori ábrázolásaiból ered, ahol a csontváz mindenkit elvisz, rangtól függetlenül. Ez a nagy kiegyenlítő.',
        symbolism: 'A csontváz a halhatatlan lényeget (ami megmarad a hús után) jelzi. A fekete páncél a legyőzhetetlenséget. A fehér ló a tisztaságot, a felkelő nap a háttérben (a két torony között) pedig a halhatatlanságot és az új reményt ígéri.',
        shortDesc: 'A Nagy Átalakulás'
    },
    {
        id: 'major-14', name: 'A Mértékletesség', nameEn: 'Temperance', arcana: 'Major', number: 14,
        element: 'Tűz', astrology: 'Nyilas', numerology: '14',
        keywords: ['Egyensúly', 'Mértékletesség', 'Türelem', 'Harmónia', 'Alkímia'],
        meaningUpright: 'Egyensúly, gyógyulás, türelem, harmónia, megfelelő mérték, ellentétek egyesítése.',
        meaningReversed: 'Egyensúlyhiány, túlzások, türelmetlenség, szélsőségek.',
        generalMeaning: 'A Mértékletesség a belső béke és a harmónia kártyája. Az alkímiai folyamatot jelzi, ahol a különböző összetevők új minőséggé olvadnak össze.',
        loveMeaning: 'Harmonikus, békés kapcsolatot jelez. A felek kiegészítik egymást.',
        careerMeaning: 'Kellemes, stresszmentes munkakörnyezetet jelent. Csapatmunka és együttműködés.',
        advice: 'Légy türelmes és mértéktartó! Keresd az arany középutat. Vegyítsd a dolgokat óvatosan.',
        dailyMeaning: 'Ma a harmónia és a nyugalom napja van. Gyógyítsd magad.',
        yearlyMeaning: 'A gyógyulás éve. Most megtalálhatod a belső békédet és egyensúlyodat.',
        questions: ['Életed mely területén van szükség több egyensúlyra?', 'Mivel estél túlzásba?'],
        affirmation: "Harmóniát teremtek testemben, lelkemben és szellememben.",
        imageUrl: 'https://myralog.hu/tarot/major-14.jpg',
        history: 'Szintén a négy sarkalatos erény egyike. A latin "temperare" szó jelentése: helyes arányban összekeverni.',
        symbolism: 'Az angyal (Mihály) egyik lába a vízen (tudatalatti), a másik a földön (valóság) áll, ami a stabilitást jelzi a változásban. A két kehely közötti folyadékáramlás az energiák cseréjét és az örök körforgást mutatja. A homlokán a Nap jele a megvilágosodást jelképezi.',
        shortDesc: 'Az Arany Középút'
    },
    {
        id: 'major-15', name: 'Az Ördög', nameEn: 'The Devil', arcana: 'Major', number: 15,
        element: 'Föld', astrology: 'Bak', numerology: '15',
        keywords: ['Függőség', 'Anyagiasság', 'Kötődés', 'Árnyék', 'Felszabadulás'],
        meaningUpright: 'Függőség, kísértés, anyagiasság, szexualitás, saját árnyékunk, rabság illúziója.',
        meaningReversed: 'Megszabadulás a láncoktól, felismerés, a függőség vége, szembenézés az igazsággal.',
        generalMeaning: 'Az Ördög a függőségeinket és félelmeinket jelképezi. Azt mutatja, hol vagyunk rabjai az anyagnak vagy a saját vágyainknak.',
        loveMeaning: 'Szenvedélyes, de gyakran egészségtelen kapcsolatot jelez. Féltékenység, birtoklási vágy.',
        careerMeaning: 'Tisztességtelen üzleteket, hatalomvágyat vagy rabszolgaság-érzést jelent a munkahelyen.',
        advice: 'Nézz szembe az árnyékoddal! Ismerd fel, hogy a láncok lazák, leveheted őket.',
        dailyMeaning: 'Ma kísértésbe eshetsz. Ne hagyd, hogy a félelem vagy a sóvárgás irányítson.',
        yearlyMeaning: 'Az árnyékmunka éve. Szembesülsz a sötét oldaladdal, de ez a felszabadulás útja.',
        questions: ['Mi az, ami rabságban tart?', 'Milyen hazugságot hiszel el magadról?'],
        affirmation: "Felismerem árnyékomat és a fény felé fordulok.",
        imageUrl: 'https://myralog.hu/tarot/major-15.jpg',
        history: 'A kártya Pánt, a természet görög istenét, vagy Baphometet ábrázolja. Gyakran a Szeretők kártya sötét párjának tekintik (itt is egy pár van, de láncra verve).',
        symbolism: 'A láncok a nyakukon lazák – bármikor levehetnék őket, de nem teszik. Ez az önként vállalt rabságot jelzi. A fordított pentagram a homlokon az anyag uralmát jelzi a szellem felett. A fáklya a pusztító tüzet és a szenvedélyt szimbolizálja.',
        shortDesc: 'A Kísértés és Láncok'
    },
    {
        id: 'major-16', name: 'A Torony', nameEn: 'The Tower', arcana: 'Major', number: 16,
        element: 'Tűz', astrology: 'Mars', numerology: '16',
        keywords: ['Hirtelen változás', 'Káosz', 'Felismerés', 'Összeomlás', 'Ébredés'],
        meaningUpright: 'Hirtelen változás, katasztrófa, összeomlás, megvilágosodás, a hamis struktúrák lerombolása.',
        meaningReversed: 'Félelem a változástól, elkerült katasztrófa, belső összeomlás, tagadás.',
        generalMeaning: 'A Torony a hirtelen, sokkoló változás kártyája. Bár fájdalmas, szükséges a tisztuláshoz, mert ami összedől, az nem volt stabil.',
        loveMeaning: 'Hirtelen szakítást vagy drámai felismerést jelez, ami alapjaiban rengeti meg a kapcsolatot.',
        careerMeaning: 'Váratlan felmondást, csődöt vagy projektösszeomlást jelenthet. Újra kell építkezni.',
        advice: 'Hagyd, hogy összeomoljon, ami nem stabil! Fogadd el a változást, ne állj ellen a viharnak.',
        dailyMeaning: 'Ma valami váratlan dolog történhet. Ne próbáld megfoltozni azt, ami menthetetlen.',
        yearlyMeaning: 'A felszabadulás éve. Ami ingatag volt, most ledől, hogy tiszta lappal indulhass.',
        questions: ['Mi az a hamis biztonság, amihez ragaszkodsz?', 'Mit kell lerombolni az újjáépítéshez?'],
        affirmation: "Bátran fogadom a változást, amely felszabadít.",
        imageUrl: 'https://myralog.hu/tarot/major-16.jpg',
        history: 'Gyakran a bibliai Bábel tornyához kötik, amit Isten villáma (isteni beavatkozás) pusztított el az emberi gőg miatt.',
        symbolism: 'A villám a hirtelen isteni beavatkozást vagy felismerést jelzi. A koronát (az ego uralmát) leveri a torony tetejéről. A zuhanó emberek a régi hitrendszerek és életmódok elhagyását mutatják. A lángok a tisztítótüzet jelképezik.',
        shortDesc: 'Az Összeomlás és Ébredés'
    },
    {
        id: 'major-17', name: 'A Csillag', nameEn: 'The Star', arcana: 'Major', number: 17,
        element: 'Levegő', astrology: 'Vízöntő', numerology: '17',
        keywords: ['Remény', 'Hit', 'Inspiráció', 'Gyógyulás', 'Cél'],
        meaningUpright: 'Remény, inspiráció, jövőkép, gyógyulás, spiritualitás, nyugalom a vihar után.',
        meaningReversed: 'Reménytelenség, hitetlenség, kiábrándultság, elszalasztott lehetőségek.',
        generalMeaning: 'A Csillag a remény és a jövőbe vetett hit kártyája. A Torony pusztítása után ő hozza el a gyógyulást és az új irányt.',
        loveMeaning: 'Ígéretes találkozást vagy inspiráló szerelmet jelez. Sebek gyógyulása.',
        careerMeaning: 'Olyan projektet jelez, aminek hosszú távon nagy jövője van. Művészi inspiráció.',
        advice: 'Bízz a jövőben! Ne add fel a reményt. Kövesd a vezércsillagodat.',
        dailyMeaning: 'Ma tele leszel optimizmussal. Higgy a jóban és légy hálás.',
        yearlyMeaning: 'A remény és a tervezés éve. Most vetehetsz el magokat, amik később szárba szökkennek.',
        questions: ['Mi a legmerészebb álmod a jövőre nézve?', 'Miben hiszel?'],
        affirmation: "Bízom az Univerzumban és követem a belső fényemet.",
        imageUrl: 'https://myralog.hu/tarot/major-17.jpg',
        history: 'A Csillag az asztronómiai tudást és a kozmikus rendet jelképezi. Gyakran Szíriusszal vagy a Vénusszal azonosítják.',
        symbolism: 'A meztelen nőalak a teljes őszinteséget és tisztaságot jelzi. Két korsóból önt vizet: egyet a tóba (tudatalatti), egyet a földre (anyagi világ), ezzel táplálva mindkettőt. A nagy csillag körül hét kisebb csillag ragyog, a csakrákat jelképezve.',
        shortDesc: 'A Remény Fénye'
    },
    {
        id: 'major-18', name: 'A Hold', nameEn: 'The Moon', arcana: 'Major', number: 18,
        element: 'Víz', astrology: 'Halak', numerology: '18',
        keywords: ['Illúzió', 'Félelem', 'Tudatalatti', 'Intuíció', 'Misztikum'],
        meaningUpright: 'Illúzió, félelem, bizonytalanság, álmok, tudatalatti, csalódás veszélye.',
        meaningReversed: 'Félelmek feloldása, tisztánlátás, a köd felszállása.',
        generalMeaning: 'A Hold a sötétség és a tudatalatti birodalmába vezet. A dolgok nem azok, aminek látszanak. Az intuíció éles, de a félelem torzíthat.',
        loveMeaning: 'Bizonytalanságot vagy féltékenységet jelez. Lehetnek titkok vagy illúziók a kapcsolatban.',
        careerMeaning: 'Félelem a kudarctól. Nem látod tisztán a viszonyokat, légy óvatos a szerződésekkel.',
        advice: 'Ne félj a sötéttől, de légy óvatos! Hallgass az álmaidra, de ne higgy el mindent a szemednek.',
        dailyMeaning: 'Ma bizonytalan lehetsz. Ne hozz fontos döntést, inkább álmodozz.',
        yearlyMeaning: 'A próbatétel éve. Szembe kell nézned a félelmeiddel, hogy megtaláld az utat.',
        questions: ['Milyen félelmek tartanak vissza az igazságtól?', 'Mit súg az ösztönöd?'],
        affirmation: "Bátran szembenézek a félelmeimmel és bízom a megérzéseimben.",
        imageUrl: 'https://myralog.hu/tarot/major-18.jpg',
        history: 'A Hold a Tarot legpszichedelikusabb kártyája, az éjszakai utazást szimbolizálja.',
        symbolism: 'A rák, ami kimászik a vízből, a tudatalattiból ébredő tudatot jelenti. A kutya és a farkas a megszelídített és a vad ösztönöket jelképezi. A két torony a kapu a tudatlanba. A Hold arca nyugtalanító, utalva a változékonyságra.',
        shortDesc: 'Az Illúziók Világa'
    },
    {
        id: 'major-19', name: 'A Nap', nameEn: 'The Sun', arcana: 'Major', number: 19,
        element: 'Tűz', astrology: 'Nap', numerology: '19',
        keywords: ['Öröm', 'Siker', 'Vitalitás', 'Pozitivitás', 'Boldogság'],
        meaningUpright: 'Öröm, siker, optimizmus, vitalitás, tisztánlátás, boldogság, ártatlanság.',
        meaningReversed: 'Időleges ború, késleltetett siker, kiégés vagy túlzott optimizmus.',
        generalMeaning: 'A Nap az életörömöt és a sikert jelképezi. Minden világossá és egyszerűvé válik. A legjobb kártya a pakliban.',
        loveMeaning: 'Felhőtlen boldogságot és melegséget jelent. Házasság, boldog családi élet.',
        careerMeaning: 'Sikert, elismerést és önmegvalósítást jelez. Kreatív kibontakozás.',
        advice: 'Légy optimista és sugározz! Oszd meg az örömödet másokkal. Mutasd meg magad.',
        dailyMeaning: 'Ma csodálatos napod lesz. Élvezd az életet és a napfényt.',
        yearlyMeaning: 'A napfény éve. Sikeres és energikus időszak vár rád, minden sikerülhet.',
        questions: ['Mi okoz neked tiszta, gyermeki örömöt?', 'Hogyan ragyoghatnál még fényesebben?'],
        affirmation: "Élvezem az életet és sugárzom a boldogságot.",
        imageUrl: 'https://myralog.hu/tarot/major-19.jpg',
        history: 'A Nap istenségeket (pl. Apollón, Héliosz) idézi, akik a fényt és az igazságot hozzák el.',
        symbolism: 'A gyermek a fehér lovon az újjászületett lelket és az ártatlanságot jelképezi. A napraforgók az életigenlést. A fal mögöttük azt mutatja, hogy magunk mögött hagytuk a nehézségeket. A Nap arca derűs és közvetlen.',
        shortDesc: 'A Ragyogó Siker'
    },
    {
        id: 'major-20', name: 'A Feltámadás', nameEn: 'Judgement', arcana: 'Major', number: 20,
        element: 'Tűz', astrology: 'Plútó', numerology: '20',
        keywords: ['Újjászületés', 'Hívás', 'Megbocsátás', 'Ébredés', 'Felismerés'],
        meaningUpright: 'Megváltás, újjászületés, hívó szó, megszabadulás, ítélet, ébredés a mély álomból.',
        meaningReversed: 'Kétségbeesés, ragaszkodás a rabsághoz, a hívás elutasítása, önvád.',
        generalMeaning: 'A Feltámadás a megszabadulást és a gyógyulást jelenti. Egy régi életszakasz végleg lezárul, és egy magasabb szintre lépsz.',
        loveMeaning: 'A kapcsolat "feltámadását" vagy új szintre lépését jelentheti. Régi sebek begyógyulása.',
        careerMeaning: 'Megtalálod az igazi hivatásodat. Felszabadító változás, esetleg visszatérés egy régi álomhoz.',
        advice: 'Kövesd a hívást! Emelkedj felül a kicsinyes gondokon. Bocsáss meg.',
        dailyMeaning: 'Ma megoldódhat egy régi problémád. Halld meg a belső hangodat.',
        yearlyMeaning: 'A kincskeresés éve. Megtalálod, amit régóta kerestél, és újjászületsz.',
        questions: ['Mire hív most az élet?', 'Mit kell megbocsátanod magadnak?'],
        affirmation: "Megbocsátok magamnak és másoknak, és szabadon élek.",
        imageUrl: 'https://myralog.hu/tarot/major-20.jpg',
        history: 'A bibliai Végítéletet ábrázolja, de a Tarotban ez nem a büntetést, hanem a felszabadulást jelenti.',
        symbolism: 'Gábriel arkangyal harsonája ébreszti a holtakat (a szunnyadó tudatot). A sírokból felkelő emberek (férfi, nő, gyermek) az egységet és az újjászületést jelképezik. A víz a koporsók körül a tudatalatti tisztító ereje.',
        shortDesc: 'A Végső Ébredés'
    },
    {
        id: 'major-21', name: 'A Világ', nameEn: 'The World', arcana: 'Major', number: 21,
        element: 'Föld', astrology: 'Szaturnusz', numerology: '21',
        keywords: ['Beteljesülés', 'Egység', 'Utazás', 'Siker', 'Teljesség'],
        meaningUpright: 'Beteljesülés, célba érés, teljesség, világegyetem, utazás, a ciklus vége.',
        meaningReversed: 'Befejezetlenség, késlekedés, hiányérzet, az utolsó lépés hiánya.',
        generalMeaning: 'A Világ a célba érést és a boldog befejezést jelenti. Megtaláltad a helyedet a világban. Minden egyben van.',
        loveMeaning: 'A "megérkezés" érzése a kapcsolatban. Teljes az életed. Házasság, boldog befejezés.',
        careerMeaning: 'Elérted a célodat. Sikeresen befejeztél egy projektet. Nemzetközi lehetőségek.',
        advice: 'Élvezd a sikert! Ismerd fel, hogy minden a helyén van. Ünnepelj.',
        dailyMeaning: 'Ma minden kerek egész. Örülj a sikereidnek és érezd az egységet.',
        yearlyMeaning: 'A beteljesülés éve. Boldogság és elégedettség vár. Egy nagy ciklus lezárul.',
        questions: ['Mi az, ami teljessé teszi az életedet?', 'Hogyan ünnepled a sikereidet?'],
        affirmation: "Egy vagyok a világgal, és a világ egy velem.",
        imageUrl: 'https://myralog.hu/tarot/major-21.jpg',
        history: 'A mandorlában (mandula alakú dicsfényben) táncoló alak a kozmikus táncot járja. A Bolond útja itt ér véget.',
        symbolism: 'A négy sarokban lévő kerubok (ugyanazok, mint a Szerencsekeréknél) most már készen vannak, a teljességet őrzik. A táncoló nőalak egyesíti a férfi és női energiákat. A koszorú a végtelenséget és a sikert jelzi.',
        shortDesc: 'A Kozmikus Tánc'
    }
];
