
import { Card } from '../types';

export const SWORDS: Card[] = [
    {
        id: 'swords-1', name: 'Kardok Ásza', nameEn: 'Ace of Swords', arcana: 'Minor', suit: 'Kardok', number: 1,
        element: 'Levegő', astrology: 'Levegő elem gyökere (Ikrek/Mérleg/Vízöntő)', numerology: '1',
        keywords: ['Tisztánlátás', 'Áttörés', 'Igazság', 'Mentális erő', 'Új ötlet'],
        meaningUpright: 'Tisztánlátás, áttörés, igazság feltárulása, siker, diadal.',
        meaningReversed: 'Túlzott elemzés, elhomályosult ítélőképesség.',
        generalMeaning: 'A szellemi tisztánlátás és a határozott döntés erejének szimbóluma.',
        loveMeaning: 'Tiszta vizet öntünk a pohárba. Józan döntés a kapcsolatról.',
        careerMeaning: 'Ragyogó ötletet és analitikus képességet jelez.',
        advice: 'Tisztázd a helyzetet! Dönts ésszerűen és határozottan.',
        dailyMeaning: 'Ma megoldást találsz egy régi problémára. Légy tárgyilagos.',
        yearlyMeaning: 'A tisztánlátás éve. Sok régi probléma megoldódik.',
        questions: ['Életének mely területein homályosítja el saját világosságát?', 'Mit fogsz tenni, hogy leföldeld a nagy ötleteidet?'],
        affirmation: "A tisztánlátás ragyogó pillanatait élem meg.",
        imageUrl: 'https://myralog.hu/tarot/swords-1.jpg',
        shortDesc: 'A Mentális Kard',
        comparison: {
            title: 'Kardok Ásza vs. Kardok Kettes',
            text: 'Míg az Ász a tiszta igazság és az áttörés pillanata, a Kettes a döntésképtelenséget és az igazsággal való szembenézés halogatását mutatja. Az Ász vág, a Kettes megállít.',
            relatedCardId: 'swords-2'
        }
    },
    {
        id: 'swords-2', name: 'Kardok Kettes', nameEn: '2 of Swords', arcana: 'Minor', suit: 'Kardok', number: 2,
        element: 'Levegő', astrology: 'Hold a Mérlegben', numerology: '2',
        keywords: ['Döntésképtelenség', 'Patthelyzet', 'Blokk', 'Válaszút', 'Dilemma'],
        meaningUpright: 'Patthelyzet, nehéz választás, cselekvésképtelenség.',
        meaningReversed: 'Döntés nehézsége, ismeretlen szorongása.',
        generalMeaning: 'A kétség és az érzelmek elfojtásának kártyája. Bénultság.',
        loveMeaning: 'Kétségek a kapcsolatban. Elzárkózás a párunk elől.',
        careerMeaning: 'Patthelyzet. Halogatott állásfoglalás, taktikai kivárás.',
        advice: 'Hallgass a belső hangodra! Nézz szembe a tényekkel.',
        dailyMeaning: 'Ma kétségek gyötörhetnek. Ne erőltesd a döntést.',
        yearlyMeaning: 'A kétségek éve. Tanulj meg hallgatni az intuíciódra.',
        questions: ['Ragadtát két egyformán nehéz dolog közé?', 'Bízol magadban, amikor az intuíciód offline?'],
        affirmation: "Bízom magamban, hogy megtalálom a fényt.",
        imageUrl: 'https://myralog.hu/tarot/swords-2.jpg'
    },
    {
        id: 'swords-3', name: 'Kardok Hármas', nameEn: '3 of Swords', arcana: 'Minor', suit: 'Kardok', number: 3,
        element: 'Levegő', astrology: 'Szaturnusz a Mérlegben', numerology: '3',
        keywords: ['Szívfájdalom', 'Szomorúság', 'Veszteség', 'Gyász', 'Megtört szív'],
        meaningUpright: 'Fájdalmas elválás, szívfájdalom, gyógyulás lehetősége.',
        meaningReversed: 'Veszteség el nem fogadása, elakadt bánat.',
        generalMeaning: 'A szívfájdalom és a csalódás kártyája. Fájdalmas felismerés.',
        loveMeaning: 'Szerelmi bánat, csalódás, megbántottság. Hűtlenség gyanúja.',
        careerMeaning: 'Szakmailag helyes, de emberileg nehéz döntések.',
        advice: 'Végezd el a fájdalmas vágást! Ne nyomd el az érzéseidet.',
        dailyMeaning: 'Ma valami megsértheti az érzéseidet. Légy erős.',
        yearlyMeaning: 'A fájdalmas felismerések éve. Megszabadulsz az illúzióktól.',
        questions: ['Hogyan vezeted le ezeket az érzelmeket?', 'Hogyan maradsz nyitott a sebek gyógyulása közben?'],
        affirmation: "Szívem továbbra is gyengéd és nyitott.",
        imageUrl: 'https://myralog.hu/tarot/swords-3.jpg'
    },
    {
        id: 'swords-4', name: 'Kardok Négyes', nameEn: '4 of Swords', arcana: 'Minor', suit: 'Kardok', number: 4,
        element: 'Levegő', astrology: 'Jupiter a Mérlegben', numerology: '4',
        keywords: ['Pihenés', 'Felépülés', 'Meditáció', 'Visszavonulás', 'Gyógyulás'],
        meaningUpright: 'Mély pihenés ideje, kiégés elkerülése, gyógyulás, önszeretet.',
        meaningReversed: 'Pangás veszélye, halogatott öngondoskodás.',
        generalMeaning: 'A kényszerpihenő és a regenerálódás kártyája. Szünet kell.',
        loveMeaning: 'Csend vagy stagnálás a kapcsolatban. "Időkérés" szükséges.',
        careerMeaning: 'Kimerültség, stressz. Lassíts a tempón, tarts szünetet.',
        advice: 'Pihenj meg! Gyűjts erőt a passzivitás által.',
        dailyMeaning: 'Ma engedélyezz magadnak egy kis pihenőt.',
        yearlyMeaning: 'A regenerálódás éve. Ez az időszak kell a későbbi aktivitáshoz.',
        questions: ['Mit kell meggyógyítani?', 'Eleget nevetsz mostanában?'],
        affirmation: "Engedélyt adok magamnak, hogy lelassuljak és gyógyuljak.",
        imageUrl: 'https://myralog.hu/tarot/swords-4.jpg'
    },
    {
        id: 'swords-5', name: 'Kardok Ötös', nameEn: '5 of Swords', arcana: 'Minor', suit: 'Kardok', number: 5,
        element: 'Levegő', astrology: 'Vénusz a Vízöntőben', numerology: '5',
        keywords: ['Konfliktus', 'Vereség', 'Önzés', 'Feszültség', 'Veszteség'],
        meaningUpright: 'Konfliktus, tisztességtelen előny, veszteség.',
        meaningReversed: 'Mindenáron nyerni akarás, álnok stratégiák.',
        generalMeaning: 'A vereség és az aljasság kártyája. Romboló konfliktus.',
        loveMeaning: 'Kegyetlen viták, megalázás. A harc tönkreteszi a feleket.',
        careerMeaning: 'Rágalmazás, tisztességtelen verseny. Valaki áskálódik.',
        advice: 'Ne menj bele a harcba, mert csak veszíthetsz!',
        dailyMeaning: 'Ma provokálhatnak. Kerüld a konfliktust.',
        yearlyMeaning: 'A konfliktusok éve. Vigyázz, kiben bízol.',
        questions: ['Tisztességesen nyerted el a helyedet?', 'Milyen leckéket tanultál a legyőzetésből?'],
        affirmation: "A leckéim előre visznek - mindig.",
        imageUrl: 'https://myralog.hu/tarot/swords-5.jpg'
    },
    {
        id: 'swords-6', name: 'Kardok Hatos', nameEn: '6 of Swords', arcana: 'Minor', suit: 'Kardok', number: 6,
        element: 'Levegő', astrology: 'Merkúr a Vízöntőben', numerology: '6',
        keywords: ['Átmenet', 'Továbblépés', 'Gyógyulás', 'Utazás', 'Változás'],
        meaningUpright: 'Átmenet rítusa, gyógyulás, túllépés a traumán, támogatás.',
        meaningReversed: 'Segítség elfogadásának nehézsége, ellenállás a változásnak.',
        generalMeaning: 'Az új partok keresésének kártyája. Elhagyjuk a megszokottat.',
        loveMeaning: 'Új szakasz. Együtt indulunk új utakra vagy kilépünk a régiből.',
        careerMeaning: 'Munkahelyváltás. Bizonytalan az új, de a régi már tarthatatlan.',
        advice: 'Indulj el! Bár félsz, a maradás nem opció.',
        dailyMeaning: 'Ma elindulhat valami új. Ne félj a változástól.',
        yearlyMeaning: 'A nagy utazás éve. Kimozdulsz a komfortzónádból.',
        questions: ['Tudsz segítséget kérni?', 'Hová költözöl lelkileg?'],
        affirmation: "Elfogadom a segítséget, hogy könnyedén átjussak.",
        imageUrl: 'https://myralog.hu/tarot/swords-6.jpg'
    },
    {
        id: 'swords-7', name: 'Kardok Hetes', nameEn: '7 of Swords', arcana: 'Minor', suit: 'Kardok', number: 7,
        element: 'Levegő', astrology: 'Hold a Vízöntőben', numerology: '7',
        keywords: ['Stratégia', 'Megtévesztés', 'Taktika', 'Titkok', 'Ravaszság'],
        meaningUpright: 'Csalás, stratégiai elvétel, megúszni valamit, csendben mozgás.',
        meaningReversed: 'Hazugság magadnak, őszinteség igénye, titkok.',
        generalMeaning: 'A csalárdság és a kibúvók kártyája. Valaki nem játszik nyílt lapokkal.',
        loveMeaning: 'Őszintétlenség, titkolózás, konfrontáció kerülése.',
        careerMeaning: 'Intrika, csalás. Te vagy valaki más megússza a felelősséget.',
        advice: 'Légy éber! Ne higgy el mindent, ne trükközz.',
        dailyMeaning: 'Ma valaki megpróbálhat átverni. Légy résen.',
        yearlyMeaning: 'Az óvatosság éve. Sok hamissággal találkozhatsz.',
        questions: ['Mennyire igazodnak a szándékaid és tetteid?', 'Mások félreolvassák a tetteidet?'],
        affirmation: "A szeretet helyéről cselekszem.",
        imageUrl: 'https://myralog.hu/tarot/swords-7.jpg'
    },
    {
        id: 'swords-8', name: 'Kardok Nyolcas', nameEn: '8 of Swords', arcana: 'Minor', suit: 'Kardok', number: 8,
        element: 'Levegő', astrology: 'Jupiter az Ikrekben', numerology: '8',
        keywords: ['Korlátozás', 'Félelem', 'Csapda', 'Tehetetlenség', 'Börtön'],
        meaningUpright: 'Elakadt érzés, ideje kinyitni a szemét, régi történet elengedése.',
        meaningReversed: 'Áldozattá válás, tehetetlenség, megtagadás.',
        generalMeaning: 'A belső akadályok kártyája. A rácsok csak a fejünkben léteznek.',
        loveMeaning: 'Gátlásosság, félelem a nyitástól. Úy érzed, a kapcsolat börtön.',
        careerMeaning: 'Nem mersz váltani a bizonytalanságtól való félelem miatt.',
        advice: 'Szabadítsd fel magad! A korlátok többsége illúzió.',
        dailyMeaning: 'Ma akadályokba ütközhetsz. Ne hagyd, hogy megbénítsanak.',
        yearlyMeaning: 'A belső korlátok éve. Szembe kell nézned a gátlásaiddal.',
        questions: ['Életed mely területein érzed, hogy meg vagy kötve?', 'Milyen történetek tartanak vissza?'],
        affirmation: "Szabadon dönthetek a fényem mellett.",
        imageUrl: 'https://myralog.hu/tarot/swords-8.jpg'
    },
    {
        id: 'swords-9', name: 'Kardok Kilences', nameEn: '9 of Swords', arcana: 'Minor', suit: 'Kardok', number: 9,
        element: 'Levegő', astrology: 'Mars az Ikrekben', numerology: '9',
        keywords: ['Szorongás', 'Rémálmok', 'Aggodalom', 'Félelem', 'Álmatlanság'],
        meaningUpright: 'Rémálmok, aggódás, depresszió, álmatlanság, félelem.',
        meaningReversed: 'Paranoia, belső zűrzavar, gyógyító út keresése.',
        generalMeaning: 'A bűntudat és szorongás kártyája. Sötétnek látod a jövőt.',
        loveMeaning: 'Félelem az elhagyatástól, bűntudat a partnerrel szemben.',
        careerMeaning: 'Vizsgadrukk, kudarctól való félelem. Stressz csúcspontja.',
        advice: 'Nézz szembe a félelmeiddel! Kapcsold fel a villanyt.',
        dailyMeaning: 'Ma rossz kedved lehet. A dolgok nem olyan sötétek, mint hiszed.',
        yearlyMeaning: 'A rémálmok éve. Meg kell tisztulnod a bűntudattól.',
        questions: ['Milyen félelmek tartanak vissza?', 'Hogyan aktiválod a fényedet a sötétben?'],
        affirmation: "A félelmeimet illúzióként látom.",
        imageUrl: 'https://myralog.hu/tarot/swords-9.jpg'
    },
    {
        id: 'swords-10', name: 'Kardok Tizes', nameEn: '10 of Swords', arcana: 'Minor', suit: 'Kardok', number: 10,
        element: 'Levegő', astrology: 'Nap az Ikrekben', numerology: '10',
        keywords: ['Befejezés', 'Fájdalom', 'Új kezdet', 'Mélypont', 'Válság'],
        meaningUpright: 'Fájdalmas befejezés, válság, hátba szúrás, mély gyógyulás szükségessége.',
        meaningReversed: 'Kudarcok elutasítása, ellenállás a változásnak, mélypont.',
        generalMeaning: 'A drasztikus befejezés kártyája. Húzz egy vonalat.',
        loveMeaning: 'Szakítás, a kapcsolat hirtelen vége. Fájdalmas összeomlás.',
        careerMeaning: 'Felmondás, a cég csődje. Radikális váltás a karrierben.',
        advice: 'Zárd le! Ne nézz vissza, a mélypont után csak felfelé vezet az út.',
        dailyMeaning: 'Ma valami véget érhet. Szükséges a továbblépéshez.',
        yearlyMeaning: 'A lezárás éve. Valamit végleg magad mögött hagysz.',
        questions: ['Mit tanultál a kihívásaidon keresztül?', 'Mennyire bízol másokban?'],
        affirmation: "Gyógyulok, minden nap.",
        imageUrl: 'https://myralog.hu/tarot/swords-10.jpg'
    },
    {
        id: 'swords-page', name: 'Kardok Apródja', nameEn: 'Page of Swords', arcana: 'Minor', suit: 'Kardok', number: 11,
        element: 'Levegő', astrology: 'Levegő elem földi aspektusa', numerology: '11',
        keywords: ['Kíváncsiság', 'Ötletek', 'Kommunikáció', 'Igazság', 'Tanulás'],
        meaningUpright: 'Nyugtalan energia, információszomj, új dolgok tanulása, hírnök.',
        meaningReversed: 'Pletykák, megszegett ígéretek, intellektualizált érzelmek.',
        generalMeaning: 'Tisztázó esély, vita vagy kritika, ami kívülről jön.',
        loveMeaning: 'Konfliktushelyzet a kapcsolatban, piszkálódás.',
        careerMeaning: 'Kritika, vita kollégákkal. Ébernek kell maradni.',
        advice: 'Légy éber és kritikus! Használd az eszedet.',
        dailyMeaning: 'Ma kritikát kaphatsz. Kezeld higgadtan.',
        yearlyMeaning: 'A viták és a tisztázás éve. Segítenek tisztábban látni.',
        questions: ['Hogyan használod a szavaidat?', 'Miről szeretnél többet megtudni?'],
        affirmation: "Kitágítom a tudásomat, és új lehetőségeket nyitok.",
        imageUrl: 'https://myralog.hu/tarot/swords-page.jpg'
    },
    {
        id: 'swords-knight', name: 'Kardok Lovagja', nameEn: 'Knight of Swords', arcana: 'Minor', suit: 'Kardok', number: 12,
        element: 'Levegő', astrology: 'Levegő elem levegő aspektusa', numerology: '12',
        keywords: ['Ambíció', 'Cselekvés', 'Impulzivitás', 'Gyorsaság', 'Intelligencia'],
        meaningUpright: 'Gyors cselekvés, szellemesség, elszántság, törekvés a kiválóságra.',
        meaningReversed: 'Szétszórt energia, türelmetlenség, érzelmi elérhetetlenség.',
        generalMeaning: 'A hideg elme és a kíméletlen őszinteség jelképe.',
        loveMeaning: 'Hidegfront. Viták, szarkazmus, harc a kapcsolatban.',
        careerMeaning: 'Kíméletlen verseny, éles viták. Gyors döntések.',
        advice: 'Őrizd meg a hidegvéredet! Ne hagyd, hogy az indulat elragadjon.',
        dailyMeaning: 'Ma feszült lehet a légkör. Védd meg magad.',
        yearlyMeaning: 'A harc éve. Szükséged lesz az éles eszedre.',
        questions: ['Mi a legnagyobb célod jelenleg?', 'Hogyan válhatnál saját hősöddé?'],
        affirmation: "Gyorsan kiterjesztem a sikeremet.",
        imageUrl: 'https://myralog.hu/tarot/swords-knight.jpg'
    },
    {
        id: 'swords-queen', name: 'Kardok Királynője', nameEn: 'Queen of Swords', arcana: 'Minor', suit: 'Kardok', number: 13,
        element: 'Levegő', astrology: 'Levegő elem vizes aspektusa', numerology: '13',
        keywords: ['Függetlenség', 'Észlelés', 'Objektivitás', 'Világosság', 'Kommunikáció'],
        meaningUpright: 'Tanácsadó, függetlenség, bölcs tanács, igazság keresése.',
        meaningReversed: 'Éles és hideg kommunikáció, elzárkózás.',
        generalMeaning: 'Az intellektus és a függetlenség női oldala.',
        loveMeaning: 'Egyenrangú, intellektuális kapcsolat. Szabadságvágy.',
        careerMeaning: 'Stratégiai gondolkodás, jó kommunikáció, független munka.',
        advice: 'Légy független és tárgyilagos! Mondd ki, amit gondolsz.',
        dailyMeaning: 'Ma légy okos és megfontolt. Ne dönts érzelemből.',
        yearlyMeaning: 'A függetlenség éve. Megtanulod a saját lábadon állni.',
        questions: ['Milyen igazságot kell kimondani?', 'Igényled mások jóváhagyását?'],
        affirmation: "Bölcsességgel és tisztánlátással szólok.",
        imageUrl: 'https://myralog.hu/tarot/swords-queen.jpg'
    },
    {
        id: 'swords-king', name: 'Kardok Királya', nameEn: 'King of Swords', arcana: 'Minor', suit: 'Kardok', number: 14,
        element: 'Levegő', astrology: 'Levegő elem tüzes aspektusa', numerology: '14',
        keywords: ['Szellemi erő', 'Tekintély', 'Igazság', 'Etika', 'Logika'],
        meaningUpright: 'Tisztán gondolkodó, erős vezető, szellemiség, bátorság.',
        meaningReversed: 'Zárkózottság, manipuláció, kontrollmánia.',
        generalMeaning: 'Az éles elme és a stratégia férfi oldala.',
        loveMeaning: 'Józanság és tisztázott viszonyok. Kevés romantika.',
        careerMeaning: 'Szakértő, elemző vagy vezető. Éles elméjű tárgyaló.',
        advice: 'Elemezz hideg fejjel! A logika vezet a megoldáshoz.',
        dailyMeaning: 'Ma neked kell okos döntést hoznod.',
        yearlyMeaning: 'A stratégia éve. Ha ésszerűen tervezel, sikeres leszel.',
        questions: ['Mi a helyzet igazsága?', 'Hová vezetnek a lehetőségeid 3 év múlva?'],
        affirmation: "Bölcsen használom egyedi intelligenciámat.",
        imageUrl: 'https://myralog.hu/tarot/swords-king.jpg'
    }
];
