
export const UI_TEXTS = {
  common: {
    loading: "Loading...",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    back: "Back",
    next: "Next",
    finish: "Finish",
    search: "Search...",
    filter: "Filter",
    close: "Close",
    language: "Language",
    theme: "Theme",
    profile: "Profile",
    logout: "Log out",
    login: "Log in",
    error: "An error occurred",
    success: "Success"
  },
  roles: {
    admin: "Administrator",
    moderator: "Moderator",
    translator: "Translator",
    member: "Member",
    guest: "Guest"
  },
  nav: {
    home: "Home",
    readings: "Readings",
    library: "Library",
    community: "Community",
    shop: "Shop",
    analysis: "Analysis"
  },
  app: {
    title: 'Arcanum',
  },
  auth: {
    login: 'Login',
    register: 'Register',
    name: 'Name',
    welcome: 'Welcome to Arcanum: Mirror of the Soul',
  },
  menu: {
    dashboard: 'Dashboard',
    history: 'Journal',
    library: 'Library',
    stats: 'Statistics',
    deckbuilder: 'Deck Builder',
    profile: 'Profile',
  },
  stats: {
    total_readings: 'Total Readings',
    balance: 'Elemental Balance',
    fire: 'Fire',
    water: 'Water',
    air: 'Air',
    earth: 'Earth',
    major: 'Major Arcana',
    minor: 'Minor Arcana',
  },
  dashboard: {
    greeting: 'Hello',
    sun: 'Sun Sign',
    moon: 'Moon Sign',
    ascendant: 'Ascendant',
    phase: 'Moon Phase',
    sunrise: 'Sunrise/Set',
    moonrise: 'Moonrise/Set',
    planet_hour: 'Planetary Hour',
    choose_spread: 'Choose a Spread',
    start: 'Start',
    cards: 'Cards',
    day_reading: 'Log Daily Draw',
    edit: 'Edit',
    share: 'Share',
    delete: 'Delete',
    no_reading_day: 'The cards of fate remained hidden on this day.',
  },
  actions: {
    community: 'Community',
    custom: 'New Spread',
    quiz: 'Quiz',
    deck: 'Deck Builder',
    stats: 'Analytics',
  },
  profile: {
    back: 'Back to Dashboard',
    level_seer: 'Level Seer',
    xp: 'Experience',
    badges: 'Badges',
    tab_details: 'Profile',
    tab_settings: 'Settings',
    tab_users: 'Accounts',
    natal_chart: 'Natal Chart (Estimated)',
    birth_card: 'Birth Card',
    personal_data: 'Personal Data & Astrology',
    display_name: 'Display Name',
    birth_date: 'Birth Date',
    birth_time: 'Birth Time',
    language: 'Language',
    deck_theme: 'Deck Theme',
    card_back: 'Card Back',
    avatar: 'Choose Avatar',
    theme: 'Choose Theme',
    data_mgmt: 'Data Management',
    export: 'Save to File',
    import: 'Load File',
    logout: 'Logout',
    who_reading: 'Who is reading the cards?',
    new_seer: 'New Seer',
    create_profile: 'Create New Profile',
    create: 'Create',
    saved: 'Data saved successfully!',
  },
  reading: {
    back: 'Back',
    shuffle: 'Shuffle',
    public: 'Public',
    private: 'Private',
    save: 'Save',
    question_label: 'Your Question to the Universe',
    question_placeholder: 'What do you seek answers for?',
    message: 'The Message',
    print: 'Print / PDF',
    public_success: 'Spread published successfully!',
    error: 'An error occurred.',
  }
};
