
export const UI_TEXTS = {
  common: {
    loading: "Laden...",
    save: "Speichern",
    cancel: "Abbrechen",
    delete: "Löschen",
    edit: "Bearbeiten",
    back: "Zurück",
    next: "Weiter",
    finish: "Fertig",
    search: "Suchen...",
    filter: "Filter",
    close: "Schließen",
    language: "Sprache",
    theme: "Thema",
    profile: "Profil",
    logout: "Abmelden",
    login: "Anmelden",
    error: "Ein Fehler ist aufgetreten",
    success: "Erfolg"
  },
  roles: {
    admin: "Administrator",
    moderator: "Moderator",
    translator: "Übersetzer",
    member: "Mitglied",
    guest: "Gast"
  },
  nav: {
    home: "Startseite",
    readings: "Lesungen",
    library: "Bibliothek",
    community: "Gemeinschaft",
    shop: "Laden",
    analysis: "Analyse"
  },
  app: {
    title: 'Arcanum',
  },
  auth: {
    login: 'Anmelden',
    register: 'Registrieren',
    name: 'Name',
    welcome: 'Willkommen bei Arcanum: Spiegel der Seele',
  },
  menu: {
    dashboard: 'Startseite',
    history: 'Tagebuch',
    library: 'Bibliothek',
    stats: 'Statistiken',
    deckbuilder: 'Deck Builder',
    profile: 'Profil',
  },
  stats: {
    total_readings: 'Lesungen insgesamt',
    balance: 'Elementare Balance',
    fire: 'Feuer',
    water: 'Wasser',
    air: 'Luft',
    earth: 'Erde',
    major: 'Große Arkana',
    minor: 'Kleine Arkana',
  },
  dashboard: {
    greeting: 'Hallo',
    sun: 'Sonnenzeichen',
    moon: 'Mondzeichen',
    ascendant: 'Aszendent',
    phase: 'Mondphase',
    sunrise: 'Sonnenaufgang/untergang',
    moonrise: 'Mondaufgang/untergang',
    planet_hour: 'Planetenstunde',
    choose_spread: 'Legesystem wählen',
    start: 'Start',
    cards: 'Karten',
    day_reading: 'Tageskarte ziehen',
    edit: 'Bearbeiten',
    share: 'Teilen',
    delete: 'Löschen',
    no_reading_day: 'Die Schicksalskarten blieben an diesem Tag verborgen.',
  },
  actions: {
    community: 'Gemeinschaft',
    custom: 'Neues Legesystem',
    quiz: 'Quiz',
    deck: 'Deck Builder',
    stats: 'Analyse',
  },
  profile: {
    back: 'Zurück zur Startseite',
    level_seer: 'Stufe Seher',
    xp: 'Erfahrung',
    badges: 'Abzeichen',
    tab_details: 'Profil',
    tab_settings: 'Einstellungen',
    tab_users: 'Konten',
    natal_chart: 'Geburtshoroskop (Geschätzt)',
    birth_card: 'Geburtskarte',
    personal_data: 'Persönliche Daten & Astrologie',
    display_name: 'Anzeigename',
    birth_date: 'Geburtsdatum',
    birth_time: 'Geburtszeit',
    language: 'Sprache / Language',
    deck_theme: 'Deck-Thema',
    card_back: 'Kartenrückseite',
    avatar: 'Avatar wählen',
    theme: 'Thema wählen',
    data_mgmt: 'Datenverwaltung',
    export: 'In Datei speichern',
    import: 'Datei laden',
    logout: 'Abmelden',
    who_reading: 'Wer liest die Karten?',
    new_seer: 'Neuer Seher',
    create_profile: 'Neues Profil erstellen',
    create: 'Erstellen',
    saved: 'Daten erfolgreich gespeichert!',
  },
  reading: {
    back: 'Zurück',
    shuffle: 'Mischen',
    public: 'Öffentlich',
    private: 'Privat',
    save: 'Speichern',
    question_label: 'Deine Frage an das Universum',
    question_placeholder: 'Worauf suchst du eine Antwort?',
    message: 'Die Nachricht',
    print: 'Drucken / PDF',
    public_success: 'Legung erfolgreich veröffentlicht!',
    error: 'Ein Fehler ist aufgetreten.',
  }
};
