
export const UI_TEXTS = {
  common: {
    loading: "Betöltés...",
    save: "Mentés",
    cancel: "Mégse",
    delete: "Törlés",
    edit: "Szerkesztés",
    back: "Vissza",
    next: "Tovább",
    finish: "Befejezés",
    search: "Keresés...",
    filter: "Szűrés",
    close: "Bezárás",
    language: "Nyelv",
    theme: "Téma",
    profile: "Profil",
    logout: "Kijelentkezés",
    login: "Bejelentkezés",
    error: "Hiba történt",
    success: "Sikeres művelet"
  },
  roles: {
    admin: "Adminisztrátor",
    moderator: "Moderátor",
    translator: "Fordító",
    member: "Tag",
    guest: "Vendég"
  },
  nav: {
    home: "Főoldal",
    readings: "Jóslások",
    library: "Könyvtár",
    community: "Közösség",
    shop: "Bolt",
    analysis: "Elemzés"
  },
  app: {
    title: 'Arkánum',
  },
  auth: {
    login: 'Bejelentkezés',
    register: 'Regisztráció',
    name: 'Név',
    welcome: 'Üdvözlünk az Arkánum: A Lélek Tükre világában',
  },
  menu: {
    dashboard: 'Főoldal',
    history: 'Napló',
    library: 'Tudástár',
    stats: 'Statisztikák',
    deckbuilder: 'Pakli Műhely',
    profile: 'Profil',
  },
  stats: {
    total_readings: 'Összes Húzás',
    balance: 'Elemi Egyensúly',
    fire: 'Tűz',
    water: 'Víz',
    air: 'Levegő',
    earth: 'Föld',
    major: 'Nagy Árkánum',
    minor: 'Kis Árkánum',
  },
  dashboard: {
    greeting: 'Üdv',
    sun: 'Napjegy',
    moon: 'Holdjegy',
    ascendant: 'Aszcendens',
    phase: 'Holdfázis',
    sunrise: 'Napkelte/Nyugta',
    moonrise: 'Holdkelte/Nyugta',
    planet_hour: 'Planetáris Óra',
    choose_spread: 'Kirakás Választása',
    start: 'Indítás',
    cards: 'Lap',
    day_reading: 'Napi Húzás rögzítése',
    edit: 'Szerkesztés',
    share: 'Megosztás',
    delete: 'Törlés',
    no_reading_day: 'A sors lapjai ezen a napon még rejtve maradtak.',
  },
  actions: {
    community: 'Faliújság',
    custom: 'Új Kirakás',
    quiz: 'Tudás Próba',
    deck: 'Pakli Műhely',
    stats: 'Elemzés',
  },
  profile: {
    back: 'Vissza a főoldalra',
    level_seer: 'Szintű Látnok',
    xp: 'Tapasztalat',
    badges: 'Jelvény',
    tab_details: 'Profil',
    tab_settings: 'Beállítások',
    tab_users: 'Fiókok',
    natal_chart: 'Születési Képlet (Becsült)',
    birth_card: 'Születési Kártya',
    personal_data: 'Személyes Adatok & Asztrológia',
    display_name: 'Megjelenített Név',
    birth_date: 'Születési Dátum',
    birth_time: 'Születési Idő',
    language: 'Nyelv / Language',
    deck_theme: 'Kártya Pakli Téma',
    card_back: 'Kártya Hátlap',
    avatar: 'Profilkép Választása',
    theme: 'Téma Választása',
    data_mgmt: 'Adatok kezelése',
    export: 'Mentés fájlba',
    import: 'Betöltés',
    logout: 'Kijelentkezés',
    who_reading: 'Ki olvassa a kártyákat?',
    new_seer: 'Új Látnok',
    create_profile: 'Új profil létrehozása',
    create: 'Létrehozás',
    saved: 'Adatok sikeresen mentve!',
  },
  reading: {
    back: 'Vissza',
    shuffle: 'Keverés',
    public: 'Publikus',
    private: 'Privát',
    save: 'Mentés',
    question_label: 'A kérdésed az Univerzumhoz',
    question_placeholder: 'Mire keresel választ?',
    message: 'Az Üzenet',
    print: 'Nyomtatás / PDF',
    public_success: 'Kirakás sikeresen publikálva!',
    error: 'Hiba történt.',
  }
};
