
import { Card } from '../../../types';

export const WANDS: Card[] = [
    {
        id: 'wands-1', name: 'Botok Ásza', nameEn: 'Ace of Wands', arcana: 'Minor', suit: 'Botok', number: 1,
        element: 'Tűz', astrology: 'Tűz elem gyökere (Kos/Oroszlán/Nyilas)', numerology: '1',
        keywords: ['Inspiráció', 'Kezdet', 'Lehetőség', 'Potenciál', 'Kreativitás'],
        meaningUpright: 'Új ötletek, a potenciál magva, az inspiráció érkezése, megvilágosodás, intenzív kreativitás.',
        meaningReversed: 'Ihletetlenség érzése, kreatív blokkok, az elmének pihenésre van szüksége, kiégés.',
        generalMeaning: 'A Botok Ásza a tűz elemét képviseli: vállalkozó kedv, bátorság, kockázatvállalás, lelkesedés és akaraterő.',
        loveMeaning: 'Élénk temperamentumot, fellángolást és "tűzbe jövést" jelez. Szenvedélyes kapcsolat kezdete.',
        careerMeaning: 'Felfedezhetünk magunkban egy tehetséget, vagy kapunk egy olyan feladatot, ami lelkesít és motivál.',
        advice: 'Ragadd meg a lehetőséget! Légy bátor és vállalkozó szellemű.',
        dailyMeaning: 'Ma tele leszel energiával és tettvággyal. Kezdj bele valamibe!',
        yearlyMeaning: 'A lendület éve. Most megvan benned a kellő erő ahhoz, hogy elindíts egy fontos projektet.',
        questions: ['Honnan ered a kreativitásod?', 'Milyen új szenvedélyek vannak a láthatáron?'],
        affirmation: "A ragyogó jövőmet az inspiráció és a kreativitás gyökereivel vetem el.",
        imageUrl: 'https://myralog.hu/tarot/wands-1.jpg',
        shortDesc: 'A Teremtő Szikra',
        comparison: {
            title: 'Botok Ásza vs. Kardok Ásza',
            text: 'Míg a Botok Ásza a tiszta kreatív energiát és a cselekvési vágyat jelképezi, a Kardok Ásza a mentális áttörést és a gondolati tisztánlátást hozza el. Tűz az akarat, Levegő az elme.',
            relatedCardId: 'swords-1'
        }
    },
    {
        id: 'wands-2', name: 'Botok Kettes', nameEn: '2 of Wands', arcana: 'Minor', suit: 'Botok', number: 2,
        element: 'Tűz', astrology: 'Mars a Kosban (Uralom)', numerology: '2',
        keywords: ['Tervezés', 'Jövő', 'Döntések', 'Felfedezés', 'Kaland'],
        meaningUpright: 'Jövő tervezése, előrelépés, aktiválás, lehetőségek, választás a komfortzóna és az új kaland között.',
        meaningReversed: 'Bizonytalanság a jövővel kapcsolatban, félelem a következő lépéstől.',
        generalMeaning: 'Ez a kártya a semleges álláspontot, a közömbösséget vagy a döntésképtelenséget jelzi.',
        loveMeaning: 'Langyos érzelmeket, érdektelenséget jelez. A kapcsolatban "üresjárat" van.',
        careerMeaning: 'Munkakedv hiánya, vagy olyan feladatok, amelyek ne hoznak lázba.',
        advice: 'Lépj hátra és vizsgáld meg pártatlanul a helyzetet.',
        dailyMeaning: 'Ma nehezedre eshet dönteni vagy lelkesedni. Ne erőltesd.',
        yearlyMeaning: 'Ez az év a kivárás éve lehet, ha nem viszel tudatosan tüzet az életedbe.',
        questions: ['Maradjak vagy menjek?', 'Mi van a komfortzónádon kívül?'],
        affirmation: "A világ tele van kalandlehetőségekkel.",
        imageUrl: 'https://myralog.hu/tarot/wands-2.jpg'
    },
    {
        id: 'wands-3', name: 'Botok Hármas', nameEn: '3 of Wands', arcana: 'Minor', suit: 'Botok', number: 3,
        element: 'Tűz', astrology: 'Nap a Kosban (Emelkedett)', numerology: '3',
        keywords: ['Terjeszkedés', 'Előrelátás', 'Várakozás', 'Felfedezés', 'Manifestáció'],
        meaningUpright: 'Megnyilvánuló energia, várakozás az eredményre, lehetőségek érkezése, üzleti sikerek.',
        meaningReversed: 'A csapások véget érnek, de nem álmodsz elég nagyot, a félelem blokkolja a mozgást.',
        generalMeaning: 'A Botok Hármas a szilárd alapot, a jó kilátásokat és a bizakodást jelenti.',
        loveMeaning: 'Jó alapokon nyugvó kapcsolatot, közös jövőképet jelent.',
        careerMeaning: 'Kiváló kilátásokat, biztos pozíciót és sikeres kereskedelmet jelez.',
        advice: 'Nézz előre! Tervezz hosszú távra, mert most szilárd talajon állsz.',
        dailyMeaning: 'Ma jó híreket kaphatsz, vagy sikeresen lefektetheted egy terv alapjait.',
        yearlyMeaning: 'A biztos kilátások éve. Amit most elindítasz, annak stabil jövője van.',
        questions: ['Nyitott vagy az új lehetőségekre?', 'Mit tehetsz ma a céljaidért?'],
        affirmation: "Tudom, hogy az álmom úton van.",
        imageUrl: 'https://myralog.hu/tarot/wands-3.jpg'
    },
    {
        id: 'wands-4', name: 'Botok Négyes', nameEn: '4 of Wands', arcana: 'Minor', suit: 'Botok', number: 4,
        element: 'Tűz', astrology: 'Vénusz a Kosban', numerology: '4',
        keywords: ['Ünneplés', 'Harmónia', 'Otthon', 'Közösség', 'Összetartozás'],
        meaningUpright: 'Ünneplés, jólét, mérföldkő, lelkek összejövetele, stabilitás otthon.',
        meaningReversed: 'Elfelejteni megünnepelni az egyszerű dolgokat, bizonytalanság.',
        generalMeaning: 'Ez a kártya az életörömöt, a nyitottságot és a "Isten hozott" érzést szimbolizálja.',
        loveMeaning: 'Boldog, felszabadult időszakot jelez. Biztonság, vidámság, közös ünneplés.',
        careerMeaning: 'Kiváló munkahelyi légkört, jó csapatmunkát és motivációt jelent.',
        advice: 'Nyílj meg! Lépj ki az elszigeteltségből, ünnepelj.',
        dailyMeaning: 'Ma légy nyitott és barátságos. Fogadd örömmel, ami jön.',
        yearlyMeaning: 'A nyitottság éve. Sok boldog pillanat és jó társaság vár rád.',
        questions: ['Hogyan ünnepled a győzelmeidet?', 'Mitől érzed magad teljesen otthon?'],
        affirmation: "Elkötelezettje vagyok a kapcsolatoknak.",
        imageUrl: 'https://myralog.hu/tarot/wands-4.jpg'
    },
    {
        id: 'wands-5', name: 'Botok Ötös', nameEn: '5 of Wands', arcana: 'Minor', suit: 'Botok', number: 5,
        element: 'Tűz', astrology: 'Szaturnusz az Oroszlánban', numerology: '5',
        keywords: ['Konfliktus', 'Verseny', 'Nézeteltérés', 'Kihívás', 'Ambíció'],
        meaningUpright: 'Versengés, ambíció, kihívás, mások általi ösztönzés, dinamikus energia.',
        meaningReversed: 'Együttműködési igény, túlzott versengés, szabályok be nem tartása.',
        generalMeaning: 'A kártya a versengést, az erőpróbát és a kihívást jelképezi.',
        loveMeaning: 'Szerelmi évődést, civódást jelent, ami fűszerezi a kapcsolatot.',
        careerMeaning: 'Versenyhelyzetet, konkurenciaharcot vagy munkahelyi vitákat jelez.',
        advice: 'Állj bele a küzdelembe! Maradj sportszerű.',
        dailyMeaning: 'Ma vitába keveredhetsz vagy bizonyítanod kell. Ne hagyd magad.',
        yearlyMeaning: 'A kihívások éve. Sokat kell küzdened, de ez megerősít.',
        questions: ['Hogyan segíthet a jelenlegi kihívásod a fejlődésben?', 'Hogyan használod mások sikerét motivációként?'],
        affirmation: "Felgyorsult harmóniában együtt emelkedünk.",
        imageUrl: 'https://myralog.hu/tarot/wands-5.jpg'
    },
    {
        id: 'wands-6', name: 'Botok Hatos', nameEn: '6 of Wands', arcana: 'Minor', suit: 'Botok', number: 6,
        element: 'Tűz', astrology: 'Jupiter az Oroszlánban', numerology: '6',
        keywords: ['Győzelem', 'Siker', 'Elismerés', 'Büszkeség', 'Vezetés'],
        meaningUpright: 'Vezetés, siker, teljesítmény, győzelem, optimizmus, mások inspirálása.',
        meaningReversed: 'Pesszimizmus, kapcsolat hiánya, kegyvesztettség.',
        generalMeaning: 'A győzelem, a siker és az elismerés kártyája.',
        loveMeaning: 'Boldogságot, a kapcsolat felvirágzását jelenti. Sikeres hódítás.',
        careerMeaning: 'Sikeres vizsgát, előléptetést, elismerést kapsz a munkádért.',
        advice: 'Bízz a győzelemben! Tűzz ki magas célokat.',
        dailyMeaning: 'Ma sikeres napod lesz. Valami beérik.',
        yearlyMeaning: 'A siker éve. Bármibe is fogsz, az győzelemmel végződhet.',
        questions: ['Könnyen el tudod fogadni az elismerést?', 'Mit tennél, ha tudnád, hogy nem bukhatnál el?'],
        affirmation: "Méltó vagyok a sikerre.",
        imageUrl: 'https://myralog.hu/tarot/wands-6.jpg'
    },
    {
        id: 'wands-7', name: 'Botok Hetes', nameEn: '7 of Wands', arcana: 'Minor', suit: 'Botok', number: 7,
        element: 'Tűz', astrology: 'Mars az Oroszlánban', numerology: '7',
        keywords: ['Kitartás', 'Védekezés', 'Fenntartás', 'Kihívás', 'Bátorság'],
        meaningUpright: 'Dinamikus energia, ötletek védelme, előrébb maradás, bátor önkifejezés.',
        meaningReversed: 'Megtámadva érzi magát, energetikai határok szükségessége, rágalmazás.',
        generalMeaning: 'Ez a kártya azt jelzi, hogy támadás alatt állunk, vagy erős konkurenciával kell szembenéznünk.',
        loveMeaning: 'Veszélyben érezzük a kapcsolatot. Meg kell védenünk az álláspontunkat.',
        careerMeaning: 'Irigységre, intrikára vagy éles konkurenciaharcra utal. Határozottság kell.',
        advice: 'Ne hagyd magad! Állj ki az igazadért és védd meg, ami a tiéd.',
        dailyMeaning: 'Ma kritikával vagy ellenállással találkozhatsz. Légy határozott.',
        yearlyMeaning: 'A védekezés éve. Meg kell védened az elért eredményeidet.',
        questions: ['Milyen a kapcsolatod mások véleményével?', 'Mikor érzed magad a legélénkebbnek?'],
        affirmation: "Bátran mutatkozom - és állom a sarat.",
        imageUrl: 'https://myralog.hu/tarot/wands-7.jpg'
    },
    {
        id: 'wands-8', name: 'Botok Nyolcas', nameEn: '8 of Wands', arcana: 'Minor', suit: 'Botok', number: 8,
        element: 'Tűz', astrology: 'Merkúr a Nyilasban', numerology: '8',
        keywords: ['Sebesség', 'Mozgás', 'Hírek', 'Akció', 'Változás'],
        meaningUpright: 'Sebesség, utazás, gyors döntések, közelgő pozitív válasz, jó hír.',
        meaningReversed: 'Instabilitás, késések, összpontosítatlan energia, irányhiány.',
        generalMeaning: 'A Botok Nyolcas a gyorsulást, a hirtelen eseményeket és a változást jelzi.',
        loveMeaning: 'Ámor nyila! Hirtelen fellángolás, eufória, szerelmi vallomás.',
        careerMeaning: 'Felgyorsulnak az események. Sürgős feladatok, váratlan üzleti lehetőségek.',
        advice: 'Reagálj gyorsan! Ne hezitálj, mert a lehetőség tovaszáll.',
        dailyMeaning: 'Ma pörögni fognak az események. Légy éber.',
        yearlyMeaning: 'A gyorsulás éve. Hirtelen nagyot léphetsz előre.',
        questions: ['Mire vársz?', 'Milyen a kapcsolatod az idővel?'],
        affirmation: "Itt az idő! Belezuhanok a gyorsulás áramlatába.",
        imageUrl: 'https://myralog.hu/tarot/wands-8.jpg'
    },
    {
        id: 'wands-9', name: 'Botok Kilences', nameEn: '9 of Wands', arcana: 'Minor', suit: 'Botok', number: 9,
        element: 'Tűz', astrology: 'Hold a Nyilasban', numerology: '9',
        keywords: ['Rugalmasság', 'Bátorság', 'Kitartás', 'Utolsó állomás', 'Védelem'],
        meaningUpright: 'Elszántság, rugalmasság, dac, utolsó védekezés, győzelem a nehézségek felett.',
        meaningReversed: 'Meg kell nyílni, elengedni a régi csatákat, erősebb határok.',
        generalMeaning: 'Ez a kártya a dacot, a gyanakvást és a védekező álláspontot jelzi.',
        loveMeaning: 'Félelem a sérüléstől. Bezárkózunk a múltbeli rossz tapasztalatok miatt.',
        careerMeaning: 'Ellenállás az újításokkal szemben. Túlzott óvatosság, bizalmatlanság.',
        advice: 'Ne védekezz ott, ahol nem támadnak! Engedd el a régi sérelmeket.',
        dailyMeaning: 'Ma hajlamos lehetsz a bizalmatlanságra. Vizsgáld meg, van-e alapja.',
        yearlyMeaning: 'A múlt árnyainak éve. Szembe kell nézned a régi félelmekkel.',
        questions: ['Mit tehetnél, hogy könnyebbé tett az életed?', 'Túlzottan védekezel?'],
        affirmation: "Túllépek a saját vélt korlátaimon.",
        imageUrl: 'https://myralog.hu/tarot/wands-9.jpg'
    },
    {
        id: 'wands-10', name: 'Botok Tizes', nameEn: '10 of Wands', arcana: 'Minor', suit: 'Botok', number: 10,
        element: 'Tűz', astrology: 'Szaturnusz a Nyilasban', numerology: '10',
        keywords: ['Teher', 'Felelősség', 'Küzdelem', 'Kitartás', 'Túlterheltség'],
        meaningUpright: 'Túl sok teher, felelősség, elnyomás, de közel a sikeres eredmény.',
        meaningReversed: 'Prioritás szükségessége, tehermentesség, mások elvárásainak elengedése.',
        generalMeaning: 'A túlterheltség, a stressz és a nehéz terhek kártyája.',
        loveMeaning: 'A kapcsolat teherré vált, vagy külső gondok nyomják rá a bélyegét.',
        careerMeaning: 'Túl sok munka és stressz. A sikernek nagy ára van.',
        advice: 'Fogd vissza magad! Tanulj meg nemet mondani, dobj le terheket.',
        dailyMeaning: 'Ma nehéz napod lehet. Csak a legszükségesebbet végezd el.',
        yearlyMeaning: 'A túlterhelés éve. Vigyázz az egészségedre, ne hajtsd túl magad.',
        questions: ['Ha minden mást elhagynál, mire összpontosítanál?', 'Mik a prioritásaid?'],
        affirmation: "Átadom a terheimet az univerzumra.",
        imageUrl: 'https://myralog.hu/tarot/wands-10.jpg'
    },
    {
        id: 'wands-page', name: 'Botok Apródja', nameEn: 'Page of Wands', arcana: 'Minor', suit: 'Botok', number: 11,
        element: 'Tűz', astrology: 'Tűz elem földi aspektusa', numerology: '11',
        keywords: ['Felfedezés', 'Izgalom', 'Szabadság', 'Ötletek', 'Lelkesedés'],
        meaningUpright: 'Kreatív kezdetek, új inspiráció, új készség csiszolása, kíváncsiság.',
        meaningReversed: 'Korlátozó hiedelmek, alkotói szorongás, nehéz elkezdeni.',
        generalMeaning: 'A Botok Apródja egy izgalmas lehetőséget vagy impulzust jelent.',
        loveMeaning: 'Szerelmi kaland, flört vagy egy csábító ajánlat. Frissesség.',
        careerMeaning: 'Új feladat vagy kihívás, ami felkelti az érdeklődésed.',
        advice: 'Fogadd el a kihívást! Légy nyitott az új impulzusokra.',
        dailyMeaning: 'Ma kaphatsz egy izgalmas hírt. Figyelj a jelekre.',
        yearlyMeaning: 'A felfedezés éve. Új lehetőségek, amelyek kimozdítanak a rutinból.',
        questions: ['Miből fakad a motivációd?', 'Hogyan ragadod meg a kreatív energiát?'],
        affirmation: "Álmom álmodójaként meggyújtom ezt a lángot.",
        imageUrl: 'https://myralog.hu/tarot/wands-page.jpg'
    },
    {
        id: 'wands-knight', name: 'Botok Lovagja', nameEn: 'Knight of Wands', arcana: 'Minor', suit: 'Botok', number: 12,
        element: 'Tűz', astrology: 'Nyilas / Tűz elem levegő aspektusa', numerology: '12',
        keywords: ['Energia', 'Szenvedély', 'Impulzivitás', 'Kaland', 'Karizma'],
        meaningUpright: 'Karizma, spontaneitás, gyors energia, lelkesedés, lendület.',
        meaningReversed: 'Tétovázás, önbizalom építésének igénye, habozás.',
        generalMeaning: 'A tűz, a forróság és a türelmetlenség megtestesítője.',
        loveMeaning: 'Szenvedélyes, intenzív időszak. Erős vonzerő, de lehet, hogy rövid távú.',
        careerMeaning: 'Nagy munkakedv, ambíció és kockázatvállalás. Kapkodás veszélye.',
        advice: 'Légy bátor, de ne fejetlen! Gondold át a következményeket.',
        dailyMeaning: 'Ma tele leszel tűzzel. Vigyázz, nehogy megégess másokat.',
        yearlyMeaning: 'A szenvedély éve. Intenzív élmények, de óvakodj a túlzásoktól.',
        questions: ['Mi áll a nagy álmaid útjában?', 'Mit tennél, ha nem bukhatnál el?'],
        affirmation: "A képzeletbeli törekvésemben fertőző ihletet nyilvánítok ki.",
        imageUrl: 'https://myralog.hu/tarot/wands-knight.jpg'
    },
    {
        id: 'wands-queen', name: 'Botok Királynője', nameEn: 'Queen of Wands', arcana: 'Minor', suit: 'Botok', number: 13,
        element: 'Tűz', astrology: 'Kos / Tűz elem vizes aspektusa', numerology: '13',
        keywords: ['Önbizalom', 'Függetlenség', 'Szenvedély', 'Bátorság', 'Melegség'],
        meaningUpright: 'Bátor önkifejezés, karizma, szenvedély, magabiztosság, hatalom.',
        meaningReversed: 'Önszabotázs, félelem a kockázattól, önbizalomhiány.',
        generalMeaning: 'Az életöröm, a temperamentum és a magabiztosság női oldala.',
        loveMeaning: 'Szenvedélyes, érett kapcsolat. Egyenrangú partnerség, nyitottság.',
        careerMeaning: 'Vállalkozó szellem, önállóság és sikerorientáltság.',
        advice: 'Légy magabiztos! Sugározz életörömöt és vedd kezedbe a sorsod.',
        dailyMeaning: 'Ma légy te a társaság középpontja. Irányíts határozottan.',
        yearlyMeaning: 'Az önmegvalósítás éve. Megmutathatod az erődet.',
        questions: ['Mikor érzed magad hatalmasnak?', 'Melyik részed akar vezetni?'],
        affirmation: "Fénnyel töltöm meg a világom.",
        imageUrl: 'https://myralog.hu/tarot/wands-queen.jpg'
    },
    {
        id: 'wands-king', name: 'Botok Királya', nameEn: 'King of Wands', arcana: 'Minor', suit: 'Botok', number: 14,
        element: 'Tűz', astrology: 'Oroszlán / Tűz elem tüzes aspektusa', numerology: '14',
        keywords: ['Vezetés', 'Látnok', 'Vállalkozó', 'Becsület', 'Erő'],
        meaningUpright: 'Természetes születésű vezető, kreatív látnok, félelemnélküliség.',
        meaningReversed: 'Túlságosan ambiciózus, türelmetlenség, téves látásmód.',
        generalMeaning: 'A dinamizmus, a meggyőződés és az akaraterő férfi oldala.',
        loveMeaning: 'Nagyvonalúság, szenvedély, érett férfi energia. Elköteleződés.',
        careerMeaning: 'Vezetői pozíció, motiváló erő. Nagy projektek irányítása.',
        advice: 'Cselekedj határozottan! Tűzz ki nagy célokat.',
        dailyMeaning: 'Ma vedd át az irányítást. Dönts határozottan.',
        yearlyMeaning: 'A cselekvés éve. Megvalósíthatod a legmerészebb terveidet.',
        questions: ['Hogyan nézne ki a tökéletes életed?', 'Ki segíthet a céljaidban?'],
        affirmation: "Együtt építjük a fény birodalmát.",
        imageUrl: 'https://myralog.hu/tarot/wands-king.jpg'
    }
];
